import type { CategoryData } from '../domain/content/types'

export const categoryIds: string[] = ['general', 'music', 'places']

export const categoryData: CategoryData = {
  general: {
    ca: [
      'Cadira',
      'Taula',
      'Finestra',
      'Porta',
      'Llibre',
      'Telèfon',
      'Ordinador',
      'Got',
      'Cullera',
      'Ganivet',
      'Sabata',
      'Rellotge',
      'Paraigua',
      'Motxilla',
      'Bicicleta',
      'Cotxe',
      'Llapis',
      'Got de cafè',
    ],
    en: [
      'Chair',
      'Table',
      'Window',
      'Door',
      'Book',
      'Phone',
      'Computer',
      'Glass',
      'Spoon',
      'Knife',
      'Shoe',
      'Clock',
      'Umbrella',
      'Backpack',
      'Bicycle',
      'Car',
      'Pencil',
      'Mirror',
    ],
    es: [
      'Silla',
      'Mesa',
      'Ventana',
      'Puerta',
      'Libro',
      'Teléfono',
      'Ordenador',
      'Vaso',
      'Cuchara',
      'Cuchillo',
      'Zapato',
      'Reloj',
      'Paraguas',
      'Mochila',
      'Bicicleta',
      'Coche',
      'Lápiz',
      'Espejo',
    ],
    eu: [
      'Aulkia',
      'Mahaia',
      'Leihoa',
      'Atea',
      'Liburua',
      'Telefonoa',
      'Ordenagailua',
      'Edalontzia',
      'Koilara',
      'Aiztoa',
      'Zapata',
      'Erlojua',
      'Aterkia',
      'Motxila',
      'Bizikleta',
      'Autoa',
      'Arkatza',
      'Ispilua',
    ],
    gl: [
      'Cadeira',
      'Mesa',
      'Fiestra',
      'Porta',
      'Libro',
      'Teléfono',
      'Ordenador',
      'Vaso',
      'Culler',
      'Coitelo',
      'Zapato',
      'Reloxo',
      'Paraugas',
      'Mochila',
      'Bicicleta',
      'Coche',
      'Lapis',
      'Espello',
    ],
    va: [
      'Cadira',
      'Taula',
      'Finestra',
      'Porta',
      'Llibre',
      'Telèfon',
      'Ordinador',
      'Got',
      'Cullera',
      'Ganivet',
      'Sabata',
      'Rellotge',
      'Paraigües',
      'Motxilla',
      'Bicicleta',
      'Cotxe',
      'Llapis',
      'Espill',
    ],
  },
  music: {
    ca: [
      'Guitarra',
      'Piano',
      'Violí',
      'Bateria',
      'Flauta',
      'Trompeta',
      'Saxofon',
      'Rock',
      'Jazz',
      'Flamenc',
      'Òpera',
      'Rumba catalana',
      'Sardana',
      'Cobla',
      'Manel',
      'Txarango',
      'Els Pets',
      'Sopa de Cabra',
    ],
    en: [
      'Guitar',
      'Piano',
      'Violin',
      'Drums',
      'Flute',
      'Trumpet',
      'Saxophone',
      'Rock',
      'Jazz',
      'Blues',
      'Opera',
      'Hip hop',
      'The Beatles',
      'Queen',
      'Bob Dylan',
      'David Bowie',
      'Pink Floyd',
      'Nina Simone',
    ],
    es: [
      'Guitarra',
      'Piano',
      'Violín',
      'Batería',
      'Flauta',
      'Trompeta',
      'Saxofón',
      'Rock',
      'Jazz',
      'Flamenco',
      'Reguetón',
      'Copla',
      'Rosalía',
      'Joaquín Sabina',
      'Paco de Lucía',
      'Camarón',
      'Mecano',
      'Estopa',
    ],
    eu: [
      'Gitarra',
      'Pianoa',
      'Biolina',
      'Bateria',
      'Txirula',
      'Tronpeta',
      'Saxofoia',
      'Trikitixa',
      'Alboka',
      'Txalaparta',
      'Rocka',
      'Jazza',
      'Bertsoa',
      'Ken Zazpi',
      'Berri Txarrak',
      'Mikel Laboa',
      'Benito Lertxundi',
      'Su Ta Gar',
    ],
    gl: [
      'Guitarra',
      'Piano',
      'Violín',
      'Batería',
      'Frauta',
      'Trompeta',
      'Saxofón',
      'Gaita',
      'Pandeireta',
      'Zanfona',
      'Muiñeira',
      'Rock',
      'Jazz',
      'Luar na Lubre',
      'Carlos Núñez',
      'Milladoiro',
      'Cristina Pato',
      'Os Resentidos',
    ],
    va: [
      'Guitarra',
      'Piano',
      'Violí',
      'Bateria',
      'Flauta',
      'Trompeta',
      'Saxofon',
      'Dolçaina',
      'Tabal',
      'Rock',
      'Jazz',
      'Pasdoble',
      'Muixeranga',
      'Obrint Pas',
      'La Gossa Sorda',
      'Aspencat',
      'Zoo',
      'Smoking Stains',
    ],
  },
  places: {
    ca: [
      'Platja',
      'Hospital',
      'Escola',
      'Mercat',
      'Biblioteca',
      'Aeroport',
      'Estació',
      'Museu',
      'Parc',
      'Muntanya',
      'Riu',
      'Restaurant',
      'Cinema',
      'Castell',
      'Barcelona',
      'Girona',
      'Tarragona',
      'Lleida',
    ],
    en: [
      'Beach',
      'Hospital',
      'School',
      'Market',
      'Library',
      'Airport',
      'Station',
      'Museum',
      'Park',
      'Mountain',
      'River',
      'Restaurant',
      'Cinema',
      'Castle',
      'London',
      'Paris',
      'New York',
      'Tokyo',
    ],
    es: [
      'Playa',
      'Hospital',
      'Escuela',
      'Mercado',
      'Biblioteca',
      'Aeropuerto',
      'Estación',
      'Museo',
      'Parque',
      'Montaña',
      'Río',
      'Restaurante',
      'Cine',
      'Castillo',
      'Madrid',
      'Sevilla',
      'Granada',
      'Toledo',
    ],
    eu: [
      'Hondartza',
      'Ospitalea',
      'Eskola',
      'Merkatua',
      'Liburutegia',
      'Aireportua',
      'Geltokia',
      'Museoa',
      'Parkea',
      'Mendia',
      'Ibaia',
      'Jatetxea',
      'Zinema',
      'Gaztelua',
      'Bilbo',
      'Donostia',
      'Gasteiz',
      'Iruñea',
    ],
    gl: [
      'Praia',
      'Hospital',
      'Escola',
      'Mercado',
      'Biblioteca',
      'Aeroporto',
      'Estación',
      'Museo',
      'Parque',
      'Montaña',
      'Río',
      'Restaurante',
      'Cine',
      'Castelo',
      'Santiago',
      'A Coruña',
      'Vigo',
      'Ourense',
    ],
    va: [
      'Platja',
      'Hospital',
      'Escola',
      'Mercat',
      'Biblioteca',
      'Aeroport',
      'Estació',
      'Museu',
      'Parc',
      'Muntanya',
      'Riu',
      'Restaurant',
      'Cinema',
      'Castell',
      'València',
      'Alacant',
      'Castelló',
      'Elx',
    ],
  },
}
