import type { CategoryData } from '../domain/content/types'

export const categoryIds: string[] = [
  'general',
  'music',
  'places',
  'food',
  'animals',
  'cinema',
]

export const categoryData: CategoryData = {
  general: {
    ca: [
      'Cadira',
      'Taula',
      'Finestra',
      'Porta',
      'Llibre',
      'Telèfon',
      'Ordinador',
      'Got',
      'Cullera',
      'Ganivet',
      'Sabata',
      'Rellotge',
      'Paraigua',
      'Motxilla',
      'Bicicleta',
      'Cotxe',
      'Llapis',
      'Mirall',
      'Llit',
      'Coixí',
      'Manta',
      'Tovallola',
      'Sabó',
      'Pinta',
      'Tisores',
      'Clau',
      'Bombeta',
      'Escala',
      'Cortina',
      'Estora',
      'Ampolla',
      'Forquilla',
      'Plat',
      'Calaix',
      'Maleta',
    ],
    en: [
      'Chair',
      'Table',
      'Window',
      'Door',
      'Book',
      'Phone',
      'Computer',
      'Glass',
      'Spoon',
      'Knife',
      'Shoe',
      'Clock',
      'Umbrella',
      'Backpack',
      'Bicycle',
      'Car',
      'Pencil',
      'Mirror',
      'Bed',
      'Pillow',
      'Blanket',
      'Towel',
      'Soap',
      'Comb',
      'Scissors',
      'Key',
      'Light bulb',
      'Ladder',
      'Curtain',
      'Rug',
      'Bottle',
      'Fork',
      'Plate',
      'Drawer',
      'Suitcase',
    ],
    es: [
      'Silla',
      'Mesa',
      'Ventana',
      'Puerta',
      'Libro',
      'Teléfono',
      'Ordenador',
      'Vaso',
      'Cuchara',
      'Cuchillo',
      'Zapato',
      'Reloj',
      'Paraguas',
      'Mochila',
      'Bicicleta',
      'Coche',
      'Lápiz',
      'Espejo',
      'Cama',
      'Almohada',
      'Manta',
      'Toalla',
      'Jabón',
      'Peine',
      'Tijeras',
      'Llave',
      'Bombilla',
      'Escalera',
      'Cortina',
      'Alfombra',
      'Botella',
      'Tenedor',
      'Plato',
      'Cajón',
      'Maleta',
    ],
    eu: [
      'Aulkia',
      'Mahaia',
      'Leihoa',
      'Atea',
      'Liburua',
      'Telefonoa',
      'Ordenagailua',
      'Edalontzia',
      'Koilara',
      'Aiztoa',
      'Zapata',
      'Erlojua',
      'Aterkia',
      'Motxila',
      'Bizikleta',
      'Autoa',
      'Arkatza',
      'Ispilua',
      'Ohea',
      'Burukoa',
      'Manta',
      'Eskuoihala',
      'Xaboia',
      'Orrazia',
      'Guraizeak',
      'Giltza',
      'Bonbila',
      'Eskailera',
      'Gortina',
      'Alfonbra',
      'Botila',
      'Sardexka',
      'Platera',
      'Tiradera',
      'Maleta',
    ],
    gl: [
      'Cadeira',
      'Mesa',
      'Fiestra',
      'Porta',
      'Libro',
      'Teléfono',
      'Ordenador',
      'Vaso',
      'Culler',
      'Coitelo',
      'Zapato',
      'Reloxo',
      'Paraugas',
      'Mochila',
      'Bicicleta',
      'Coche',
      'Lapis',
      'Espello',
      'Cama',
      'Almofada',
      'Manta',
      'Toalla',
      'Xabón',
      'Peite',
      'Tesoiras',
      'Chave',
      'Lámpada',
      'Escaleira',
      'Cortina',
      'Alfombra',
      'Botella',
      'Garfo',
      'Prato',
      'Caixón',
      'Maleta',
    ],
    va: [
      'Cadira',
      'Taula',
      'Finestra',
      'Porta',
      'Llibre',
      'Telèfon',
      'Ordinador',
      'Got',
      'Cullera',
      'Ganivet',
      'Sabata',
      'Rellotge',
      'Paraigües',
      'Motxilla',
      'Bicicleta',
      'Cotxe',
      'Llapis',
      'Espill',
      'Llit',
      'Coixí',
      'Manta',
      'Tovalla',
      'Sabó',
      'Pinta',
      'Estisores',
      'Clau',
      'Bombeta',
      'Escala',
      'Cortina',
      'Estora',
      'Botella',
      'Forqueta',
      'Plat',
      'Calaix',
      'Maleta',
    ],
  },
  music: {
    ca: [
      'Guitarra',
      'Piano',
      'Violí',
      'Bateria',
      'Flauta',
      'Trompeta',
      'Saxofon',
      'Rock',
      'Jazz',
      'Flamenc',
      'Òpera',
      'Rumba catalana',
      'Sardana',
      'Cobla',
      'Manel',
      'Txarango',
      'Els Pets',
      'Sopa de Cabra',
      'Antònia Font',
      'Lax’n’Busto',
      'Gossos',
      'Oques Grasses',
      'Doctor Prats',
      'Buhos',
      'Blaumut',
      'Acordió',
      'Clarinet',
      'Contrabaix',
      'Pop',
      'Reggae',
      'Salsa',
      'Tango',
      'Cor',
      'Orquestra',
      'Tenora',
    ],
    en: [
      'Guitar',
      'Piano',
      'Violin',
      'Drums',
      'Flute',
      'Trumpet',
      'Saxophone',
      'Rock',
      'Jazz',
      'Blues',
      'Opera',
      'Hip hop',
      'The Beatles',
      'Queen',
      'Bob Dylan',
      'David Bowie',
      'Pink Floyd',
      'Nina Simone',
      'Michael Jackson',
      'Madonna',
      'Elvis Presley',
      'Radiohead',
      'Amy Winehouse',
      'Beyoncé',
      'The Rolling Stones',
      'Cello',
      'Clarinet',
      'Harp',
      'Pop',
      'Reggae',
      'Country',
      'Techno',
      'Choir',
      'Orchestra',
      'Trombone',
    ],
    es: [
      'Guitarra',
      'Piano',
      'Violín',
      'Batería',
      'Flauta',
      'Trompeta',
      'Saxofón',
      'Rock',
      'Jazz',
      'Flamenco',
      'Reguetón',
      'Copla',
      'Rosalía',
      'Joaquín Sabina',
      'Paco de Lucía',
      'Camarón',
      'Mecano',
      'Estopa',
      'Alejandro Sanz',
      'Enrique Iglesias',
      'Manu Chao',
      'Extremoduro',
      'Héroes del Silencio',
      'C. Tangana',
      'Bad Bunny',
      'Violonchelo',
      'Clarinete',
      'Arpa',
      'Pop',
      'Salsa',
      'Bolero',
      'Tango',
      'Coro',
      'Orquesta',
      'Acordeón',
    ],
    eu: [
      'Gitarra',
      'Pianoa',
      'Biolina',
      'Bateria',
      'Txirula',
      'Tronpeta',
      'Saxofoia',
      'Trikitixa',
      'Alboka',
      'Txalaparta',
      'Rocka',
      'Jazza',
      'Bertsoa',
      'Ken Zazpi',
      'Berri Txarrak',
      'Mikel Laboa',
      'Benito Lertxundi',
      'Su Ta Gar',
      'Gatibu',
      'Itoiz',
      'Kortatu',
      'Negu Gorriak',
      'Oskorri',
      'Esne Beltza',
      'Zea Mays',
      'Biolontxeloa',
      'Klarinetea',
      'Arpa',
      'Popa',
      'Reggaea',
      'Punka',
      'Soinua',
      'Abesbatza',
      'Orkestra',
      'Tronboia',
    ],
    gl: [
      'Guitarra',
      'Piano',
      'Violín',
      'Batería',
      'Frauta',
      'Trompeta',
      'Saxofón',
      'Gaita',
      'Pandeireta',
      'Zanfona',
      'Muiñeira',
      'Rock',
      'Jazz',
      'Luar na Lubre',
      'Carlos Núñez',
      'Milladoiro',
      'Cristina Pato',
      'Os Resentidos',
      'Mercedes Peón',
      'Susana Seivane',
      'Heredeiros da Crus',
      'Siniestro Total',
      'Tanxugueiras',
      'Berrogüetto',
      'Sés',
      'Violonchelo',
      'Clarinete',
      'Arpa',
      'Pop',
      'Reggae',
      'Punk',
      'Tango',
      'Coro',
      'Orquestra',
      'Acordeón',
    ],
    va: [
      'Guitarra',
      'Piano',
      'Violí',
      'Bateria',
      'Flauta',
      'Trompeta',
      'Saxofon',
      'Dolçaina',
      'Tabal',
      'Rock',
      'Jazz',
      'Pasdoble',
      'Muixeranga',
      'Obrint Pas',
      'La Gossa Sorda',
      'Aspencat',
      'Zoo',
      'Smoking Stains',
      'Feliu Ventura',
      'El Diluvi',
      'Auxili',
      'Pep Gimeno Botifarra',
      'Tardor',
      'Senyor Mostaza',
      'Clarinet',
      'Violoncel',
      'Arpa',
      'Pop',
      'Reggae',
      'Salsa',
      'Tango',
      'Cor',
      'Orquestra',
      'Acordió',
      'Contrabaix',
    ],
  },
  places: {
    ca: [
      'Platja',
      'Hospital',
      'Escola',
      'Mercat',
      'Biblioteca',
      'Aeroport',
      'Estació',
      'Museu',
      'Parc',
      'Muntanya',
      'Riu',
      'Restaurant',
      'Cinema',
      'Castell',
      'Barcelona',
      'Girona',
      'Tarragona',
      'Lleida',
      'Plaça',
      'Esglèsia',
      'Farmàcia',
      'Bosc',
      'Llac',
      'Port',
      'Universitat',
      'Teatre',
      'Estadi',
      'Gimnàs',
      'Hotel',
      'Banc',
      'Fàbrica',
      'Granja',
      'Desert',
      'Cova',
      'Pont',
    ],
    en: [
      'Beach',
      'Hospital',
      'School',
      'Market',
      'Library',
      'Airport',
      'Station',
      'Museum',
      'Park',
      'Mountain',
      'River',
      'Restaurant',
      'Cinema',
      'Castle',
      'London',
      'Paris',
      'New York',
      'Tokyo',
      'Square',
      'Church',
      'Pharmacy',
      'Forest',
      'Lake',
      'Harbour',
      'University',
      'Theatre',
      'Stadium',
      'Gym',
      'Hotel',
      'Bank',
      'Factory',
      'Farm',
      'Desert',
      'Cave',
      'Bridge',
    ],
    es: [
      'Playa',
      'Hospital',
      'Escuela',
      'Mercado',
      'Biblioteca',
      'Aeropuerto',
      'Estación',
      'Museo',
      'Parque',
      'Montaña',
      'Río',
      'Restaurante',
      'Cine',
      'Castillo',
      'Madrid',
      'Sevilla',
      'Granada',
      'Toledo',
      'Plaza',
      'Iglesia',
      'Farmacia',
      'Bosque',
      'Lago',
      'Puerto',
      'Universidad',
      'Teatro',
      'Estadio',
      'Gimnasio',
      'Hotel',
      'Banco',
      'Fábrica',
      'Granja',
      'Desierto',
      'Cueva',
      'Puente',
    ],
    eu: [
      'Hondartza',
      'Ospitalea',
      'Eskola',
      'Merkatua',
      'Liburutegia',
      'Aireportua',
      'Geltokia',
      'Museoa',
      'Parkea',
      'Mendia',
      'Ibaia',
      'Jatetxea',
      'Zinema',
      'Gaztelua',
      'Bilbo',
      'Donostia',
      'Gasteiz',
      'Iruñea',
      'Plaza',
      'Eliza',
      'Farmazia',
      'Basoa',
      'Aintzira',
      'Portua',
      'Unibertsitatea',
      'Antzokia',
      'Estadioa',
      'Gimnasioa',
      'Hotela',
      'Bankua',
      'Lantegia',
      'Baserria',
      'Basamortua',
      'Leizea',
      'Zubia',
    ],
    gl: [
      'Praia',
      'Hospital',
      'Escola',
      'Mercado',
      'Biblioteca',
      'Aeroporto',
      'Estación',
      'Museo',
      'Parque',
      'Montaña',
      'Río',
      'Restaurante',
      'Cine',
      'Castelo',
      'Santiago',
      'A Coruña',
      'Vigo',
      'Ourense',
      'Praza',
      'Igrexa',
      'Farmacia',
      'Bosque',
      'Lago',
      'Porto',
      'Universidade',
      'Teatro',
      'Estadio',
      'Ximnasio',
      'Hotel',
      'Banco',
      'Fábrica',
      'Granxa',
      'Deserto',
      'Cova',
      'Ponte',
    ],
    va: [
      'Platja',
      'Hospital',
      'Escola',
      'Mercat',
      'Biblioteca',
      'Aeroport',
      'Estació',
      'Museu',
      'Parc',
      'Muntanya',
      'Riu',
      'Restaurant',
      'Cinema',
      'Castell',
      'València',
      'Alacant',
      'Castelló',
      'Elx',
      'Plaça',
      'Esglèsia',
      'Farmàcia',
      'Bosc',
      'Llac',
      'Port',
      'Universitat',
      'Teatre',
      'Estadi',
      'Gimnàs',
      'Hotel',
      'Banc',
      'Fàbrica',
      'Granja',
      'Desert',
      'Cova',
      'Pont',
    ],
  },
  food: {
    ca: [
      'Pa amb tomàquet',
      'Botifarra',
      'Escudella',
      'Fideuà',
      'Crema catalana',
      'Calçots',
      'Coca de recapte',
      'Mongetes',
      'Cargols',
      'Truita de patates',
      'Croquetes',
      'Arròs',
      'Macarrons',
      'Pizza',
      'Hamburguesa',
      'Amanida',
      'Sopa',
      'Pollastre',
      'Peix',
      'Formatge',
      'Pernil',
      'Ou',
      'Tomàquet',
      'Patata',
      'Ceba',
      'All',
      'Poma',
      'Plàtan',
      'Taronja',
      'Maduixa',
      'Xocolata',
      'Gelat',
      'Pa',
      'Llet',
      'Mel',
    ],
    en: [
      'Pizza',
      'Hamburger',
      'Spaghetti',
      'Sushi',
      'Sandwich',
      'Salad',
      'Soup',
      'Omelette',
      'Pancakes',
      'Rice',
      'Chicken',
      'Fish',
      'Cheese',
      'Ham',
      'Egg',
      'Tomato',
      'Potato',
      'Onion',
      'Garlic',
      'Apple',
      'Banana',
      'Orange',
      'Strawberry',
      'Chocolate',
      'Ice cream',
      'Bread',
      'Milk',
      'Honey',
      'Butter',
      'Coffee',
      'Tea',
      'Pasta',
      'Steak',
      'Curry',
      'Tacos',
    ],
    es: [
      'Paella',
      'Tortilla de patatas',
      'Gazpacho',
      'Cocido',
      'Croquetas',
      'Jamón',
      'Pulpo',
      'Fabada',
      'Salmorejo',
      'Churros',
      'Arroz',
      'Macarrones',
      'Pizza',
      'Hamburguesa',
      'Ensalada',
      'Sopa',
      'Pollo',
      'Pescado',
      'Queso',
      'Huevo',
      'Tomate',
      'Patata',
      'Cebolla',
      'Ajo',
      'Manzana',
      'Plátano',
      'Naranja',
      'Fresa',
      'Chocolate',
      'Helado',
      'Pan',
      'Leche',
      'Miel',
      'Café',
      'Lentejas',
    ],
    eu: [
      'Bakailaoa',
      'Marmitakoa',
      'Pintxoa',
      'Idi txuleta',
      'Piperrak',
      'Talo',
      'Gazta',
      'Sagardoa',
      'Antxoak',
      'Tortilla',
      'Arroza',
      'Makarroiak',
      'Pizza',
      'Hanburgesa',
      'Entsalada',
      'Zopa',
      'Oilaskoa',
      'Arraina',
      'Urdaiazpikoa',
      'Arrautza',
      'Tomatea',
      'Patata',
      'Tipula',
      'Baratxuria',
      'Sagarra',
      'Platanoa',
      'Laranja',
      'Marrubia',
      'Txokolatea',
      'Izozkia',
      'Ogia',
      'Esnea',
      'Eztia',
      'Kafea',
      'Babarrunak',
    ],
    gl: [
      'Pulpo á feira',
      'Empanada',
      'Lacón con grelos',
      'Caldo galego',
      'Filloas',
      'Tarta de Santiago',
      'Percebes',
      'Zamburiñas',
      'Queixo',
      'Tortilla',
      'Arroz',
      'Macarróns',
      'Pizza',
      'Hamburguesa',
      'Ensalada',
      'Sopa',
      'Polo',
      'Peixe',
      'Xamón',
      'Ovo',
      'Tomate',
      'Pataca',
      'Cebola',
      'Allo',
      'Mazá',
      'Plátano',
      'Laranxa',
      'Amorodo',
      'Chocolate',
      'Xeado',
      'Pan',
      'Leite',
      'Mel',
      'Café',
      'Lentellas',
    ],
    va: [
      'Paella',
      'Fideuà',
      'All i pebre',
      'Arròs al forn',
      'Coca de dacsa',
      'Esgarraet',
      'Olleta',
      'Bunyols',
      'Horchata',
      'Truita de creïlles',
      'Arròs',
      'Macarrons',
      'Pizza',
      'Hamburguesa',
      'Ensalada',
      'Sopa',
      'Pollastre',
      'Peix',
      'Pernil',
      'Ou',
      'Tomaca',
      'Creïlla',
      'Ceba',
      'All',
      'Poma',
      'Plàtan',
      'Taronja',
      'Maduixa',
      'Xocolata',
      'Gelat',
      'Pa',
      'Llet',
      'Mel',
      'Café',
      'Llentilles',
    ],
  },
  animals: {
    ca: [
      'Gos',
      'Gat',
      'Cavall',
      'Vaca',
      'Porc',
      'Ovella',
      'Cabra',
      'Gallina',
      'Ànec',
      'Conill',
      'Ratolí',
      'Lleó',
      'Tigre',
      'Elefant',
      'Girafa',
      'Mico',
      'Os',
      'Llop',
      'Guineu',
      'Cérvol',
      'Esquirol',
      'Àguila',
      'Mussol',
      'Pingüí',
      'Dofí',
      'Balena',
      'Tauró',
      'Pop',
      'Serp',
      'Granota',
      'Tortuga',
      'Aranya',
      'Abella',
      'Papallona',
      'Formiga',
    ],
    en: [
      'Dog',
      'Cat',
      'Horse',
      'Cow',
      'Pig',
      'Sheep',
      'Goat',
      'Hen',
      'Duck',
      'Rabbit',
      'Mouse',
      'Lion',
      'Tiger',
      'Elephant',
      'Giraffe',
      'Monkey',
      'Bear',
      'Wolf',
      'Fox',
      'Deer',
      'Squirrel',
      'Eagle',
      'Owl',
      'Penguin',
      'Dolphin',
      'Whale',
      'Shark',
      'Octopus',
      'Snake',
      'Frog',
      'Turtle',
      'Spider',
      'Bee',
      'Butterfly',
      'Ant',
    ],
    es: [
      'Perro',
      'Gato',
      'Caballo',
      'Vaca',
      'Cerdo',
      'Oveja',
      'Cabra',
      'Gallina',
      'Pato',
      'Conejo',
      'Ratón',
      'León',
      'Tigre',
      'Elefante',
      'Jirafa',
      'Mono',
      'Oso',
      'Lobo',
      'Zorro',
      'Ciervo',
      'Ardilla',
      'Águila',
      'Búho',
      'Pingüino',
      'Delfín',
      'Ballena',
      'Tiburón',
      'Pulpo',
      'Serpiente',
      'Rana',
      'Tortuga',
      'Araña',
      'Abeja',
      'Mariposa',
      'Hormiga',
    ],
    eu: [
      'Txakurra',
      'Katua',
      'Zaldia',
      'Behia',
      'Txerria',
      'Ardia',
      'Ahuntza',
      'Oiloa',
      'Ahatea',
      'Untxia',
      'Sagua',
      'Lehoia',
      'Tigrea',
      'Elefantea',
      'Jirafa',
      'Tximinoa',
      'Hartza',
      'Otsoa',
      'Azeria',
      'Oreina',
      'Urtxintxa',
      'Arranoa',
      'Hontza',
      'Pinguinoa',
      'Izurdea',
      'Balea',
      'Marrazoa',
      'Olagarroa',
      'Sugea',
      'Igela',
      'Dortoka',
      'Armiarma',
      'Erlea',
      'Tximeleta',
      'Inurria',
    ],
    gl: [
      'Can',
      'Gato',
      'Cabalo',
      'Vaca',
      'Porco',
      'Ovella',
      'Cabra',
      'Galiña',
      'Pato',
      'Coello',
      'Rato',
      'León',
      'Tigre',
      'Elefante',
      'Xirafa',
      'Mono',
      'Oso',
      'Lobo',
      'Raposo',
      'Cervo',
      'Esquío',
      'Aguia',
      'Curuxa',
      'Pingüín',
      'Golfiño',
      'Balea',
      'Quenlla',
      'Polbo',
      'Serpe',
      'Ra',
      'Tartaruga',
      'Araña',
      'Abella',
      'Bolboreta',
      'Formiga',
    ],
    va: [
      'Gos',
      'Gat',
      'Cavall',
      'Vaca',
      'Porc',
      'Ovella',
      'Cabra',
      'Gallina',
      'Ànec',
      'Conill',
      'Ratolí',
      'Lleó',
      'Tigre',
      'Elefant',
      'Girafa',
      'Mona',
      'Ós',
      'Llop',
      'Rabosa',
      'Cérvol',
      'Esquirol',
      'Àguila',
      'Mussol',
      'Pingüí',
      'Dofí',
      'Balena',
      'Tauró',
      'Polp',
      'Serp',
      'Granota',
      'Tortuga',
      'Aranya',
      'Abella',
      'Palometa',
      'Formiga',
    ],
  },
  cinema: {
    ca: [
      'Comèdia',
      'Drama',
      'Terror',
      'Acció',
      'Ciència-ficció',
      'Western',
      'Thriller',
      'Documental',
      'Animació',
      'Musical',
      'Director',
      'Actor',
      'Actriu',
      'Guionista',
      'Productor',
      'Càmera',
      'Pantalla',
      'Butaca',
      'Palomites',
      'Tràiler',
      'Estrena',
      'Oscar',
      'Festival de Sitges',
      'Pel·lícula muda',
      'Banda sonora',
      'Efectes especials',
      'Doblatge',
      'Subtítols',
      'Curtmetratge',
      'Llargmetratge',
      'Protagonista',
      'Antagonista',
      'Escena',
      'Plató',
      'Repartiment',
    ],
    en: [
      'Comedy',
      'Drama',
      'Horror',
      'Action',
      'Science fiction',
      'Western',
      'Thriller',
      'Documentary',
      'Animation',
      'Musical',
      'Director',
      'Actor',
      'Actress',
      'Screenwriter',
      'Producer',
      'Camera',
      'Screen',
      'Seat',
      'Popcorn',
      'Trailer',
      'Premiere',
      'Oscar',
      'The Godfather',
      'Star Wars',
      'Titanic',
      'Jurassic Park',
      'Soundtrack',
      'Special effects',
      'Subtitles',
      'Short film',
      'Feature film',
      'Protagonist',
      'Villain',
      'Scene',
      'Cast',
    ],
    es: [
      'Comedia',
      'Drama',
      'Terror',
      'Acción',
      'Ciencia ficción',
      'Western',
      'Thriller',
      'Documental',
      'Animación',
      'Musical',
      'Director',
      'Actor',
      'Actriz',
      'Guionista',
      'Productor',
      'Cámara',
      'Pantalla',
      'Butaca',
      'Palomitas',
      'Tráiler',
      'Estreno',
      'Goya',
      'El laberinto del fauno',
      'Mar adentro',
      'Volver',
      'Banda sonora',
      'Efectos especiales',
      'Doblaje',
      'Subtítulos',
      'Cortometraje',
      'Largometraje',
      'Protagonista',
      'Antagonista',
      'Escena',
      'Reparto',
    ],
    eu: [
      'Komedia',
      'Drama',
      'Beldurra',
      'Akzioa',
      'Zientzia fikzioa',
      'Western',
      'Thrillerra',
      'Dokumentala',
      'Animazioa',
      'Musikala',
      'Zuzendaria',
      'Aktorea',
      'Aktoresa',
      'Gidoilaria',
      'Ekoizlea',
      'Kamera',
      'Pantaila',
      'Aulkia',
      'Krispetak',
      'Trailerra',
      'Estreinaldia',
      'Loreak',
      'Handia',
      'Aupa Etxebeste',
      'Soinu banda',
      'Efektu bereziak',
      'Bikoizketa',
      'Azpitituluak',
      'Film laburra',
      'Film luzea',
      'Protagonista',
      'Antagonista',
      'Eszena',
      'Aktore taldea',
      'Zinema aretoa',
    ],
    gl: [
      'Comedia',
      'Drama',
      'Terror',
      'Acción',
      'Ciencia ficción',
      'Western',
      'Thriller',
      'Documental',
      'Animación',
      'Musical',
      'Director',
      'Actor',
      'Actriz',
      'Guionista',
      'Produtor',
      'Cámara',
      'Pantalla',
      'Butaca',
      'Pipas',
      'Tráiler',
      'Estrea',
      'Oscar',
      'O bosque animado',
      'A lingua das bolboretas',
      'Banda sonora',
      'Efectos especiais',
      'Dobraxe',
      'Subtítulos',
      'Curtametraxe',
      'Longametraxe',
      'Protagonista',
      'Antagonista',
      'Escena',
      'Reparto',
      'Sala de cine',
    ],
    va: [
      'Comèdia',
      'Drama',
      'Terror',
      'Acció',
      'Ciència-ficció',
      'Western',
      'Thriller',
      'Documental',
      'Animació',
      'Musical',
      'Director',
      'Actor',
      'Actriu',
      'Guionista',
      'Productor',
      'Càmera',
      'Pantalla',
      'Butaca',
      'Crispetes',
      'Tràiler',
      'Estrena',
      'Oscar',
      'Banda sonora',
      'Efectes especials',
      'Doblatge',
      'Subtítols',
      'Curtmetratge',
      'Llargmetratge',
      'Protagonista',
      'Antagonista',
      'Escena',
      'Plató',
      'Repartiment',
      'Sala de cine',
      'Cartellera',
    ],
  },
}
