import type { WordEntry } from '../../domain/content/types'
import type { LocaleCode } from '../../domain/game/types'

export const animals: Partial<Record<LocaleCode, WordEntry[]>> = {
  ca: [
    { word: 'Gos', hint: 'Lleial' },
    { word: 'Gat', hint: 'Ronroneja' },
    { word: 'Cavall', hint: 'Galopa' },
    { word: 'Vaca', hint: 'Pastura' },
    { word: 'Porc', hint: 'Fang' },
    { word: 'Ovella', hint: 'Llana' },
    { word: 'Cabra', hint: 'Cingles' },
    { word: 'Gallina', hint: 'Corral' },
    { word: 'Ànec', hint: 'Estany' },
    { word: 'Conill', hint: 'Cau' },
    { word: 'Ratolí', hint: 'Formatge' },
    { word: 'Lleó', hint: 'Sabana' },
    { word: 'Tigre', hint: 'Ratlles' },
    { word: 'Elefant', hint: 'Trompa' },
    { word: 'Girafa', hint: 'Coll llarg' },
    { word: 'Mico', hint: 'Arbres' },
    { word: 'Os', hint: 'Hibernació' },
    { word: 'Llop', hint: 'Manada' },
    { word: 'Guineu', hint: 'Astuta' },
    { word: 'Cérvol', hint: 'Banyes' },
    { word: 'Esquirol', hint: 'Glans' },
    { word: 'Àguila', hint: 'Cel' },
    { word: 'Mussol', hint: 'Nocturn' },
    { word: 'Pingüí', hint: 'Gel' },
    { word: 'Dofí', hint: 'Intel·ligent' },
    { word: 'Balena', hint: 'Oceà' },
    { word: 'Tauró', hint: 'Aletes' },
    { word: 'Serp', hint: 'Repta' },
    { word: 'Granota', hint: 'Bassa' },
    { word: 'Tortuga', hint: 'Closca' },
    { word: 'Aranya', hint: 'Teranyina' },
    { word: 'Abella', hint: 'Mel' },
    { word: 'Papallona', hint: 'Vol' },
    { word: 'Formiga', hint: 'Formiguer' },
  ],
  en: [
    { word: 'Dog', hint: 'Loyal' },
    { word: 'Cat', hint: 'Purrs' },
    { word: 'Horse', hint: 'Gallops' },
    { word: 'Cow', hint: 'Pasture' },
    { word: 'Pig', hint: 'Mud' },
    { word: 'Sheep', hint: 'Wool' },
    { word: 'Goat', hint: 'Cliffs' },
    { word: 'Hen', hint: 'Barnyard' },
    { word: 'Duck', hint: 'Pond' },
    { word: 'Rabbit', hint: 'Burrow' },
    { word: 'Mouse', hint: 'Cheese' },
    { word: 'Lion', hint: 'Savanna' },
    { word: 'Tiger', hint: 'Stripes' },
    { word: 'Elephant', hint: 'Trunk' },
    { word: 'Giraffe', hint: 'Long neck' },
    { word: 'Monkey', hint: 'Trees' },
    { word: 'Bear', hint: 'Hibernation' },
    { word: 'Wolf', hint: 'Pack' },
    { word: 'Fox', hint: 'Cunning' },
    { word: 'Deer', hint: 'Antlers' },
    { word: 'Squirrel', hint: 'Acorns' },
    { word: 'Eagle', hint: 'Sky' },
    { word: 'Owl', hint: 'Nocturnal' },
    { word: 'Penguin', hint: 'Ice' },
    { word: 'Dolphin', hint: 'Clever' },
    { word: 'Whale', hint: 'Ocean' },
    { word: 'Shark', hint: 'Fins' },
    { word: 'Snake', hint: 'Slithers' },
    { word: 'Frog', hint: 'Pond' },
    { word: 'Turtle', hint: 'Shell' },
    { word: 'Spider', hint: 'Web' },
    { word: 'Bee', hint: 'Honey' },
    { word: 'Butterfly', hint: 'Flutters' },
    { word: 'Ant', hint: 'Colony' },
  ],
  es: [
    { word: 'Perro', hint: 'Leal' },
    { word: 'Gato', hint: 'Ronronea' },
    { word: 'Caballo', hint: 'Galopa' },
    { word: 'Vaca', hint: 'Pasto' },
    { word: 'Cerdo', hint: 'Barro' },
    { word: 'Oveja', hint: 'Lana' },
    { word: 'Cabra', hint: 'Riscos' },
    { word: 'Gallina', hint: 'Corral' },
    { word: 'Pato', hint: 'Estanque' },
    { word: 'Conejo', hint: 'Madriguera' },
    { word: 'Ratón', hint: 'Queso' },
    { word: 'León', hint: 'Sabana' },
    { word: 'Tigre', hint: 'Rayas' },
    { word: 'Elefante', hint: 'Trompa' },
    { word: 'Jirafa', hint: 'Cuello largo' },
    { word: 'Mono', hint: 'Árboles' },
    { word: 'Oso', hint: 'Hibernación' },
    { word: 'Lobo', hint: 'Manada' },
    { word: 'Zorro', hint: 'Astuto' },
    { word: 'Ciervo', hint: 'Cuernos' },
    { word: 'Ardilla', hint: 'Bellotas' },
    { word: 'Águila', hint: 'Cielo' },
    { word: 'Búho', hint: 'Nocturno' },
    { word: 'Pingüino', hint: 'Hielo' },
    { word: 'Delfín', hint: 'Inteligente' },
    { word: 'Ballena', hint: 'Océano' },
    { word: 'Tiburón', hint: 'Aletas' },
    { word: 'Serpiente', hint: 'Repta' },
    { word: 'Rana', hint: 'Charca' },
    { word: 'Tortuga', hint: 'Caparazón' },
    { word: 'Araña', hint: 'Ocho patas' },
    { word: 'Abeja', hint: 'Miel' },
    { word: 'Mariposa', hint: 'Vuela' },
    { word: 'Hormiga', hint: 'Hormiguero' },
  ],
  eu: [
    { word: 'Txakurra', hint: 'Leiala' },
    { word: 'Katua', hint: 'Purr' },
    { word: 'Zaldia', hint: 'Lauhazka' },
    { word: 'Behia', hint: 'Larrea' },
    { word: 'Txerria', hint: 'Lokatza' },
    { word: 'Ardia', hint: 'Artilea' },
    { word: 'Ahuntza', hint: 'Malkarrak' },
    { word: 'Oiloa', hint: 'Oilategia' },
    { word: 'Ahatea', hint: 'Urmaela' },
    { word: 'Untxia', hint: 'Zuloa' },
    { word: 'Sagua', hint: 'Gazta' },
    { word: 'Lehoia', hint: 'Sabana' },
    { word: 'Tigrea', hint: 'Marrak' },
    { word: 'Elefantea', hint: 'Tronpa' },
    { word: 'Jirafa', hint: 'Lepo luzea' },
    { word: 'Tximinoa', hint: 'Zuhaitzak' },
    { word: 'Hartza', hint: 'Negu loa' },
    { word: 'Otsoa', hint: 'Taldea' },
    { word: 'Azeria', hint: 'Maltzurra' },
    { word: 'Oreina', hint: 'Adarrak' },
    { word: 'Urtxintxa', hint: 'Ezkurrak' },
    { word: 'Arranoa', hint: 'Zerua' },
    { word: 'Hontza', hint: 'Gauekoa' },
    { word: 'Pinguinoa', hint: 'Izotza' },
    { word: 'Izurdea', hint: 'Adimentsua' },
    { word: 'Balea', hint: 'Ozeanoa' },
    { word: 'Marrazoa', hint: 'Hegatsak' },
    { word: 'Sugea', hint: 'Narrasti' },
    { word: 'Igela', hint: 'Putzua' },
    { word: 'Dortoka', hint: 'Oskola' },
    { word: 'Armiarma', hint: 'Sarea' },
    { word: 'Erlea', hint: 'Eztia' },
    { word: 'Tximeleta', hint: 'Hegan' },
    { word: 'Inurria', hint: 'Inurritegia' },
  ],
  gl: [
    { word: 'Can', hint: 'Leal' },
    { word: 'Gato', hint: 'Ronrón' },
    { word: 'Cabalo', hint: 'Galope' },
    { word: 'Vaca', hint: 'Pasto' },
    { word: 'Porco', hint: 'Lama' },
    { word: 'Ovella', hint: 'Rabaño' },
    { word: 'Cabra', hint: 'Penedos' },
    { word: 'Galiña', hint: 'Curral' },
    { word: 'Pato', hint: 'Lagoa' },
    { word: 'Coello', hint: 'Tobeira' },
    { word: 'Rato', hint: 'Queixo' },
    { word: 'León', hint: 'Sabana' },
    { word: 'Tigre', hint: 'Raias' },
    { word: 'Elefante', hint: 'Trompa' },
    { word: 'Xirafa', hint: 'Pescozo longo' },
    { word: 'Mono', hint: 'Árbores' },
    { word: 'Oso', hint: 'Hibernación' },
    { word: 'Lobo', hint: 'Manda' },
    { word: 'Raposo', hint: 'Astuto' },
    { word: 'Cervo', hint: 'Cornos' },
    { word: 'Esquío', hint: 'Landras' },
    { word: 'Aguia', hint: 'Ceo' },
    { word: 'Curuxa', hint: 'Nocturna' },
    { word: 'Pingüín', hint: 'Xeo' },
    { word: 'Golfiño', hint: 'Intelixente' },
    { word: 'Balea', hint: 'Océano' },
    { word: 'Quenlla', hint: 'Aletas' },
    { word: 'Serpe', hint: 'Repta' },
    { word: 'Ra', hint: 'Charca' },
    { word: 'Tartaruga', hint: 'Cuncha' },
    { word: 'Araña', hint: 'Teaa' },
    { word: 'Abella', hint: 'Mel' },
    { word: 'Bolboreta', hint: 'Voa' },
    { word: 'Formiga', hint: 'Formigueiro' },
  ],
  va: [
    { word: 'Gos', hint: 'Lleial' },
    { word: 'Gat', hint: 'Ronrolla' },
    { word: 'Cavall', hint: 'Galopa' },
    { word: 'Vaca', hint: 'Pastura' },
    { word: 'Porc', hint: 'Fang' },
    { word: 'Ovella', hint: 'Llana' },
    { word: 'Cabra', hint: 'Penyes' },
    { word: 'Gallina', hint: 'Corral' },
    { word: 'Ànec', hint: 'Bassa' },
    { word: 'Conill', hint: 'Cau' },
    { word: 'Ratolí', hint: 'Formatge' },
    { word: 'Lleó', hint: 'Sabana' },
    { word: 'Tigre', hint: 'Ratlles' },
    { word: 'Elefant', hint: 'Trompa' },
    { word: 'Girafa', hint: 'Coll llarg' },
    { word: 'Mona', hint: 'Arbres' },
    { word: 'Ós', hint: 'Hibernació' },
    { word: 'Llop', hint: 'Ramat' },
    { word: 'Rabosa', hint: 'Astuta' },
    { word: 'Cérvol', hint: 'Banyes' },
    { word: 'Esquirol', hint: 'Aglans' },
    { word: 'Àguila', hint: 'Cel' },
    { word: 'Mussol', hint: 'Nocturn' },
    { word: 'Pingüí', hint: 'Gel' },
    { word: 'Dofí', hint: 'Intel·ligent' },
    { word: 'Balena', hint: 'Oceà' },
    { word: 'Tauró', hint: 'Aletes' },
    { word: 'Serp', hint: 'Repta' },
    { word: 'Granota', hint: 'Bassal' },
    { word: 'Tortuga', hint: 'Closca' },
    { word: 'Aranya', hint: 'Teranyina' },
    { word: 'Abella', hint: 'Mel' },
    { word: 'Palometa', hint: 'Vola' },
    { word: 'Formiga', hint: 'Formiguer' },
  ],
}
