import type { WordEntry } from '../../domain/content/types'
import type { LocaleCode } from '../../domain/game/types'

export const animals: Partial<Record<LocaleCode, WordEntry[]>> = {
  ca: [
    { word: 'Gos', hints: ['Lleial', 'Lladra', 'Mossega'] },
    { word: 'Gat', hints: ['Ronroneja', 'Bigotis', 'Miol'] },
    { word: 'Cavall', hints: ['Galopa', 'Crinera', 'Ferradura'] },
    { word: 'Vaca', hints: ['Pastura', 'Llet', 'Mugeix'] },
    { word: 'Porc', hints: ['Fang', 'Cua rissada', 'Gruny'] },
    { word: 'Ovella', hints: ['Llana', 'Ramat', 'Bela'] },
    { word: 'Cabra', hints: ['Cingles', 'Banyes', 'Salta'] },
    { word: 'Gallina', hints: ['Corral', 'Ous', 'Escataina'] },
    { word: 'Ànec', hints: ['Estany', 'Bec pla', 'Neda'] },
    { word: 'Conill', hints: ['Cau', 'Orelles llargues', 'Pastanaga'] },
    { word: 'Ratolí', hints: ['Formatge', 'Cua fina', 'Forat'] },
    { word: 'Lleó', hints: ['Sabana', 'Melena', 'Rugit'] },
    { word: 'Tigre', hints: ['Ratlles', 'Felí', 'Jungla'] },
    { word: 'Elefant', hints: ['Trompa', 'Ullals', 'Enorme'] },
    { word: 'Girafa', hints: ['Coll llarg', 'Taques', 'Savana'] },
    { word: 'Mico', hints: ['Arbres', 'Plàtan', 'Salta'] },
    { word: 'Os', hints: ['Hibernació', 'Mel', 'Cova'] },
    { word: 'Llop', hints: ['Manada', 'Udol', 'Bosc'] },
    { word: 'Guineu', hints: ['Astuta', 'Cua roja', 'Caça'] },
    { word: 'Cérvol', hints: ['Banyes', 'Bosc', 'Salta'] },
    { word: 'Esquirol', hints: ['Glans', 'Cua peluda', 'Branques'] },
    { word: 'Àguila', hints: ['Cel', 'Becut', 'Vista'] },
    { word: 'Mussol', hints: ['Nocturn', 'Ulls grans', 'Nit'] },
    { word: 'Pingüí', hints: ['Gel', 'Frac', 'Neda'] },
    { word: 'Dofí', hints: ['Intel·ligent', 'Salta', 'Mar'] },
    { word: 'Balena', hints: ['Oceà', 'Gegant', 'Brolla'] },
    { word: 'Tauró', hints: ['Aletes', 'Dents', 'Depredador'] },
    { word: 'Serp', hints: ['Repta', 'Verí', 'Sense potes'] },
    { word: 'Granota', hints: ['Bassa', 'Salta', 'Verda'] },
    { word: 'Tortuga', hints: ['Closca', 'Lenta', 'Aigua'] },
    { word: 'Aranya', hints: ['Teranyina', 'Vuit potes', 'Insectes'] },
    { word: 'Abella', hints: ['Mel', 'Rusc', 'Pica'] },
    { word: 'Papallona', hints: ['Vol', 'Ales', 'Flors'] },
    { word: 'Formiga', hints: ['Formiguer', 'Treballadora', 'Petita'] },
  ],
  en: [
    { word: 'Dog', hints: ['Loyal', 'Barks', 'Fetch'] },
    { word: 'Cat', hints: ['Purrs', 'Whiskers', 'Meow'] },
    { word: 'Horse', hints: ['Gallops', 'Mane', 'Saddle'] },
    { word: 'Cow', hints: ['Pasture', 'Milk', 'Moo'] },
    { word: 'Pig', hints: ['Mud', 'Curly tail', 'Oink'] },
    { word: 'Sheep', hints: ['Wool', 'Flock', 'Baa'] },
    { word: 'Goat', hints: ['Cliffs', 'Horns', 'Climbs'] },
    { word: 'Hen', hints: ['Barnyard', 'Eggs', 'Clucks'] },
    { word: 'Duck', hints: ['Pond', 'Webbed feet', 'Quack'] },
    { word: 'Rabbit', hints: ['Burrow', 'Long ears', 'Carrot'] },
    { word: 'Mouse', hints: ['Cheese', 'Tiny', 'Squeak'] },
    { word: 'Lion', hints: ['Savanna', 'Mane', 'Roar'] },
    { word: 'Tiger', hints: ['Stripes', 'Feline', 'Jungle'] },
    { word: 'Elephant', hints: ['Trunk', 'Tusks', 'Huge'] },
    { word: 'Giraffe', hints: ['Long neck', 'Spots', 'Tall'] },
    { word: 'Monkey', hints: ['Trees', 'Banana', 'Swings'] },
    { word: 'Bear', hints: ['Hibernation', 'Honey', 'Cave'] },
    { word: 'Wolf', hints: ['Pack', 'Howl', 'Forest'] },
    { word: 'Fox', hints: ['Cunning', 'Red tail', 'Sly'] },
    { word: 'Deer', hints: ['Antlers', 'Forest', 'Leaps'] },
    { word: 'Squirrel', hints: ['Acorns', 'Bushy tail', 'Branches'] },
    { word: 'Eagle', hints: ['Sky', 'Talons', 'Sharp eyes'] },
    { word: 'Owl', hints: ['Nocturnal', 'Big eyes', 'Hoots'] },
    { word: 'Penguin', hints: ['Ice', 'Tuxedo', 'Swims'] },
    { word: 'Dolphin', hints: ['Clever', 'Leaps', 'Sea'] },
    { word: 'Whale', hints: ['Ocean', 'Giant', 'Spouts'] },
    { word: 'Shark', hints: ['Fins', 'Teeth', 'Predator'] },
    { word: 'Snake', hints: ['Slithers', 'Venom', 'No legs'] },
    { word: 'Frog', hints: ['Pond', 'Hops', 'Green'] },
    { word: 'Turtle', hints: ['Shell', 'Slow', 'Water'] },
    { word: 'Spider', hints: ['Web', 'Eight legs', 'Bugs'] },
    { word: 'Bee', hints: ['Honey', 'Hive', 'Sting'] },
    { word: 'Butterfly', hints: ['Flutters', 'Wings', 'Flowers'] },
    { word: 'Ant', hints: ['Colony', 'Worker', 'Tiny'] },
  ],
  es: [
    { word: 'Perro', hints: ['Leal', 'Ladra', 'Hueso'] },
    { word: 'Gato', hints: ['Ronronea', 'Bigotes', 'Maúlla'] },
    { word: 'Caballo', hints: ['Galopa', 'Crin', 'Herradura'] },
    { word: 'Vaca', hints: ['Pasto', 'Leche', 'Muge'] },
    { word: 'Cerdo', hints: ['Barro', 'Rabo rizado', 'Gruñe'] },
    { word: 'Oveja', hints: ['Lana', 'Rebaño', 'Bala'] },
    { word: 'Cabra', hints: ['Riscos', 'Cuernos', 'Trepa'] },
    { word: 'Gallina', hints: ['Corral', 'Huevos', 'Cacarea'] },
    { word: 'Pato', hints: ['Estanque', 'Pico plano', 'Nada'] },
    { word: 'Conejo', hints: ['Madriguera', 'Orejas largas', 'Zanahoria'] },
    { word: 'Ratón', hints: ['Queso', 'Cola fina', 'Agujero'] },
    { word: 'León', hints: ['Sabana', 'Melena', 'Ruge'] },
    { word: 'Tigre', hints: ['Rayas', 'Felino', 'Selva'] },
    { word: 'Elefante', hints: ['Trompa', 'Colmillos', 'Enorme'] },
    { word: 'Jirafa', hints: ['Cuello largo', 'Manchas', 'Alta'] },
    { word: 'Mono', hints: ['Árboles', 'Plátano', 'Salta'] },
    { word: 'Oso', hints: ['Hibernación', 'Miel', 'Cueva'] },
    { word: 'Lobo', hints: ['Manada', 'Aúlla', 'Bosque'] },
    { word: 'Zorro', hints: ['Astuto', 'Cola roja', 'Caza'] },
    { word: 'Ciervo', hints: ['Cuernos', 'Bosque', 'Salta'] },
    { word: 'Ardilla', hints: ['Bellotas', 'Cola peluda', 'Ramas'] },
    { word: 'Águila', hints: ['Cielo', 'Garras', 'Vista'] },
    { word: 'Búho', hints: ['Nocturno', 'Ojos grandes', 'Noche'] },
    { word: 'Pingüino', hints: ['Hielo', 'Frac', 'Nada'] },
    { word: 'Delfín', hints: ['Inteligente', 'Salta', 'Mar'] },
    { word: 'Ballena', hints: ['Océano', 'Gigante', 'Chorro'] },
    { word: 'Tiburón', hints: ['Aletas', 'Dientes', 'Depredador'] },
    { word: 'Serpiente', hints: ['Repta', 'Veneno', 'Sin patas'] },
    { word: 'Rana', hints: ['Charca', 'Salta', 'Verde'] },
    { word: 'Tortuga', hints: ['Caparazón', 'Lenta', 'Agua'] },
    { word: 'Araña', hints: ['Ocho patas', 'Tela', 'Insectos'] },
    { word: 'Abeja', hints: ['Miel', 'Colmena', 'Pica'] },
    { word: 'Mariposa', hints: ['Vuela', 'Alas', 'Flores'] },
    { word: 'Hormiga', hints: ['Hormiguero', 'Trabajadora', 'Diminuta'] },
  ],
  eu: [
    { word: 'Txakurra', hints: ['Leiala', 'Zaunka', 'Hezurra'] },
    { word: 'Katua', hints: ['Purr', 'Bibote', 'Miau'] },
    { word: 'Zaldia', hints: ['Lauhazka', 'Zurda', 'Ferra'] },
    { word: 'Behia', hints: ['Larrea', 'Esnea', 'Muu'] },
    { word: 'Txerria', hints: ['Lokatza', 'Buztan kizkurra', 'Marru'] },
    { word: 'Ardia', hints: ['Artilea', 'Artaldea', 'Bee'] },
    { word: 'Ahuntza', hints: ['Malkarrak', 'Adarrak', 'Igo'] },
    { word: 'Oiloa', hints: ['Oilategia', 'Arrautzak', 'Kokoreko'] },
    { word: 'Ahatea', hints: ['Urmaela', 'Moko zabala', 'Igeri'] },
    { word: 'Untxia', hints: ['Zuloa', 'Belarri luzeak', 'Azenarioa'] },
    { word: 'Sagua', hints: ['Gazta', 'Buztan mehea', 'Txikia'] },
    { word: 'Lehoia', hints: ['Sabana', 'Zurda', 'Orro'] },
    { word: 'Tigrea', hints: ['Marrak', 'Felidoa', 'Oihana'] },
    { word: 'Elefantea', hints: ['Tronpa', 'Letaginak', 'Erraldoia'] },
    { word: 'Jirafa', hints: ['Lepo luzea', 'Orbanak', 'Garaia'] },
    { word: 'Tximinoa', hints: ['Zuhaitzak', 'Banana', 'Jauzi'] },
    { word: 'Hartza', hints: ['Negu loa', 'Eztia', 'Haitzuloa'] },
    { word: 'Otsoa', hints: ['Taldea', 'Uluak', 'Basoa'] },
    { word: 'Azeria', hints: ['Maltzurra', 'Buztan gorria', 'Ehiza'] },
    { word: 'Oreina', hints: ['Adarrak', 'Basoa', 'Jauzi'] },
    { word: 'Urtxintxa', hints: ['Ezkurrak', 'Buztan iletsua', 'Adarrak'] },
    { word: 'Arranoa', hints: ['Zerua', 'Atzaparrak', 'Begiak'] },
    { word: 'Hontza', hints: ['Gauekoa', 'Begi handiak', 'Iluna'] },
    { word: 'Pinguinoa', hints: ['Izotza', 'Fraka', 'Igeri'] },
    { word: 'Izurdea', hints: ['Adimentsua', 'Jauzi', 'Itsasoa'] },
    { word: 'Balea', hints: ['Ozeanoa', 'Erraldoia', 'Ura'] },
    { word: 'Marrazoa', hints: ['Hegatsak', 'Hortzak', 'Harraparia'] },
    { word: 'Sugea', hints: ['Narrasti', 'Pozoia', 'Hankarik gabe'] },
    { word: 'Igela', hints: ['Putzua', 'Jauzi', 'Berdea'] },
    { word: 'Dortoka', hints: ['Oskola', 'Geldoa', 'Ura'] },
    { word: 'Armiarma', hints: ['Sarea', 'Zortzi hanka', 'Intsektuak'] },
    { word: 'Erlea', hints: ['Eztia', 'Erlauntza', 'Ziztada'] },
    { word: 'Tximeleta', hints: ['Hegan', 'Hegoak', 'Loreak'] },
    { word: 'Inurria', hints: ['Inurritegia', 'Langilea', 'Txikia'] },
  ],
  gl: [
    { word: 'Can', hints: ['Leal', 'Ladra', 'Óso'] },
    { word: 'Gato', hints: ['Ronrón', 'Bigotes', 'Miaña'] },
    { word: 'Cabalo', hints: ['Galope', 'Crina', 'Ferradura'] },
    { word: 'Vaca', hints: ['Pasto', 'Leite', 'Muxe'] },
    { word: 'Porco', hints: ['Lama', 'Rabo rizo', 'Gruñe'] },
    { word: 'Ovella', hints: ['Rabaño', 'Lá', 'Bala'] },
    { word: 'Cabra', hints: ['Penedos', 'Cornos', 'Trepa'] },
    { word: 'Galiña', hints: ['Curral', 'Ovos', 'Cacarexa'] },
    { word: 'Pato', hints: ['Lagoa', 'Pico plano', 'Nada'] },
    { word: 'Coello', hints: ['Tobeira', 'Orellas longas', 'Cenoria'] },
    { word: 'Rato', hints: ['Queixo', 'Rabo fino', 'Furado'] },
    { word: 'León', hints: ['Sabana', 'Melena', 'Ruxe'] },
    { word: 'Tigre', hints: ['Raias', 'Felino', 'Selva'] },
    { word: 'Elefante', hints: ['Trompa', 'Cabeiros', 'Enorme'] },
    { word: 'Xirafa', hints: ['Pescozo longo', 'Manchas', 'Alta'] },
    { word: 'Mono', hints: ['Árbores', 'Plátano', 'Salta'] },
    { word: 'Oso', hints: ['Hibernación', 'Mel', 'Cova'] },
    { word: 'Lobo', hints: ['Manda', 'Oubea', 'Bosque'] },
    { word: 'Raposo', hints: ['Astuto', 'Rabo vermello', 'Caza'] },
    { word: 'Cervo', hints: ['Cornos', 'Bosque', 'Salta'] },
    { word: 'Esquío', hints: ['Landras', 'Rabo peludo', 'Pólas'] },
    { word: 'Aguia', hints: ['Ceo', 'Gadoupas', 'Vista'] },
    { word: 'Curuxa', hints: ['Nocturna', 'Ollos grandes', 'Noite'] },
    { word: 'Pingüín', hints: ['Xeo', 'Frac', 'Nada'] },
    { word: 'Golfiño', hints: ['Intelixente', 'Salta', 'Mar'] },
    { word: 'Balea', hints: ['Océano', 'Xigante', 'Chorro'] },
    { word: 'Quenlla', hints: ['Aletas', 'Dentes', 'Depredador'] },
    { word: 'Serpe', hints: ['Repta', 'Veleno', 'Sen patas'] },
    { word: 'Ra', hints: ['Charca', 'Salta', 'Verde'] },
    { word: 'Tartaruga', hints: ['Cuncha', 'Lenta', 'Auga'] },
    { word: 'Araña', hints: ['Teaa', 'Oito patas', 'Insectos'] },
    { word: 'Abella', hints: ['Mel', 'Colmea', 'Pica'] },
    { word: 'Bolboreta', hints: ['Voa', 'Ás', 'Flores'] },
    { word: 'Formiga', hints: ['Formigueiro', 'Traballadora', 'Pequena'] },
  ],
  va: [
    { word: 'Gos', hints: ['Lleial', 'Lladra', 'Mossega'] },
    { word: 'Gat', hints: ['Ronrolla', 'Bigotis', 'Miol'] },
    { word: 'Cavall', hints: ['Galopa', 'Crinera', 'Ferradura'] },
    { word: 'Vaca', hints: ['Pastura', 'Llet', 'Mugix'] },
    { word: 'Porc', hints: ['Fang', 'Cua rissada', 'Gruny'] },
    { word: 'Ovella', hints: ['Llana', 'Ramat', 'Bela'] },
    { word: 'Cabra', hints: ['Penyes', 'Banyes', 'Salta'] },
    { word: 'Gallina', hints: ['Corral', 'Ous', 'Escataina'] },
    { word: 'Ànec', hints: ['Bassa', 'Bec pla', 'Neda'] },
    { word: 'Conill', hints: ['Cau', 'Orelles llargues', 'Safanòria'] },
    { word: 'Ratolí', hints: ['Formatge', 'Cua fina', 'Forat'] },
    { word: 'Lleó', hints: ['Sabana', 'Melena', 'Rugit'] },
    { word: 'Tigre', hints: ['Ratlles', 'Felí', 'Selva'] },
    { word: 'Elefant', hints: ['Trompa', 'Ullals', 'Enorme'] },
    { word: 'Girafa', hints: ['Coll llarg', 'Taques', 'Alta'] },
    { word: 'Mona', hints: ['Arbres', 'Plàtan', 'Salta'] },
    { word: 'Ós', hints: ['Hibernació', 'Mel', 'Cova'] },
    { word: 'Llop', hints: ['Ramat', 'Udol', 'Bosc'] },
    { word: 'Rabosa', hints: ['Astuta', 'Cua roja', 'Caça'] },
    { word: 'Cérvol', hints: ['Banyes', 'Bosc', 'Salta'] },
    { word: 'Esquirol', hints: ['Aglans', 'Cua peluda', 'Branques'] },
    { word: 'Àguila', hints: ['Cel', 'Becut', 'Vista'] },
    { word: 'Mussol', hints: ['Nocturn', 'Ulls grans', 'Nit'] },
    { word: 'Pingüí', hints: ['Gel', 'Frac', 'Neda'] },
    { word: 'Dofí', hints: ['Intel·ligent', 'Salta', 'Mar'] },
    { word: 'Balena', hints: ['Oceà', 'Gegant', 'Brolla'] },
    { word: 'Tauró', hints: ['Aletes', 'Dents', 'Depredador'] },
    { word: 'Serp', hints: ['Repta', 'Verí', 'Sense potes'] },
    { word: 'Granota', hints: ['Bassal', 'Salta', 'Verda'] },
    { word: 'Tortuga', hints: ['Closca', 'Lenta', 'Aigua'] },
    { word: 'Aranya', hints: ['Teranyina', 'Vuit potes', 'Insectes'] },
    { word: 'Abella', hints: ['Mel', 'Rusc', 'Pica'] },
    { word: 'Palometa', hints: ['Vola', 'Ales', 'Flors'] },
    { word: 'Formiga', hints: ['Formiguer', 'Treballadora', 'Menuda'] },
  ],
}
