import type { WordEntry } from '../../domain/content/types'
import type { LocaleCode } from '../../domain/game/types'

export const cinema: Partial<Record<LocaleCode, WordEntry[]>> = {
  ca: [
    { word: 'Titanic', hints: ['Vaixell', 'Iceberg', 'Romàntica'] },
    { word: 'Matrix', hints: ['Realitat virtual', 'Pastilla', 'Neo'] },
    { word: 'Avatar', hints: ['Planeta blau', 'Pandora', 'Na’vi'] },
    { word: 'Gladiator', hints: ['Arena romana', 'Espasa', 'Venjança'] },
    { word: 'Shrek', hints: ['Verd', 'Pantà', 'Conte de fades'] },
    { word: 'Toy Story', hints: ['Joguines', 'Pixar', 'Habitació d’un nen'] },
    { word: 'Frozen', hints: ['Neu', 'Germanes', 'Princeses'] },
    { word: 'Harry Potter', hints: ['Màgia', 'Escola', 'Ulleres'] },
    { word: 'El rei lleó', hints: ['Sabana', 'Àfrica', 'Corona'] },
    { word: 'Frankenstein', hints: ['Monstre', 'Llamps', 'Doctor'] },
    { word: 'Terror', hints: ['Por', 'Sang', 'Ensurts'] },
    { word: 'Comèdia', hints: ['Riure', 'Acudits', 'Diversió'] },
    { word: 'Drama', hints: ['Llàgrimes', 'Emoció', 'Tristesa'] },
    { word: 'Acció', hints: ['Persecucions', 'Explosions', 'Lluites'] },
    { word: 'Ciència-ficció', hints: ['Futur', 'Naus', 'Robots'] },
    { word: 'Western', hints: ['Cowboys', 'Oest', 'Pistoles'] },
    { word: 'Cinema de suspens', hints: ['Tensió', 'Intriga', 'Misteri'] },
    { word: 'Animació', hints: ['Dibuixos', 'Pixar', 'Infantil'] },
    { word: 'Documental', hints: ['Realitat', 'Natura', 'Veritat'] },
    { word: 'Director', hints: ['Rodatge', 'Càmera', 'Ordres'] },
    { word: 'Guió', hints: ['Text', 'Diàlegs', 'Història'] },
    { word: 'Actor', hints: ['Interpreta', 'Paper', 'Escena'] },
    { word: 'Productor', hints: ['Diners', 'Finançament', 'Projecte'] },
    { word: 'Taquilla', hints: ['Entrades', 'Recaptació', 'Cua'] },
    { word: 'Estrena', hints: ['Primer dia', 'Catifa vermella', 'Novetat'] },
    { word: 'Oscar', hints: ['Premi', 'Estatueta', 'Hollywood'] },
    { word: 'Banda sonora', hints: ['Música', 'Cançons', 'Melodia'] },
    { word: 'Spielberg', hints: ['Tauró', 'Director', 'Dinosaures'] },
    { word: 'Càmera', hints: ['Imatge', 'Filmar', 'Objectiu'] },
    { word: 'Pantalla', hints: ['Projecció', 'Sala', 'Gran'] },
  ],
  en: [
    { word: 'Titanic', hints: ['Ship', 'Iceberg', 'Romance'] },
    { word: 'Matrix', hints: ['Virtual reality', 'Sunglasses', 'Slow motion'] },
    { word: 'Avatar', hints: ['Blue skin', 'Aliens', '3D'] },
    { word: 'Gladiator', hints: ['Roman arena', 'Sword', 'Revenge'] },
    { word: 'Jaws', hints: ['Shark', 'Beach', 'Bite'] },
    { word: 'Shrek', hints: ['Green', 'Swamp', 'Fairy tale'] },
    { word: 'Inception', hints: ['Dreams', 'Heist', 'Layers'] },
    { word: 'Frankenstein', hints: ['Monster', 'Lightning', 'Doctor'] },
    { word: 'Toy Story', hints: ['Toys', 'Pixar', 'Cowboy'] },
    { word: 'Harry Potter', hints: ['Wizard', 'Glasses', 'Owls'] },
    { word: 'Horror', hints: ['Fear', 'Blood', 'Jump scares'] },
    { word: 'Comedy', hints: ['Laughter', 'Jokes', 'Fun'] },
    { word: 'Drama', hints: ['Tears', 'Emotion', 'Serious'] },
    { word: 'Action', hints: ['Chases', 'Explosions', 'Fights'] },
    { word: 'Sci-fi', hints: ['Future', 'Spaceships', 'Robots'] },
    { word: 'Western', hints: ['Cowboys', 'Wild west', 'Guns'] },
    { word: 'Thriller', hints: ['Tension', 'Suspense', 'Twist'] },
    { word: 'Animation', hints: ['Cartoons', 'Pixar', 'Drawn'] },
    { word: 'Documentary', hints: ['Real life', 'Nature', 'Truth'] },
    { word: 'Director', hints: ['Shooting', 'Camera', 'In charge'] },
    { word: 'Script', hints: ['Written lines', 'Dialogue', 'Story'] },
    { word: 'Actor', hints: ['Performs', 'Role', 'Scene'] },
    { word: 'Producer', hints: ['Funding', 'Money', 'Project'] },
    { word: 'Box office', hints: ['Tickets', 'Earnings', 'Queue'] },
    { word: 'Premiere', hints: ['First night', 'Red carpet', 'Launch'] },
    { word: 'Oscar', hints: ['Award', 'Statuette', 'Hollywood'] },
    { word: 'Soundtrack', hints: ['Music', 'Songs', 'Score'] },
    { word: 'Spielberg', hints: ['Famous director', 'Shark', 'Dinosaurs'] },
    { word: 'Camera', hints: ['Image', 'Filming', 'Lens'] },
    { word: 'Screen', hints: ['Projection', 'Theatre', 'Big'] },
  ],
  es: [
    { word: 'Titanic', hints: ['Barco', 'Iceberg', 'Romántica'] },
    { word: 'Matrix', hints: ['Realidad virtual', 'Pastilla roja', 'Gafas negras'] },
    { word: 'Avatar', hints: ['Planeta lejano', 'Piel azul', 'Alienígenas'] },
    { word: 'Gladiator', hints: ['Arena romana', 'Espada', 'Venganza'] },
    { word: 'Shrek', hints: ['Ogro', 'Verde', 'Pantano'] },
    { word: 'Frozen', hints: ['Hermanas', 'Hielo', 'Princesa'] },
    { word: 'Tadeo Jones', hints: ['Arqueólogo', 'Momia', 'Sombrero'] },
    { word: 'Campeones', hints: ['Baloncesto', 'Equipo', 'Entrenador'] },
    { word: 'La lengua de las mariposas', hints: ['Maestro', 'Escuela', 'República'] },
    { word: 'Frankenstein', hints: ['Monstruo', 'Rayos', 'Doctor'] },
    { word: 'Terror', hints: ['Miedo', 'Sangre', 'Sustos'] },
    { word: 'Comedia', hints: ['Risa', 'Chistes', 'Diversión'] },
    { word: 'Drama', hints: ['Lágrimas', 'Emoción', 'Tristeza'] },
    { word: 'Acción', hints: ['Persecuciones', 'Explosiones', 'Peleas'] },
    { word: 'Ciencia ficción', hints: ['Futuro', 'Naves', 'Robots'] },
    { word: 'Western', hints: ['Vaqueros', 'Oeste', 'Pistolas'] },
    { word: 'Suspense', hints: ['Tensión', 'Intriga', 'Misterio'] },
    { word: 'Animación', hints: ['Dibujos', 'Pixar', 'Infantil'] },
    { word: 'Documental', hints: ['Realidad', 'Naturaleza', 'Verdad'] },
    { word: 'Director', hints: ['Rodaje', 'Cámara', 'Manda'] },
    { word: 'Guion', hints: ['Texto', 'Diálogos', 'Historia'] },
    { word: 'Actor', hints: ['Interpreta', 'Papel', 'Escena'] },
    { word: 'Productor', hints: ['Dinero', 'Financia', 'Proyecto'] },
    { word: 'Taquilla', hints: ['Entradas', 'Recaudación', 'Cola'] },
    { word: 'Estreno', hints: ['Primer día', 'Alfombra roja', 'Novedad'] },
    { word: 'Óscar', hints: ['Premio', 'Estatuilla', 'Hollywood'] },
    { word: 'Banda sonora', hints: ['Música', 'Canciones', 'Melodía'] },
    { word: 'Spielberg', hints: ['Director', 'Estadounidense', 'Aventuras'] },
    { word: 'Cámara', hints: ['Imagen', 'Filmar', 'Objetivo'] },
    { word: 'Pantalla', hints: ['Proyección', 'Sala', 'Grande'] },
  ],
  eu: [
    { word: 'Titanic', hints: ['Itsasontzia', 'Hondoratzea', 'Maitasuna'] },
    { word: 'Matrix', hints: ['Errealitate birtuala', 'Pilula', 'Eguzkitako beltzak'] },
    { word: 'Avatar', hints: ['Planeta urdina', 'Estralurtarrak', '3D'] },
    { word: 'Gladiator', hints: ['Erromatar anfiteatroa', 'Ezpata', 'Mendekua'] },
    { word: 'Shrek', hints: ['Berdea', 'Zingira', 'Maitagarrien ipuina'] },
    { word: 'Toy Story', hints: ['Jostailuak', 'Pixar', 'Behizaina'] },
    { word: 'Frozen', hints: ['Izotza', 'Ahizpak', 'Elurra'] },
    { word: 'Frankenstein', hints: ['Munstroa', 'Tximistak', 'Doktorea'] },
    { word: 'Harry Potter', hints: ['Aztia', 'Betaurrekoak', 'Hontzak'] },
    { word: 'Coco', hints: ['Mexiko', 'Hildakoen eguna', 'Gitarra'] },
    { word: 'Beldurrezko filma', hints: ['Mamuak', 'Odola', 'Sustoak'] },
    { word: 'Komedia', hints: ['Barrea', 'Txisteak', 'Dibertsioa'] },
    { word: 'Drama', hints: ['Malkoak', 'Emozioa', 'Tristura'] },
    { word: 'Ekintza', hints: ['Jazarpenak', 'Leherketak', 'Borrokak'] },
    { word: 'Zientzia-fikzioa', hints: ['Etorkizuna', 'Ontziak', 'Robotak'] },
    { word: 'Westerna', hints: ['Behizainak', 'Mendebaldea', 'Pistolak'] },
    { word: 'Suspentsea', hints: ['Tentsioa', 'Intriga', 'Misterioa'] },
    { word: 'Animazioa', hints: ['Marrazkiak', 'Pixar', 'Haurrentzat'] },
    { word: 'Dokumentala', hints: ['Errealitatea', 'Natura', 'Egia'] },
    { word: 'Zinema zuzendaria', hints: ['Filmaketa', 'Kamera', 'Nagusia'] },
    { word: 'Gidoia', hints: ['Testua', 'Elkarrizketak', 'Istorioa'] },
    { word: 'Aktorea', hints: ['Antzezten du', 'Papera', 'Eszena'] },
    { word: 'Ekoizlea', hints: ['Dirua', 'Finantzaketa', 'Proiektua'] },
    { word: 'Leihatila', hints: ['Sarrerak', 'Diru bilketa', 'Ilara'] },
    { word: 'Estreinaldia', hints: ['Lehen eguna', 'Alfonbra gorria', 'Berria'] },
    { word: 'Oscar', hints: ['Saria', 'Estatuatxoa', 'Hollywood'] },
    { word: 'Soinu-banda', hints: ['Musika', 'Abestiak', 'Melodia'] },
    { word: 'Spielberg', hints: ['Marrazoa', 'Zuzendaria', 'Dinosauroak'] },
    { word: 'Kamera', hints: ['Irudia', 'Filmatzea', 'Objektiboa'] },
    { word: 'Pantaila', hints: ['Proiekzioa', 'Aretoa', 'Handia'] },
  ],
  gl: [
    { word: 'Titanic', hints: ['Barco', 'Iceberg', 'Romántica'] },
    { word: 'Matrix', hints: ['Realidade virtual', 'Pílula vermella', 'Lentes escuras'] },
    { word: 'Avatar', hints: ['Planeta afastado', 'Pel azul', 'Alieníxenas'] },
    { word: 'Gladiator', hints: ['Area romana', 'Espada', 'Vinganza'] },
    { word: 'A lingua das bolboretas', hints: ['Mestre', 'Escola', 'República'] },
    { word: 'Shrek', hints: ['Ogro', 'Verde', 'Pantano'] },
    { word: 'Frozen', hints: ['Irmás', 'Xeo', 'Princesa'] },
    { word: 'Toy Story', hints: ['Xoguetes', 'Vaqueiro', 'Astronauta'] },
    { word: 'Frankenstein', hints: ['Monstro', 'Raios', 'Doutor'] },
    { word: 'Harry Potter', hints: ['Mago', 'Variña', 'Cicatriz'] },
    { word: 'Terror', hints: ['Medo', 'Sangue', 'Sustos'] },
    { word: 'Comedia', hints: ['Risa', 'Chistes', 'Diversión'] },
    { word: 'Drama', hints: ['Lágrimas', 'Emoción', 'Tristeza'] },
    { word: 'Acción', hints: ['Persecucións', 'Explosións', 'Loitas'] },
    { word: 'Ciencia ficción', hints: ['Futuro', 'Naves', 'Robots'] },
    { word: 'Western', hints: ['Vaqueiros', 'Oeste', 'Pistolas'] },
    { word: 'Suspense', hints: ['Tensión', 'Intriga', 'Misterio'] },
    { word: 'Animación', hints: ['Debuxos', 'Pixar', 'Infantil'] },
    { word: 'Documental', hints: ['Realidade', 'Natureza', 'Verdade'] },
    { word: 'Director', hints: ['Rodaxe', 'Cámara', 'Manda'] },
    { word: 'Guión', hints: ['Texto', 'Diálogos', 'Historia'] },
    { word: 'Actor', hints: ['Interpreta', 'Papel', 'Escena'] },
    { word: 'Produtor', hints: ['Cartos', 'Financia', 'Proxecto'] },
    { word: 'Billeteira', hints: ['Entradas', 'Recadación', 'Cola'] },
    { word: 'Estrea', hints: ['Primeiro día', 'Alfombra vermella', 'Novidade'] },
    { word: 'Óscar', hints: ['Premio', 'Estatuíña', 'Hollywood'] },
    { word: 'Banda sonora', hints: ['Música', 'Cancións', 'Melodía'] },
    { word: 'Spielberg', hints: ['Director', 'Estadounidense', 'Aventuras'] },
    { word: 'Cámara', hints: ['Imaxe', 'Filmar', 'Obxectivo'] },
    { word: 'Pantalla', hints: ['Proxección', 'Sala', 'Grande'] },
  ],
  va: [
    { word: 'Titanic', hints: ['Vaixell', 'Iceberg', 'Romàntica'] },
    { word: 'Matrix', hints: ['Realitat virtual', 'Pastilla', 'Neo'] },
    { word: 'Avatar', hints: ['Planeta blau', 'Pandora', 'Na’vi'] },
    { word: 'Gladiator', hints: ['Arena romana', 'Espasa', 'Venjança'] },
    { word: 'Shrek', hints: ['Verd', 'Pantà', 'Conte de fades'] },
    { word: 'Harry Potter', hints: ['Màgia', 'Escola', 'Ulleres'] },
    { word: 'Toy Story', hints: ['Joguines', 'Pixar', 'Habitació d’un xiquet'] },
    { word: 'Frozen', hints: ['Neu', 'Germanes', 'Princeses'] },
    { word: 'Frankenstein', hints: ['Monstre', 'Llamps', 'Doctor'] },
    { word: 'El rei lleó', hints: ['Sabana', 'Àfrica', 'Corona'] },
    { word: 'Terror', hints: ['Por', 'Sang', 'Ensurts'] },
    { word: 'Comèdia', hints: ['Riure', 'Acudits', 'Diversió'] },
    { word: 'Drama', hints: ['Llàgrimes', 'Emoció', 'Tristesa'] },
    { word: 'Acció', hints: ['Persecucions', 'Explosions', 'Lluites'] },
    { word: 'Ciència-ficció', hints: ['Futur', 'Naus', 'Robots'] },
    { word: 'Western', hints: ['Cowboys', 'Oest', 'Pistoles'] },
    { word: 'Cinema de suspens', hints: ['Tensió', 'Intriga', 'Misteri'] },
    { word: 'Animació', hints: ['Dibuixos', 'Pixar', 'Infantil'] },
    { word: 'Documental', hints: ['Realitat', 'Natura', 'Veritat'] },
    { word: 'Director', hints: ['Rodatge', 'Càmera', 'Ordres'] },
    { word: 'Guió', hints: ['Text', 'Diàlegs', 'Història'] },
    { word: 'Actor', hints: ['Interpreta', 'Paper', 'Escena'] },
    { word: 'Productor', hints: ['Diners', 'Finançament', 'Projecte'] },
    { word: 'Taquilla', hints: ['Entrades', 'Recaptació', 'Cua'] },
    { word: 'Estrena', hints: ['Primer dia', 'Catifa vermella', 'Novetat'] },
    { word: 'Oscar', hints: ['Premi', 'Estatueta', 'Hollywood'] },
    { word: 'Banda sonora', hints: ['Música', 'Cançons', 'Melodia'] },
    { word: 'Spielberg', hints: ['Tauró', 'Director', 'Dinosaures'] },
    { word: 'Càmera', hints: ['Imatge', 'Filmar', 'Objectiu'] },
    { word: 'Pantalla', hints: ['Projecció', 'Sala', 'Gran'] },
  ],
}
