import type { WordEntry } from '../../domain/content/types'
import type { LocaleCode } from '../../domain/game/types'

export const cinema: Partial<Record<LocaleCode, WordEntry[]>> = {
  ca: [
    { word: 'Titanic', hint: 'Vaixell' },
    { word: 'Matrix', hint: 'Realitat virtual' },
    { word: 'Avatar', hint: 'Planeta blau' },
    { word: 'Gladiator', hint: 'Arena romana' },
    { word: 'El laberint del faune', hint: 'Postguerra' },
    { word: 'Loreak', hint: 'Flors' },
    { word: 'A lingua das bolboretas', hint: 'Mestre' },
    { word: 'Mar adentro', hint: 'Cadira de rodes' },
    { word: 'Pa negre', hint: 'Catalana' },
    { word: 'Frankenstein', hint: 'Monstre' },
    { word: 'Terror', hint: 'Por' },
    { word: 'Comèdia', hint: 'Riure' },
    { word: 'Drama', hint: 'Llàgrimes' },
    { word: 'Acció', hint: 'Persecucions' },
    { word: 'Ciència-ficció', hint: 'Futur' },
    { word: 'Western', hint: 'Cowboys' },
    { word: 'Suspens', hint: 'Tensió' },
    { word: 'Animació', hint: 'Dibuixos' },
    { word: 'Documental', hint: 'Realitat' },
    { word: 'Director', hint: 'Rodatge' },
    { word: 'Guió', hint: 'Text' },
    { word: 'Actor', hint: 'Interpreta' },
    { word: 'Productor', hint: 'Diners' },
    { word: 'Taquilla', hint: 'Entrades' },
    { word: 'Estrena', hint: 'Primer dia' },
    { word: 'Oscar', hint: 'Premi' },
    { word: 'Banda sonora', hint: 'Música' },
    { word: 'Espielberg', hint: 'Tauró' },
    { word: 'Càmera', hint: 'Imatge' },
    { word: 'Pantalla', hint: 'Projecció' },
  ],
  en: [
    { word: 'Titanic', hint: 'Ship' },
    { word: 'Matrix', hint: 'Virtual reality' },
    { word: 'Avatar', hint: 'Blue planet' },
    { word: 'Gladiator', hint: 'Roman arena' },
    { word: 'Jaws', hint: 'Shark' },
    { word: 'Casablanca', hint: 'Morocco classic' },
    { word: 'Inception', hint: 'Dreams' },
    { word: 'Frankenstein', hint: 'Monster' },
    { word: 'Pan’s Labyrinth', hint: 'Postwar fairy tale' },
    { word: 'The Godfather', hint: 'Mafia family' },
    { word: 'Horror', hint: 'Fear' },
    { word: 'Comedy', hint: 'Laughter' },
    { word: 'Drama', hint: 'Tears' },
    { word: 'Action', hint: 'Chases' },
    { word: 'Sci-fi', hint: 'Future' },
    { word: 'Western', hint: 'Cowboys' },
    { word: 'Thriller', hint: 'Tension' },
    { word: 'Animation', hint: 'Cartoons' },
    { word: 'Documentary', hint: 'Real life' },
    { word: 'Director', hint: 'Shooting' },
    { word: 'Script', hint: 'Written lines' },
    { word: 'Actor', hint: 'Performs' },
    { word: 'Producer', hint: 'Funding' },
    { word: 'Box office', hint: 'Tickets' },
    { word: 'Premiere', hint: 'First night' },
    { word: 'Oscar', hint: 'Award' },
    { word: 'Soundtrack', hint: 'Music' },
    { word: 'Spielberg', hint: 'Famous director' },
    { word: 'Camera', hint: 'Image' },
    { word: 'Screen', hint: 'Projection' },
  ],
  es: [
    { word: 'Titanic', hint: 'Barco' },
    { word: 'Matrix', hint: 'Realidad virtual' },
    { word: 'Avatar', hint: 'Planeta azul' },
    { word: 'Gladiator', hint: 'Arena romana' },
    { word: 'El laberinto del fauno', hint: 'Posguerra' },
    { word: 'Mar adentro', hint: 'Silla de ruedas' },
    { word: 'Volver', hint: 'Almodóvar' },
    { word: 'Loreak', hint: 'Flores' },
    { word: 'La lengua de las mariposas', hint: 'Maestro' },
    { word: 'Frankenstein', hint: 'Monstruo' },
    { word: 'Terror', hint: 'Miedo' },
    { word: 'Comedia', hint: 'Risa' },
    { word: 'Drama', hint: 'Lágrimas' },
    { word: 'Acción', hint: 'Persecuciones' },
    { word: 'Ciencia ficción', hint: 'Futuro' },
    { word: 'Western', hint: 'Vaqueros' },
    { word: 'Suspense', hint: 'Tensión' },
    { word: 'Animación', hint: 'Dibujos' },
    { word: 'Documental', hint: 'Realidad' },
    { word: 'Director', hint: 'Rodaje' },
    { word: 'Guión', hint: 'Texto' },
    { word: 'Actor', hint: 'Interpreta' },
    { word: 'Productor', hint: 'Dinero' },
    { word: 'Taquilla', hint: 'Entradas' },
    { word: 'Estreno', hint: 'Primer día' },
    { word: 'Oscar', hint: 'Premio' },
    { word: 'Banda sonora', hint: 'Música' },
    { word: 'Spielberg', hint: 'Tiburón' },
    { word: 'Cámara', hint: 'Imagen' },
    { word: 'Pantalla', hint: 'Proyección' },
  ],
  eu: [
    { word: 'Titanic', hint: 'Itsasontzia' },
    { word: 'Matrix', hint: 'Errealitate birtuala' },
    { word: 'Avatar', hint: 'Planeta urdina' },
    { word: 'Gladiator', hint: 'Erromatar arena' },
    { word: 'Loreak', hint: 'Lili' },
    { word: 'Handia', hint: 'Erraldoia' },
    { word: 'Ama Lur', hint: 'Euskal lurra' },
    { word: 'Frankenstein', hint: 'Munstroa' },
    { word: 'Faunoaren labirintoa', hint: 'Gerraostea' },
    { word: 'Ito', hint: 'Itsaso barrena' },
    { word: 'Beldurra', hint: 'Izua' },
    { word: 'Komedia', hint: 'Barrea' },
    { word: 'Drama', hint: 'Malkoak' },
    { word: 'Ekintza', hint: 'Jazarpenak' },
    { word: 'Zientzia fikzioa', hint: 'Etorkizuna' },
    { word: 'Western', hint: 'Cowboyak' },
    { word: 'Suspentsea', hint: 'Tentsioa' },
    { word: 'Animazioa', hint: 'Marrazkiak' },
    { word: 'Dokumentala', hint: 'Errealitatea' },
    { word: 'Zuzendaria', hint: 'Filmaketa' },
    { word: 'Gidoia', hint: 'Testua' },
    { word: 'Aktorea', hint: 'Antzezten du' },
    { word: 'Ekoizlea', hint: 'Dirua' },
    { word: 'Leihatila', hint: 'Sarrerak' },
    { word: 'Estreinaldia', hint: 'Lehen eguna' },
    { word: 'Oscar', hint: 'Saria' },
    { word: 'Soinu banda', hint: 'Musika' },
    { word: 'Spielberg', hint: 'Marrazoa' },
    { word: 'Kamera', hint: 'Irudia' },
    { word: 'Pantaila', hint: 'Proiekzioa' },
  ],
  gl: [
    { word: 'Titanic', hint: 'Barco' },
    { word: 'Matrix', hint: 'Realidade virtual' },
    { word: 'Avatar', hint: 'Planeta azul' },
    { word: 'Gladiator', hint: 'Area romana' },
    { word: 'A lingua das bolboretas', hint: 'Mestre' },
    { word: 'Os luns ao sol', hint: 'Parados' },
    { word: 'Sempre Xonxa', hint: 'Galega clásica' },
    { word: 'O lapis do carpinteiro', hint: 'Guerra civil' },
    { word: 'Frankenstein', hint: 'Monstro' },
    { word: 'O labirinto do fauno', hint: 'Posguerra' },
    { word: 'Terror', hint: 'Medo' },
    { word: 'Comedia', hint: 'Risa' },
    { word: 'Drama', hint: 'Lágrimas' },
    { word: 'Acción', hint: 'Persecucións' },
    { word: 'Ciencia ficción', hint: 'Futuro' },
    { word: 'Western', hint: 'Vaqueiros' },
    { word: 'Suspense', hint: 'Tensión' },
    { word: 'Animación', hint: 'Debuxos' },
    { word: 'Documental', hint: 'Realidade' },
    { word: 'Director', hint: 'Rodaxe' },
    { word: 'Guión', hint: 'Texto' },
    { word: 'Actor', hint: 'Interpreta' },
    { word: 'Produtor', hint: 'Cartos' },
    { word: 'Despacho de billetes', hint: 'Entradas' },
    { word: 'Estrea', hint: 'Primeiro día' },
    { word: 'Oscar', hint: 'Premio' },
    { word: 'Banda sonora', hint: 'Música' },
    { word: 'Spielberg', hint: 'Tiburón' },
    { word: 'Cámara', hint: 'Imaxe' },
    { word: 'Pantalla', hint: 'Proxección' },
  ],
  va: [
    { word: 'Titanic', hint: 'Vaixell' },
    { word: 'Matrix', hint: 'Realitat virtual' },
    { word: 'Avatar', hint: 'Planeta blau' },
    { word: 'Gladiator', hint: 'Arena romana' },
    { word: 'El laberint del faune', hint: 'Postguerra' },
    { word: 'Mar adentro', hint: 'Cadira de rodes' },
    { word: 'Loreak', hint: 'Flors' },
    { word: 'A lingua das bolboretas', hint: 'Mestre' },
    { word: 'Frankenstein', hint: 'Monstre' },
    { word: 'Pa negre', hint: 'Catalana' },
    { word: 'Terror', hint: 'Por' },
    { word: 'Comèdia', hint: 'Riure' },
    { word: 'Drama', hint: 'Llàgrimes' },
    { word: 'Acció', hint: 'Persecucions' },
    { word: 'Ciència-ficció', hint: 'Futur' },
    { word: 'Western', hint: 'Cowboys' },
    { word: 'Suspens', hint: 'Tensió' },
    { word: 'Animació', hint: 'Dibuixos' },
    { word: 'Documental', hint: 'Realitat' },
    { word: 'Director', hint: 'Rodatge' },
    { word: 'Guió', hint: 'Text' },
    { word: 'Actor', hint: 'Interpreta' },
    { word: 'Productor', hint: 'Diners' },
    { word: 'Taquilla', hint: 'Entrades' },
    { word: 'Estrena', hint: 'Primer dia' },
    { word: 'Oscar', hint: 'Premi' },
    { word: 'Banda sonora', hint: 'Música' },
    { word: 'Spielberg', hint: 'Tauró' },
    { word: 'Càmera', hint: 'Imatge' },
    { word: 'Pantalla', hint: 'Projecció' },
  ],
}
