import type { WordEntry } from '../../domain/content/types'
import type { LocaleCode } from '../../domain/game/types'

export const food: Partial<Record<LocaleCode, WordEntry[]>> = {
  ca: [
    { word: 'Paella', hints: ['Arròs', 'València', 'Paellera'] },
    { word: 'Pop', hints: ['Mar', 'Tentacles', 'A la gallega'] },
    { word: 'Xocolata', hints: ['Dolç', 'Cacau', 'Marró'] },
    { word: 'Truita', hints: ['Ous', 'Patata', 'Paella'] },
    { word: 'Gaspatxo', hints: ['Fred', 'Tomàquet', 'Estiu'] },
    { word: 'Formatge', hints: ['Llet', 'Curat', 'Ratllat'] },
    { word: 'Sushi', hints: ['Japó', 'Arròs', 'Peix cru'] },
    { word: 'Gelat', hints: ['Postres', 'Fred', 'Cucurutxo'] },
    { word: 'Llenties', hints: ['Llegum', 'Guisat', 'Cullera'] },
    { word: 'Croqueta', hints: ['Fregit', 'Beixamel', 'Tapa'] },
    { word: 'Pa amb tomàquet', hints: ['Esmorzar', 'Oli', 'Català'] },
    { word: 'Botifarra', hints: ['Brasa', 'Porc', 'Mongetes'] },
    { word: 'Calçots', hints: ['Calçotada', 'Salsa', 'Brasa'] },
    { word: 'Fideuà', hints: ['Fideus', 'Marisc', 'Paellera'] },
    { word: 'Crema catalana', hints: ['Postres', 'Cremada', 'Sucre'] },
    { word: 'Escudella', hints: ['Hivern', 'Brou', 'Nadal'] },
    { word: 'Pizza', hints: ['Itàlia', 'Forn', 'Rodona'] },
    { word: 'Hamburguesa', hints: ['Carn', 'Pa', 'Ràpid'] },
    { word: 'Vi', hints: ['Beguda', 'Raïm', 'Copa'] },
    { word: 'Cervesa', hints: ['Bar', 'Espuma', 'Freda'] },
    { word: 'Pernil', hints: ['Tapa', 'Porc', 'Curat'] },
    { word: 'Macarrons', hints: ['Pasta', 'Tomàquet', 'Forn'] },
    { word: 'Amanida', hints: ['Verd', 'Enciam', 'Fresca'] },
    { word: 'Sopa', hints: ['Calenta', 'Brou', 'Cullera'] },
    { word: 'Cafè', hints: ['Matí', 'Negre', 'Tassa'] },
    { word: 'Pollastre', hints: ['Forn', 'Au', 'Carn'] },
    { word: 'Maduixes', hints: ['Fruita', 'Vermell', 'Primavera'] },
    { word: 'Olives', hints: ['Aperitiu', 'Adobades', 'Verdes'] },
    { word: 'Allioli', hints: ['Salsa', 'Picada', 'Blanc'] },
    { word: 'Coca', hints: ['Festa', 'Forn', 'Sant Joan'] },
  ],
  en: [
    { word: 'Paella', hints: ['Rice', 'Spain', 'Pan'] },
    { word: 'Octopus', hints: ['Sea', 'Tentacles', 'Grilled'] },
    { word: 'Chocolate', hints: ['Sweet', 'Cocoa', 'Brown'] },
    { word: 'Omelette', hints: ['Eggs', 'Pan', 'Folded'] },
    { word: 'Gazpacho', hints: ['Cold', 'Tomato', 'Summer'] },
    { word: 'Cheese', hints: ['Milk', 'Yellow', 'Grated'] },
    { word: 'Sushi', hints: ['Japan', 'Rice', 'Raw fish'] },
    { word: 'Ice cream', hints: ['Dessert', 'Cold', 'Cone'] },
    { word: 'Lentils', hints: ['Legume', 'Stew', 'Tiny'] },
    { word: 'Croquette', hints: ['Fried', 'Crispy', 'Bite'] },
    { word: 'Pizza', hints: ['Italy', 'Oven', 'Round'] },
    { word: 'Burger', hints: ['Beef', 'Bun', 'Fast food'] },
    { word: 'Pasta', hints: ['Italian', 'Sauce', 'Boiled'] },
    { word: 'Salad', hints: ['Greens', 'Lettuce', 'Fresh'] },
    { word: 'Soup', hints: ['Warm', 'Bowl', 'Spoon'] },
    { word: 'Coffee', hints: ['Morning', 'Black', 'Mug'] },
    { word: 'Wine', hints: ['Drink', 'Grapes', 'Glass'] },
    { word: 'Beer', hints: ['Pub', 'Foam', 'Cold'] },
    { word: 'Bread', hints: ['Bakery', 'Loaf', 'Flour'] },
    { word: 'Chicken', hints: ['Poultry', 'Roast', 'Wings'] },
    { word: 'Strawberry', hints: ['Fruit', 'Red', 'Spring'] },
    { word: 'Olives', hints: ['Snack', 'Oil', 'Green'] },
    { word: 'Pancakes', hints: ['Breakfast', 'Syrup', 'Stack'] },
    { word: 'Sandwich', hints: ['Lunch', 'Bread', 'Filling'] },
    { word: 'Sausage', hints: ['Grill', 'Pork', 'Link'] },
    { word: 'Tacos', hints: ['Mexico', 'Tortilla', 'Spicy'] },
    { word: 'Curry', hints: ['India', 'Spicy', 'Sauce'] },
    { word: 'Honey', hints: ['Bees', 'Sweet', 'Golden'] },
    { word: 'Garlic', hints: ['Pungent', 'Clove', 'White'] },
    { word: 'Rice', hints: ['Grain', 'White', 'Asia'] },
  ],
  es: [
    { word: 'Paella', hints: ['Arroz', 'Valencia', 'Sartén'] },
    { word: 'Pulpo', hints: ['Mar', 'Tentáculos', 'Gallega'] },
    { word: 'Chocolate', hints: ['Dulce', 'Cacao', 'Marrón'] },
    { word: 'Tortilla', hints: ['Huevos', 'Patata', 'Sartén'] },
    { word: 'Gazpacho', hints: ['Frío', 'Tomate', 'Verano'] },
    { word: 'Queso', hints: ['Leche', 'Curado', 'Rallado'] },
    { word: 'Sushi', hints: ['Japón', 'Arroz', 'Pescado crudo'] },
    { word: 'Helado', hints: ['Postre', 'Frío', 'Cucurucho'] },
    { word: 'Lentejas', hints: ['Legumbre', 'Guiso', 'Cuchara'] },
    { word: 'Croqueta', hints: ['Frito', 'Bechamel', 'Tapa'] },
    { word: 'Jamón', hints: ['Tapa', 'Cerdo', 'Curado'] },
    { word: 'Cocido', hints: ['Invierno', 'Garbanzos', 'Caldo'] },
    { word: 'Fabada', hints: ['Asturias', 'Alubias', 'Chorizo'] },
    { word: 'Salmorejo', hints: ['Córdoba', 'Tomate', 'Frío'] },
    { word: 'Churros', hints: ['Desayuno', 'Frito', 'Azúcar'] },
    { word: 'Pizza', hints: ['Italia', 'Horno', 'Redonda'] },
    { word: 'Hamburguesa', hints: ['Carne', 'Pan', 'Rápida'] },
    { word: 'Macarrones', hints: ['Pasta', 'Tomate', 'Horno'] },
    { word: 'Ensalada', hints: ['Verde', 'Lechuga', 'Fresca'] },
    { word: 'Sopa', hints: ['Caliente', 'Caldo', 'Cuchara'] },
    { word: 'Café', hints: ['Mañana', 'Negro', 'Taza'] },
    { word: 'Vino', hints: ['Bebida', 'Uva', 'Copa'] },
    { word: 'Cerveza', hints: ['Bar', 'Espuma', 'Fría'] },
    { word: 'Pollo', hints: ['Horno', 'Ave', 'Carne'] },
    { word: 'Fresas', hints: ['Fruta', 'Rojo', 'Primavera'] },
    { word: 'Aceitunas', hints: ['Aperitivo', 'Aceite', 'Verdes'] },
    { word: 'Gambas', hints: ['Marisco', 'Mar', 'Plancha'] },
    { word: 'Flan', hints: ['Caramelo', 'Postre', 'Huevo'] },
    { word: 'Migas', hints: ['Pastor', 'Pan', 'Sartén'] },
    { word: 'Pan', hints: ['Horno', 'Harina', 'Barra'] },
  ],
  eu: [
    { word: 'Marmitako', hints: ['Hegaluzea', 'Patata', 'Itsasoa'] },
    { word: 'Pintxoa', hints: ['Barra', 'Taberna', 'Txikia'] },
    { word: 'Bakailaoa', hints: ['Arraina', 'Gatza', 'Pil-pil'] },
    { word: 'Txuleta', hints: ['Haragia', 'Behia', 'Parrila'] },
    { word: 'Talo', hints: ['Artoa', 'Zapata', 'Azoka'] },
    { word: 'Idiazabal', hints: ['Gazta', 'Ardia', 'Esnea'] },
    { word: 'Txakoli', hints: ['Ardoa', 'Mahatsa', 'Zuria'] },
    { word: 'Sagardo', hints: ['Sagarra', 'Edaria', 'Tolosa'] },
    { word: 'Paella', hints: ['Arroza', 'Valentzia', 'Zartagina'] },
    { word: 'Olagarroa', hints: ['Itsasoa', 'Garroak', 'Egosia'] },
    { word: 'Txokolatea', hints: ['Goxoa', 'Kakaoa', 'Marroia'] },
    { word: 'Tortilla', hints: ['Arrautzak', 'Patata', 'Zartagina'] },
    { word: 'Gazpatxoa', hints: ['Hotza', 'Tomatea', 'Uda'] },
    { word: 'Sushia', hints: ['Japonia', 'Arroza', 'Arrain gordina'] },
    { word: 'Izozkia', hints: ['Postrea', 'Hotza', 'Baratxoa'] },
    { word: 'Dilistak', hints: ['Lekaleak', 'Eltzekoa', 'Koilara'] },
    { word: 'Kroketa', hints: ['Frijitua', 'Bexamela', 'Txikia'] },
    { word: 'Pizza', hints: ['Italia', 'Labea', 'Biribila'] },
    { word: 'Hanburgesa', hints: ['Okela', 'Ogia', 'Azkarra'] },
    { word: 'Entsalada', hints: ['Berdea', 'Uraza', 'Freskoa'] },
    { word: 'Zopa', hints: ['Beroa', 'Salda', 'Koilara'] },
    { word: 'Kafea', hints: ['Goiza', 'Beltza', 'Katilua'] },
    { word: 'Garagardoa', hints: ['Taberna', 'Aparra', 'Hotza'] },
    { word: 'Oilaskoa', hints: ['Labea', 'Hegaztia', 'Okela'] },
    { word: 'Marrubiak', hints: ['Fruta', 'Gorria', 'Udaberria'] },
    { word: 'Olibak', hints: ['Aperitiboa', 'Olioa', 'Berdeak'] },
    { word: 'Ogia', hints: ['Okindegia', 'Irina', 'Zuria'] },
    { word: 'Eztia', hints: ['Erleak', 'Goxoa', 'Horia'] },
    { word: 'Baratxuria', hints: ['Mina', 'Atala', 'Zuria'] },
    { word: 'Arroza', hints: ['Alea', 'Zuria', 'Asia'] },
  ],
  gl: [
    { word: 'Polbo á feira', hints: ['Pemento', 'Cocido', 'Festa'] },
    { word: 'Empanada', hints: ['Masa', 'Forno', 'Recheo'] },
    { word: 'Caldo galego', hints: ['Grelos', 'Quente', 'Inverno'] },
    { word: 'Lacón', hints: ['Porco', 'Grelos', 'Salgado'] },
    { word: 'Filloas', hints: ['Sobremesa', 'Fina', 'Entroido'] },
    { word: 'Queixo do Cebreiro', hints: ['Leite', 'Curado', 'Montaña'] },
    { word: 'Albariño', hints: ['Viño', 'Branco', 'Rías Baixas'] },
    { word: 'Percebes', hints: ['Marisco', 'Rocha', 'Mar'] },
    { word: 'Paella', hints: ['Arroz', 'Valencia', 'Tixola'] },
    { word: 'Polbo', hints: ['Mar', 'Tentáculos', 'Cocido'] },
    { word: 'Chocolate', hints: ['Doce', 'Cacao', 'Marrón'] },
    { word: 'Tortilla', hints: ['Ovos', 'Pataca', 'Tixola'] },
    { word: 'Gazpacho', hints: ['Frío', 'Tomate', 'Verán'] },
    { word: 'Sushi', hints: ['Xapón', 'Arroz', 'Peixe cru'] },
    { word: 'Xeado', hints: ['Sobremesa', 'Frío', 'Cucurucho'] },
    { word: 'Lentellas', hints: ['Legume', 'Guiso', 'Culler'] },
    { word: 'Croqueta', hints: ['Frito', 'Bechamel', 'Tapa'] },
    { word: 'Pizza', hints: ['Italia', 'Forno', 'Redonda'] },
    { word: 'Hamburguesa', hints: ['Carne', 'Pan', 'Rápida'] },
    { word: 'Ensalada', hints: ['Verde', 'Leituga', 'Fresca'] },
    { word: 'Sopa', hints: ['Quente', 'Caldo', 'Culler'] },
    { word: 'Café', hints: ['Mañá', 'Negro', 'Cunca'] },
    { word: 'Cervexa', hints: ['Bar', 'Escuma', 'Fría'] },
    { word: 'Polo', hints: ['Forno', 'Ave', 'Carne'] },
    { word: 'Amorodos', hints: ['Froita', 'Vermello', 'Primavera'] },
    { word: 'Aceitunas', hints: ['Aperitivo', 'Aceite', 'Verdes'] },
    { word: 'Pan', hints: ['Forno', 'Fariña', 'Barra'] },
    { word: 'Mel', hints: ['Abellas', 'Doce', 'Dourado'] },
    { word: 'Allo', hints: ['Forte', 'Dente', 'Branco'] },
    { word: 'Arroz', hints: ['Gran', 'Branco', 'Asia'] },
  ],
  va: [
    { word: 'Paella', hints: ['Arròs', 'València', 'Paellera'] },
    { word: 'Fideuà', hints: ['Fideus', 'Marisc', 'Paellera'] },
    { word: 'Orxata', hints: ['Xufa', 'Fresca', 'Estiu'] },
    { word: 'Arròs al forn', hints: ['Cassola', 'Cigrons', 'Creïlla'] },
    { word: 'All i pebre', hints: ['Anguila', 'Albufera', 'Guisat'] },
    { word: 'Coca de dacsa', hints: ['Panís', 'Plana', 'Forn'] },
    { word: 'Bunyols', hints: ['Falles', 'Fregit', 'Sucre'] },
    { word: 'Esmorzaret', hints: ['Entrepà', 'Matí', 'Cacau'] },
    { word: 'Polp', hints: ['Mar', 'Tentacles', 'Brasa'] },
    { word: 'Xocolata', hints: ['Dolç', 'Cacau', 'Marró'] },
    { word: 'Truita', hints: ['Ous', 'Creïlla', 'Paella'] },
    { word: 'Gaspatxo', hints: ['Fred', 'Tomaca', 'Estiu'] },
    { word: 'Formatge', hints: ['Llet', 'Curat', 'Ratllat'] },
    { word: 'Sushi', hints: ['Japó', 'Arròs', 'Peix cru'] },
    { word: 'Gelat', hints: ['Postres', 'Fred', 'Cucurutxo'] },
    { word: 'Llentilles', hints: ['Llegum', 'Guisat', 'Cullera'] },
    { word: 'Croqueta', hints: ['Fregit', 'Beixamel', 'Tapa'] },
    { word: 'Pizza', hints: ['Itàlia', 'Forn', 'Redona'] },
    { word: 'Hamburguesa', hints: ['Carn', 'Pa', 'Ràpid'] },
    { word: 'Amanida', hints: ['Verd', 'Encisam', 'Fresca'] },
    { word: 'Sopa', hints: ['Calenta', 'Brou', 'Cullera'] },
    { word: 'Café', hints: ['Matí', 'Negre', 'Tassa'] },
    { word: 'Vi', hints: ['Beguda', 'Raïm', 'Copa'] },
    { word: 'Cervesa', hints: ['Bar', 'Espuma', 'Freda'] },
    { word: 'Pollastre', hints: ['Forn', 'Au', 'Carn'] },
    { word: 'Maduixes', hints: ['Fruita', 'Roig', 'Primavera'] },
    { word: 'Olives', hints: ['Aperitiu', 'Adobades', 'Verdes'] },
    { word: 'Pa', hints: ['Forn', 'Farina', 'Barra'] },
    { word: 'Mel', hints: ['Abelles', 'Dolç', 'Daurat'] },
    { word: 'Arròs', hints: ['Gra', 'Blanc', 'Àsia'] },
  ],
}
