import type { WordEntry } from '../../domain/content/types'
import type { LocaleCode } from '../../domain/game/types'

export const food: Partial<Record<LocaleCode, WordEntry[]>> = {
  ca: [
    { word: 'Paella', hint: 'Arròs' },
    { word: 'Pop', hint: 'Mar' },
    { word: 'Xocolata', hint: 'Dolç' },
    { word: 'Truita', hint: 'Ous' },
    { word: 'Gaspatxo', hint: 'Fred' },
    { word: 'Formatge', hint: 'Llet' },
    { word: 'Sushi', hint: 'Japó' },
    { word: 'Gelat', hint: 'Postres' },
    { word: 'Llenties', hint: 'Llegum' },
    { word: 'Croqueta', hint: 'Fregit' },
    { word: 'Pa amb tomàquet', hint: 'Esmorzar' },
    { word: 'Botifarra', hint: 'Brasa' },
    { word: 'Calçots', hint: 'Calçotada' },
    { word: 'Fideuà', hint: 'Fideus' },
    { word: 'Crema catalana', hint: 'Postres' },
    { word: 'Escudella', hint: 'Hivern' },
    { word: 'Pizza', hint: 'Itàlia' },
    { word: 'Hamburguesa', hint: 'Carn' },
    { word: 'Vi', hint: 'Beguda' },
    { word: 'Cervesa', hint: 'Bar' },
    { word: 'Pernil', hint: 'Tapa' },
    { word: 'Macarrons', hint: 'Pasta' },
    { word: 'Amanida', hint: 'Verd' },
    { word: 'Sopa', hint: 'Calenta' },
    { word: 'Cafè', hint: 'Matí' },
    { word: 'Pollastre', hint: 'Forn' },
    { word: 'Maduixes', hint: 'Fruita' },
    { word: 'Olives', hint: 'Aperitiu' },
    { word: 'Allioli', hint: 'Salsa' },
    { word: 'Coca', hint: 'Festa' },
  ],
  en: [
    { word: 'Paella', hint: 'Rice' },
    { word: 'Octopus', hint: 'Sea' },
    { word: 'Chocolate', hint: 'Sweet' },
    { word: 'Omelette', hint: 'Eggs' },
    { word: 'Gazpacho', hint: 'Cold' },
    { word: 'Cheese', hint: 'Milk' },
    { word: 'Sushi', hint: 'Japan' },
    { word: 'Ice cream', hint: 'Dessert' },
    { word: 'Lentils', hint: 'Legume' },
    { word: 'Croquette', hint: 'Fried' },
    { word: 'Pizza', hint: 'Italy' },
    { word: 'Burger', hint: 'Beef' },
    { word: 'Pasta', hint: 'Italian' },
    { word: 'Salad', hint: 'Greens' },
    { word: 'Soup', hint: 'Warm' },
    { word: 'Coffee', hint: 'Morning' },
    { word: 'Wine', hint: 'Drink' },
    { word: 'Beer', hint: 'Pub' },
    { word: 'Bread', hint: 'Bakery' },
    { word: 'Chicken', hint: 'Poultry' },
    { word: 'Strawberry', hint: 'Fruit' },
    { word: 'Olives', hint: 'Snack' },
    { word: 'Pancakes', hint: 'Breakfast' },
    { word: 'Sandwich', hint: 'Lunch' },
    { word: 'Sausage', hint: 'Grill' },
    { word: 'Tacos', hint: 'Mexico' },
    { word: 'Curry', hint: 'India' },
    { word: 'Honey', hint: 'Bees' },
    { word: 'Garlic', hint: 'Pungent' },
    { word: 'Rice', hint: 'Grain' },
  ],
  es: [
    { word: 'Paella', hint: 'Arroz' },
    { word: 'Pulpo', hint: 'Mar' },
    { word: 'Chocolate', hint: 'Dulce' },
    { word: 'Tortilla', hint: 'Huevos' },
    { word: 'Gazpacho', hint: 'Frío' },
    { word: 'Queso', hint: 'Leche' },
    { word: 'Sushi', hint: 'Japón' },
    { word: 'Helado', hint: 'Postre' },
    { word: 'Lentejas', hint: 'Legumbre' },
    { word: 'Croqueta', hint: 'Frito' },
    { word: 'Jamón', hint: 'Tapa' },
    { word: 'Cocido', hint: 'Invierno' },
    { word: 'Fabada', hint: 'Asturias' },
    { word: 'Salmorejo', hint: 'Córdoba' },
    { word: 'Churros', hint: 'Desayuno' },
    { word: 'Pizza', hint: 'Italia' },
    { word: 'Hamburguesa', hint: 'Carne' },
    { word: 'Macarrones', hint: 'Pasta' },
    { word: 'Ensalada', hint: 'Verde' },
    { word: 'Sopa', hint: 'Caliente' },
    { word: 'Café', hint: 'Mañana' },
    { word: 'Vino', hint: 'Bebida' },
    { word: 'Cerveza', hint: 'Bar' },
    { word: 'Pollo', hint: 'Horno' },
    { word: 'Fresas', hint: 'Fruta' },
    { word: 'Aceitunas', hint: 'Aperitivo' },
    { word: 'Gambas', hint: 'Marisco' },
    { word: 'Flan', hint: 'Caramelo' },
    { word: 'Migas', hint: 'Pastor' },
    { word: 'Pan', hint: 'Horno' },
  ],
  eu: [
    { word: 'Marmitako', hint: 'Hegaluzea' },
    { word: 'Pintxoa', hint: 'Barra' },
    { word: 'Bakailaoa', hint: 'Arraina' },
    { word: 'Txuleta', hint: 'Haragia' },
    { word: 'Talo', hint: 'Artoa' },
    { word: 'Idiazabal', hint: 'Gazta' },
    { word: 'Txakoli', hint: 'Ardoa' },
    { word: 'Sagardo', hint: 'Sagarra' },
    { word: 'Paella', hint: 'Arroza' },
    { word: 'Olagarroa', hint: 'Itsasoa' },
    { word: 'Txokolatea', hint: 'Goxoa' },
    { word: 'Tortilla', hint: 'Arrautzak' },
    { word: 'Gazpatxoa', hint: 'Hotza' },
    { word: 'Sushia', hint: 'Japonia' },
    { word: 'Izozkia', hint: 'Postrea' },
    { word: 'Dilistak', hint: 'Lekaleak' },
    { word: 'Kroketa', hint: 'Frijitua' },
    { word: 'Pizza', hint: 'Italia' },
    { word: 'Hanburgesa', hint: 'Okela' },
    { word: 'Entsalada', hint: 'Berdea' },
    { word: 'Zopa', hint: 'Beroa' },
    { word: 'Kafea', hint: 'Goiza' },
    { word: 'Garagardoa', hint: 'Taberna' },
    { word: 'Oilaskoa', hint: 'Labea' },
    { word: 'Marrubiak', hint: 'Fruta' },
    { word: 'Olibak', hint: 'Aperitiboa' },
    { word: 'Ogia', hint: 'Okindegia' },
    { word: 'Eztia', hint: 'Erleak' },
    { word: 'Baratxuria', hint: 'Mina' },
    { word: 'Arroza', hint: 'Alea' },
  ],
  gl: [
    { word: 'Polbo á feira', hint: 'Pemento' },
    { word: 'Empanada', hint: 'Masa' },
    { word: 'Caldo galego', hint: 'Grelos' },
    { word: 'Lacón', hint: 'Porco' },
    { word: 'Filloas', hint: 'Sobremesa' },
    { word: 'Queixo do Cebreiro', hint: 'Leite' },
    { word: 'Albariño', hint: 'Viño' },
    { word: 'Percebes', hint: 'Marisco' },
    { word: 'Paella', hint: 'Arroz' },
    { word: 'Polbo', hint: 'Mar' },
    { word: 'Chocolate', hint: 'Doce' },
    { word: 'Tortilla', hint: 'Ovos' },
    { word: 'Gazpacho', hint: 'Frío' },
    { word: 'Sushi', hint: 'Xapón' },
    { word: 'Xeado', hint: 'Sobremesa' },
    { word: 'Lentellas', hint: 'Legume' },
    { word: 'Croqueta', hint: 'Frito' },
    { word: 'Pizza', hint: 'Italia' },
    { word: 'Hamburguesa', hint: 'Carne' },
    { word: 'Ensalada', hint: 'Verde' },
    { word: 'Sopa', hint: 'Quente' },
    { word: 'Café', hint: 'Mañá' },
    { word: 'Cervexa', hint: 'Bar' },
    { word: 'Polo', hint: 'Forno' },
    { word: 'Amorodos', hint: 'Froita' },
    { word: 'Aceitunas', hint: 'Aperitivo' },
    { word: 'Pan', hint: 'Forno' },
    { word: 'Mel', hint: 'Abellas' },
    { word: 'Allo', hint: 'Forte' },
    { word: 'Arroz', hint: 'Gran' },
  ],
  va: [
    { word: 'Paella', hint: 'Arròs' },
    { word: 'Fideuà', hint: 'Fideus' },
    { word: 'Orxata', hint: 'Xufa' },
    { word: 'Arròs al forn', hint: 'Cassola' },
    { word: 'All i pebre', hint: 'Anguila' },
    { word: 'Coca de dacsa', hint: 'Panís' },
    { word: 'Bunyols', hint: 'Falles' },
    { word: 'Esmorzaret', hint: 'Entrepà' },
    { word: 'Polp', hint: 'Mar' },
    { word: 'Xocolata', hint: 'Dolç' },
    { word: 'Truita', hint: 'Ous' },
    { word: 'Gaspatxo', hint: 'Fred' },
    { word: 'Formatge', hint: 'Llet' },
    { word: 'Sushi', hint: 'Japó' },
    { word: 'Gelat', hint: 'Postres' },
    { word: 'Llentilles', hint: 'Llegum' },
    { word: 'Croqueta', hint: 'Fregit' },
    { word: 'Pizza', hint: 'Itàlia' },
    { word: 'Hamburguesa', hint: 'Carn' },
    { word: 'Amanida', hint: 'Verd' },
    { word: 'Sopa', hint: 'Calenta' },
    { word: 'Café', hint: 'Matí' },
    { word: 'Vi', hint: 'Beguda' },
    { word: 'Cervesa', hint: 'Bar' },
    { word: 'Pollastre', hint: 'Forn' },
    { word: 'Maduixes', hint: 'Fruita' },
    { word: 'Olives', hint: 'Aperitiu' },
    { word: 'Pa', hint: 'Forn' },
    { word: 'Mel', hint: 'Abelles' },
    { word: 'Arròs', hint: 'Gra' },
  ],
}
