import type { WordEntry } from '../../domain/content/types'
import type { LocaleCode } from '../../domain/game/types'

export const home: Partial<Record<LocaleCode, WordEntry[]>> = {
  ca: [
    { word: 'Rellotge', hints: ['Temps', 'Canell', 'Agulles'] },
    { word: 'Sofà', hints: ['Seure', 'Sala', 'Tou'] },
    { word: 'Nevera', hints: ['Fred', 'Cuina', 'Conserva'] },
    { word: 'Coixí', hints: ['Dormir', 'Tou', 'Cap'] },
    { word: 'Cullera', hints: ['Sopa', 'Coberts', 'Remenar'] },
    { word: 'Mirall', hints: ['Reflex', 'Vidre', 'Bany'] },
    { word: 'Llàntia', hints: ['Llum', 'Taula', 'Lectura'] },
    { word: 'Escombra', hints: ['Netejar', 'Terra', 'Pals'] },
    { word: 'Tovallola', hints: ['Eixugar', 'Bany', 'Tela'] },
    { word: 'Clau', hints: ['Pany', 'Porta', 'Obrir'] },
    { word: 'Cadira', hints: ['Taula', 'Seient', 'Quatre potes'] },
    { word: 'Llit', hints: ['Descans', 'Habitació', 'Matalàs'] },
    { word: 'Forquilla', hints: ['Punxar', 'Coberts', 'Pues'] },
    { word: 'Ganivet', hints: ['Tallar', 'Fulla', 'Esmolat'] },
    { word: 'Got', hints: ['Beure', 'Aigua', 'Vidre'] },
    { word: 'Plat', hints: ['Menjar', 'Rodó', 'Taula'] },
    { word: 'Estufa', hints: ['Calor', 'Hivern', 'Escalfar'] },
    { word: 'Ventilador', hints: ['Aire', 'Estiu', 'Aspes'] },
    { word: 'Aspiradora', hints: ['Pols', 'Netejar', 'Endollar'] },
    { word: 'Rentadora', hints: ['Roba', 'Aigua', 'Centrifugar'] },
    { word: 'Forn', hints: ['Coure', 'Calor', 'Pastissos'] },
    { word: 'Cassola', hints: ['Cuinar', 'Foc', 'Guisat'] },
    { word: 'Paella', hints: ['Fregir', 'Mànec', 'Oli'] },
    { word: 'Manta', hints: ['Abrigar', 'Sofà', 'Calenta'] },
    { word: 'Cortina', hints: ['Finestra', 'Tela', 'Tapar'] },
    { word: 'Catifa', hints: ['Terra', 'Tova', 'Sala'] },
    { word: 'Calaix', hints: ['Guardar', 'Moble', 'Estirar'] },
    { word: 'Armari', hints: ['Roba', 'Portes', 'Habitació'] },
    { word: 'Bombeta', hints: ['Encendre', 'Llum', 'Vidre'] },
    { word: 'Tisores', hints: ['Retallar', 'Paper', 'Dos talls'] },
    { word: 'Martell', hints: ['Clavar', 'Eina', 'Cops'] },
    { word: 'Endoll', hints: ['Corrent', 'Paret', 'Connectar'] },
  ],
  en: [
    { word: 'Clock', hints: ['Time', 'Wall', 'Hands'] },
    { word: 'Sofa', hints: ['Sit', 'Living room', 'Soft'] },
    { word: 'Fridge', hints: ['Cold', 'Kitchen', 'Preserve'] },
    { word: 'Pillow', hints: ['Sleep', 'Soft', 'Head'] },
    { word: 'Spoon', hints: ['Soup', 'Cutlery', 'Stir'] },
    { word: 'Mirror', hints: ['Reflection', 'Glass', 'Bathroom'] },
    { word: 'Lamp', hints: ['Light', 'Desk', 'Reading'] },
    { word: 'Broom', hints: ['Sweep', 'Floor', 'Bristles'] },
    { word: 'Towel', hints: ['Dry', 'Bathroom', 'Cloth'] },
    { word: 'Key', hints: ['Lock', 'Door', 'Open'] },
    { word: 'Chair', hints: ['Table', 'Seat', 'Four legs'] },
    { word: 'Bed', hints: ['Rest', 'Sleep', 'Mattress'] },
    { word: 'Fork', hints: ['Stab', 'Cutlery', 'Prongs'] },
    { word: 'Knife', hints: ['Cut', 'Blade', 'Sharp'] },
    { word: 'Glass', hints: ['Drink', 'Water', 'Clear'] },
    { word: 'Plate', hints: ['Food', 'Round', 'Table'] },
    { word: 'Heater', hints: ['Warm', 'Winter', 'Cosy'] },
    { word: 'Fan', hints: ['Air', 'Summer', 'Blades'] },
    { word: 'Vacuum', hints: ['Dust', 'Clean', 'Plug in'] },
    { word: 'Washer', hints: ['Laundry', 'Water', 'Spin'] },
    { word: 'Oven', hints: ['Bake', 'Heat', 'Cake'] },
    { word: 'Pot', hints: ['Cook', 'Stove', 'Stew'] },
    { word: 'Pan', hints: ['Fry', 'Handle', 'Oil'] },
    { word: 'Blanket', hints: ['Warmth', 'Bed', 'Cosy'] },
    { word: 'Curtain', hints: ['Window', 'Cloth', 'Cover'] },
    { word: 'Carpet', hints: ['Floor', 'Soft', 'Room'] },
    { word: 'Drawer', hints: ['Storage', 'Pull out', 'Furniture'] },
    { word: 'Wardrobe', hints: ['Clothes', 'Doors', 'Bedroom'] },
    { word: 'Bulb', hints: ['Switch', 'Light', 'Glass'] },
    { word: 'Scissors', hints: ['Snip', 'Paper', 'Two blades'] },
    { word: 'Hammer', hints: ['Nail', 'Tool', 'Bang'] },
    { word: 'Kettle', hints: ['Boil', 'Tea', 'Spout'] },
  ],
  es: [
    { word: 'Reloj', hints: ['Tiempo', 'Muñeca', 'Agujas'] },
    { word: 'Sofá', hints: ['Sentarse', 'Salón', 'Blando'] },
    { word: 'Nevera', hints: ['Frío', 'Cocina', 'Conservar'] },
    { word: 'Almohada', hints: ['Dormir', 'Blanda', 'Cabeza'] },
    { word: 'Cuchara', hints: ['Sopa', 'Cubierto', 'Remover'] },
    { word: 'Espejo', hints: ['Reflejo', 'Cristal', 'Baño'] },
    { word: 'Lámpara', hints: ['Luz', 'Mesa', 'Lectura'] },
    { word: 'Escoba', hints: ['Limpiar', 'Suelo', 'Cerdas'] },
    { word: 'Toalla', hints: ['Secar', 'Baño', 'Tela'] },
    { word: 'Llave', hints: ['Cerradura', 'Puerta', 'Abrir'] },
    { word: 'Silla', hints: ['Mesa', 'Asiento', 'Cuatro patas'] },
    { word: 'Cama', hints: ['Descanso', 'Dormitorio', 'Colchón'] },
    { word: 'Tenedor', hints: ['Pinchar', 'Cubierto', 'Púas'] },
    { word: 'Cuchillo', hints: ['Cortar', 'Hoja', 'Afilado'] },
    { word: 'Vaso', hints: ['Beber', 'Agua', 'Cristal'] },
    { word: 'Plato', hints: ['Comida', 'Redondo', 'Mesa'] },
    { word: 'Estufa', hints: ['Calor', 'Invierno', 'Calentar'] },
    { word: 'Ventilador', hints: ['Aire', 'Verano', 'Aspas'] },
    { word: 'Aspiradora', hints: ['Polvo', 'Limpiar', 'Enchufar'] },
    { word: 'Lavadora', hints: ['Ropa', 'Agua', 'Centrifugar'] },
    { word: 'Horno', hints: ['Hornear', 'Calor', 'Pastel'] },
    { word: 'Olla', hints: ['Cocinar', 'Fuego', 'Guiso'] },
    { word: 'Sartén', hints: ['Freír', 'Mango', 'Aceite'] },
    { word: 'Manta', hints: ['Abrigar', 'Sofá', 'Calentita'] },
    { word: 'Cortina', hints: ['Ventana', 'Tela', 'Tapar'] },
    { word: 'Alfombra', hints: ['Suelo', 'Blanda', 'Salón'] },
    { word: 'Cajón', hints: ['Guardar', 'Mueble', 'Tirar'] },
    { word: 'Armario', hints: ['Ropa', 'Puertas', 'Dormitorio'] },
    { word: 'Bombilla', hints: ['Encender', 'Luz', 'Cristal'] },
    { word: 'Tijeras', hints: ['Recortar', 'Papel', 'Dos filos'] },
    { word: 'Martillo', hints: ['Clavar', 'Herramienta', 'Golpe'] },
    { word: 'Enchufe', hints: ['Corriente', 'Pared', 'Conectar'] },
  ],
  eu: [
    { word: 'Erlojua', hints: ['Denbora', 'Eskumuturra', 'Orratzak'] },
    { word: 'Sofa', hints: ['Eseri', 'Egongela', 'Biguna'] },
    { word: 'Hozkailua', hints: ['Hotza', 'Sukaldea', 'Janaria gorde'] },
    { word: 'Burkoa', hints: ['Lo egin', 'Biguna', 'Burua'] },
    { word: 'Koilara', hints: ['Zopa', 'Mahai tresnak', 'Nahastu'] },
    { word: 'Ispilua', hints: ['Islada', 'Beira', 'Komuna'] },
    { word: 'Lanpara', hints: ['Argia', 'Mahaia', 'Irakurri'] },
    { word: 'Erratza', hints: ['Garbitu', 'Lurra', 'Zerdak'] },
    { word: 'Eskuoihala', hints: ['Lehortu', 'Komuna', 'Ehuna'] },
    { word: 'Giltza', hints: ['Sarraila', 'Atea', 'Ireki'] },
    { word: 'Aulkia', hints: ['Mahaia', 'Eserlekua', 'Lau hanka'] },
    { word: 'Ohea', hints: ['Atsedena', 'Logela', 'Koltxoia'] },
    { word: 'Sardexka', hints: ['Ziztatu', 'Mahai tresnak', 'Hortzak'] },
    { word: 'Labana', hints: ['Moztu', 'Xafla', 'Zorrotza'] },
    { word: 'Edalontzia', hints: ['Edan', 'Ura', 'Beira'] },
    { word: 'Platera', hints: ['Janaria', 'Biribila', 'Mahaia'] },
    { word: 'Berogailua', hints: ['Beroa', 'Negua', 'Epeldu'] },
    { word: 'Haizagailua', hints: ['Airea', 'Uda', 'Palak'] },
    { word: 'Xurgagailua', hints: ['Hautsa', 'Garbitu', 'Entxufatu'] },
    { word: 'Garbigailua', hints: ['Arropa', 'Ura', 'Zentrifugatu'] },
    { word: 'Labea', hints: ['Erre', 'Beroa', 'Pastela'] },
    { word: 'Lapikoa', hints: ['Sukaldatu', 'Sua', 'Gisatua'] },
    { word: 'Zartagina', hints: ['Frijitu', 'Kirtena', 'Olioa'] },
    { word: 'Manta', hints: ['Estali', 'Sofa', 'Epela'] },
    { word: 'Errezela', hints: ['Leihoa', 'Ehuna', 'Estali'] },
    { word: 'Alfonbra', hints: ['Lurra', 'Biguna', 'Egongela'] },
    { word: 'Tiradera', hints: ['Gorde', 'Altzaria', 'Atera'] },
    { word: 'Armairua', hints: ['Jantziak', 'Ateak', 'Logela'] },
    { word: 'Bonbilla', hints: ['Piztu', 'Argia', 'Beira'] },
    { word: 'Guraizeak', hints: ['Ebaki', 'Papera', 'Bi aho'] },
    { word: 'Mailua', hints: ['Iltzea', 'Tresna', 'Kolpea'] },
    { word: 'Entxufea', hints: ['Korrontea', 'Horma', 'Konektatu'] },
  ],
  gl: [
    { word: 'Reloxo', hints: ['Tempo', 'Pulso', 'Agullas'] },
    { word: 'Sofá', hints: ['Sentar', 'Salón', 'Brando'] },
    { word: 'Neveira', hints: ['Frío', 'Cociña', 'Conservar'] },
    { word: 'Almofada', hints: ['Durmir', 'Branda', 'Cabeza'] },
    { word: 'Culler', hints: ['Sopa', 'Cuberto', 'Remexer'] },
    { word: 'Espello', hints: ['Reflexo', 'Cristal', 'Baño'] },
    { word: 'Lámpada', hints: ['Luz', 'Mesa', 'Ler'] },
    { word: 'Vasoira', hints: ['Limpar', 'Chan', 'Cerdas'] },
    { word: 'Toalla', hints: ['Secar', 'Baño', 'Tea'] },
    { word: 'Chave', hints: ['Pechadura', 'Porta', 'Abrir'] },
    { word: 'Cadeira', hints: ['Mesa', 'Asento', 'Catro patas'] },
    { word: 'Cama', hints: ['Descanso', 'Cuarto', 'Colchón'] },
    { word: 'Garfo', hints: ['Pinchar', 'Cuberto', 'Dentes'] },
    { word: 'Coitelo', hints: ['Cortar', 'Folla', 'Afiado'] },
    { word: 'Vaso', hints: ['Beber', 'Auga', 'Cristal'] },
    { word: 'Prato', hints: ['Comida', 'Redondo', 'Mesa'] },
    { word: 'Estufa', hints: ['Calor', 'Inverno', 'Quentar'] },
    { word: 'Ventilador', hints: ['Aire', 'Verán', 'Aspas'] },
    { word: 'Aspiradora', hints: ['Po', 'Limpar', 'Enchufar'] },
    { word: 'Lavadora', hints: ['Roupa', 'Auga', 'Centrifugar'] },
    { word: 'Forno', hints: ['Asar', 'Calor', 'Biscoito'] },
    { word: 'Pota', hints: ['Cociñar', 'Lume', 'Guiso'] },
    { word: 'Tixola', hints: ['Fritir', 'Mango', 'Aceite'] },
    { word: 'Manta', hints: ['Abrigar', 'Sofá', 'Quente'] },
    { word: 'Cortina', hints: ['Fiestra', 'Tea', 'Tapar'] },
    { word: 'Alfombra', hints: ['Chan', 'Branda', 'Salón'] },
    { word: 'Caixón', hints: ['Gardar', 'Moble', 'Tirar'] },
    { word: 'Armario', hints: ['Roupa', 'Portas', 'Cuarto'] },
    { word: 'Lámpada de man', hints: ['Acender', 'Pilas', 'Escuridade'] },
    { word: 'Tesoiras', hints: ['Recortar', 'Papel', 'Dous fíos'] },
    { word: 'Martelo', hints: ['Cravar', 'Ferramenta', 'Golpe'] },
    { word: 'Enchufe', hints: ['Corrente', 'Parede', 'Conectar'] },
  ],
  va: [
    { word: 'Rellonge', hints: ['Temps', 'Canell', 'Agulles'] },
    { word: 'Sofà', hints: ['Asseure', 'Sala', 'Bla'] },
    { word: 'Nevera', hints: ['Fred', 'Cuina', 'Conservar'] },
    { word: 'Coixí', hints: ['Dormir', 'Bla', 'Cap'] },
    { word: 'Cullera', hints: ['Sopa', 'Coberts', 'Remenar'] },
    { word: 'Espill', hints: ['Reflex', 'Vidre', 'Bany'] },
    { word: 'Llum', hints: ['Claror', 'Bombeta', 'Encendre'] },
    { word: 'Granera', hints: ['Agranar', 'Terra', 'Pals'] },
    { word: 'Tovalla', hints: ['Eixugar', 'Bany', 'Tela'] },
    { word: 'Clau', hints: ['Pany', 'Porta', 'Obrir'] },
    { word: 'Cadira', hints: ['Taula', 'Seient', 'Quatre potes'] },
    { word: 'Llit', hints: ['Descans', 'Habitació', 'Matalàs'] },
    { word: 'Forquilla', hints: ['Punxar', 'Coberts', 'Pues'] },
    { word: 'Ganivet', hints: ['Tallar', 'Fulla', 'Esmolat'] },
    { word: 'Got', hints: ['Beure', 'Aigua', 'Vidre'] },
    { word: 'Plat', hints: ['Menjar', 'Redó', 'Taula'] },
    { word: 'Estufa', hints: ['Calfor', 'Hivern', 'Calfar'] },
    { word: 'Ventilador', hints: ['Aire', 'Estiu', 'Aspes'] },
    { word: 'Aspiradora', hints: ['Pols', 'Netejar', 'Endollar'] },
    { word: 'Llavadora', hints: ['Roba', 'Aigua', 'Centrifugar'] },
    { word: 'Forn', hints: ['Coure', 'Calfor', 'Pastissos'] },
    { word: 'Cassola', hints: ['Cuinar', 'Foc', 'Guisat'] },
    { word: 'Paella', hints: ['Fregir', 'Mànec', 'Oli'] },
    { word: 'Manta', hints: ['Abrigar', 'Sofà', 'Calenta'] },
    { word: 'Cortina', hints: ['Finestra', 'Tela', 'Tapar'] },
    { word: 'Catifa', hints: ['Terra', 'Tova', 'Sala'] },
    { word: 'Calaix', hints: ['Guardar', 'Moble', 'Estirar'] },
    { word: 'Armari', hints: ['Roba', 'Portes', 'Habitació'] },
    { word: 'Bombeta', hints: ['Encendre', 'Claror', 'Vidre'] },
    { word: 'Tisores', hints: ['Retallar', 'Paper', 'Dos talls'] },
    { word: 'Martell', hints: ['Clavar', 'Eina', 'Colps'] },
    { word: 'Endoll', hints: ['Corrent', 'Paret', 'Connectar'] },
  ],
}
