import type { WordEntry } from '../../domain/content/types'
import type { LocaleCode } from '../../domain/game/types'

export const music: Partial<Record<LocaleCode, WordEntry[]>> = {
  ca: [
    { word: 'Guitarra', hints: ['Sis cordes', 'Rasgueig', 'Trasts'] },
    { word: 'Piano', hints: ['Tecles', 'Blanc i negre', 'Cua'] },
    { word: 'Violí', hints: ['Arquet', 'Quatre cordes', 'Sota la barbeta'] },
    { word: 'Bateria', hints: ['Ritme', 'Baquetes', 'Plats'] },
    { word: 'Flauta', hints: ['Vent', 'Travessera', 'Forats'] },
    { word: 'Trompeta', hints: ['Metall', 'Pistons', 'Sordina'] },
    { word: 'Saxofon', hints: ['Jazz', 'Llautó corbat', 'Canya'] },
    { word: 'Acordió', hints: ['Manxa', 'Botons', 'Aire'] },
    { word: 'Clarinet', hints: ['Canya', 'Vent de fusta', 'Negre'] },
    { word: 'Contrabaix', hints: ['Greus', 'Quatre cordes', 'Dempeus'] },
    { word: 'Tenora', hints: ['Cobla', 'Doble canya', 'Sardanes'] },
    { word: 'Rock', hints: ['Guitarres elèctriques', 'Bateria forta', 'Rebel·lia'] },
    { word: 'Jazz', hints: ['Improvisació', 'Nova Orleans', 'Swing'] },
    { word: 'Pop', hints: ['Llistes d’èxits', 'Comercial', 'Tornada enganxosa'] },
    { word: 'Flamenc', hints: ['Andalusia', 'Taconeig', 'Cante jondo'] },
    { word: 'Reggae', hints: ['Jamaica', 'Bob Marley', 'Ritme lent'] },
    { word: 'Bachata', hints: ['Ball llatí', 'Carib', 'Parella'] },
    { word: 'Tango', hints: ['Argentina', 'Bandoneó', 'Parella'] },
    { word: 'Òpera', hints: ['Veu lírica', 'Escenari', 'Ària'] },
    { word: 'Rumba catalana', hints: ['Peret', 'Ventilador', 'Gràcia'] },
    { word: 'Sardana', hints: ['Dansa en rotllana', 'Cobla', 'Mans agafades'] },
    { word: 'Coral', hints: ['Veus juntes', 'Cantar en grup', 'Director'] },
    { word: 'Orquestra', hints: ['Molts músics', 'Simfònica', 'Batuta'] },
    { word: 'Rosalía', hints: ['Cantant catalana', 'Flamenc modern', 'Ungles llargues'] },
    { word: 'Txarango', hints: ['Festa mestissa', 'Directes massius', 'Catalunya'] },
    {
      word: 'Taylor Swift',
      hints: ['Cantant americana', 'Gires multitudinàries', 'Country i pop'],
    },
    { word: 'Ed Sheeran', hints: ['Cantant anglès', 'Pèl-roig', 'Guitarra acústica'] },
    { word: 'Billie Eilish', hints: ['Veu xiuxiuejada', 'Cabells de colors', 'Cantant jove'] },
    { word: 'Oques Grasses', hints: ['Vic', 'Festes majors', 'Pop festiu'] },
    { word: 'Stay Homas', hints: ['Confinament', 'Terrat', 'Grup català'] },
    { word: 'Doctor Prats', hints: ['Mestissatge festiu', 'Terrassa', 'Vents'] },
  ],
  en: [
    { word: 'Guitar', hints: ['Six strings', 'Frets', 'Strumming'] },
    { word: 'Piano', hints: ['Keys', 'Black and white', 'Grand'] },
    { word: 'Violin', hints: ['Bow', 'Four strings', 'Chin rest'] },
    { word: 'Drums', hints: ['Rhythm', 'Sticks', 'Cymbals'] },
    { word: 'Flute', hints: ['Woodwind', 'Silver', 'Holes'] },
    { word: 'Trumpet', hints: ['Brass', 'Valves', 'Fanfare'] },
    { word: 'Saxophone', hints: ['Jazz horn', 'Reed', 'Curved metal'] },
    { word: 'Cello', hints: ['Low strings', 'Bowed', 'Seated player'] },
    { word: 'Clarinet', hints: ['Single reed', 'Woodwind', 'Black tube'] },
    { word: 'Harp', hints: ['Plucked strings', 'Tall frame', 'Angelic'] },
    { word: 'Trombone', hints: ['Slide', 'Brass', 'Low pitch'] },
    { word: 'Rock', hints: ['Electric guitars', 'Loud drums', 'Rebellion'] },
    { word: 'Jazz', hints: ['Improvisation', 'New Orleans', 'Swing'] },
    { word: 'Pop', hints: ['Charts', 'Catchy chorus', 'Mainstream'] },
    { word: 'Blues', hints: ['Mississippi', 'Twelve bars', 'Sorrowful'] },
    { word: 'Reggae', hints: ['Jamaica', 'Dreadlocks', 'Offbeat'] },
    { word: 'Country music', hints: ['Nashville', 'Cowboy', 'Banjo'] },
    { word: 'Techno', hints: ['Electronic beats', 'Synthesizer', 'Nightclub'] },
    { word: 'Opera', hints: ['Soprano', 'Stage drama', 'Aria'] },
    { word: 'Hip hop', hints: ['Breakdance', 'Beats', 'Street culture'] },
    { word: 'Choir', hints: ['Group of voices', 'Harmony', 'Conductor'] },
    { word: 'Orchestra', hints: ['Many players', 'Symphony', 'Baton'] },
    { word: 'The Beatles', hints: ['Liverpool', 'Sixties', 'British band'] },
    { word: 'Taylor Swift', hints: ['Pop star', 'Stadium tour', 'Songwriter'] },
    { word: 'Ed Sheeran', hints: ['Red hair', 'Acoustic guitar', 'Loop pedal'] },
    { word: 'Billie Eilish', hints: ['Whispery voice', 'Gen Z star', 'Dark pop'] },
    { word: 'Adele', hints: ['Powerful voice', 'London', 'Ballads'] },
    { word: 'Michael Jackson', hints: ['Dancer', 'Eighties', 'Sparkly glove'] },
    { word: 'Beyoncé', hints: ['R&B', 'Houston', 'Diva'] },
    { word: 'Harry Styles', hints: ['Boy band past', 'Pop star', 'Feather boa'] },
    { word: 'Shakira', hints: ['Colombia', 'Belly dance', 'Latin pop'] },
  ],
  es: [
    { word: 'Guitarra', hints: ['Seis cuerdas', 'Trastes', 'Rasgueo'] },
    { word: 'Piano', hints: ['Teclas', 'Blanco y negro', 'De cola'] },
    { word: 'Violín', hints: ['Arco', 'Cuatro cuerdas', 'Mentonera'] },
    { word: 'Batería', hints: ['Ritmo', 'Baquetas', 'Platillos'] },
    { word: 'Flauta', hints: ['Viento', 'Travesera', 'Agujeros'] },
    { word: 'Trompeta', hints: ['Metal', 'Pistones', 'Fanfarria'] },
    { word: 'Saxofón', hints: ['Jazz', 'Latón curvo', 'Caña'] },
    { word: 'Acordeón', hints: ['Fuelle', 'Botones', 'Aire'] },
    { word: 'Clarinete', hints: ['Lengüeta', 'Viento madera', 'Tubo negro'] },
    { word: 'Violonchelo', hints: ['Cuerda grave', 'Arco', 'Sentado'] },
    { word: 'Arpa', hints: ['Cuerdas pulsadas', 'Marco alto', 'Angelical'] },
    { word: 'Rock', hints: ['Guitarras eléctricas', 'Batería fuerte', 'Rebeldía'] },
    { word: 'Jazz', hints: ['Improvisación', 'Nueva Orleans', 'Swing'] },
    { word: 'Pop', hints: ['Listas de éxitos', 'Estribillo pegadizo', 'Comercial'] },
    { word: 'Sevillanas', hints: ['Andalucía', 'Feria', 'Palmas'] },
    { word: 'Reguetón', hints: ['Puerto Rico', 'Ritmo latino', 'Discoteca'] },
    { word: 'Bachata', hints: ['Baile en pareja', 'República Dominicana', 'Romántica'] },
    { word: 'Rap', hints: ['Rimas', 'Micrófono', 'Batallas'] },
    { word: 'Música clásica', hints: ['Beethoven', 'Partitura', 'Concierto'] },
    { word: 'Tango', hints: ['Argentina', 'Bandoneón', 'Pareja'] },
    { word: 'Coro', hints: ['Voces juntas', 'Armonía', 'Director'] },
    { word: 'Orquesta', hints: ['Muchos músicos', 'Sinfónica', 'Batuta'] },
    { word: 'Rosalía', hints: ['Flamenco pop', 'Catalana', 'Uñas largas'] },
    { word: 'Taylor Swift', hints: ['Estadounidense', 'Pop country', 'Gira mundial'] },
    { word: 'Paco de Lucía', hints: ['Guitarra flamenca', 'Algeciras', 'Virtuoso'] },
    { word: 'Camarón de la Isla', hints: ['San Fernando', 'Leyenda gitana', 'Cante flamenco'] },
    { word: 'Aitana', hints: ['Operación Triunfo', 'Pop juvenil', 'Barcelona'] },
    { word: 'Estopa', hints: ['Hermanos rumberos', 'Cornellà', 'Rumba rock'] },
    { word: 'Alejandro Sanz', hints: ['Baladas', 'Madrileño', 'Voz rasgada'] },
    { word: 'Bad Bunny', hints: ['Trap latino', 'Puerto Rico', 'Gafas de sol'] },
    { word: 'Lola Índigo', hints: ['Bailarina', 'Pop urbano', 'Coreografías'] },
  ],
  eu: [
    { word: 'Gitarra', hints: ['Sei soka', 'Trasteak', 'Akordeak'] },
    { word: 'Pianoa', hints: ['Teklak', 'Zuri-beltza', 'Pedalak'] },
    { word: 'Biolina', hints: ['Arkua', 'Lau soka', 'Kokotsa'] },
    { word: 'Bateria', hints: ['Erritmoa', 'Makilak', 'Platerak'] },
    { word: 'Txirula', hints: ['Haize tresna', 'Zuloak', 'Esku bat'] },
    { word: 'Tronpeta', hints: ['Metala', 'Pistoiak', 'Haize tresna'] },
    { word: 'Saxofoia', hints: ['Jazza', 'Letoi okertua', 'Mihia'] },
    { word: 'Trikitixa', hints: ['Panderoa', 'Botoiak', 'Erromeria'] },
    { word: 'Alboka', hints: ['Adarra', 'Haize tresna', 'Tradizionala'] },
    { word: 'Txalaparta', hints: ['Bi makila', 'Egurra', 'Bikoteka'] },
    { word: 'Klarinetea', hints: ['Mihia', 'Egurrezko haize tresna', 'Tutu beltza'] },
    { word: 'Biolontxeloa', hints: ['Soinu baxua', 'Arkua', 'Eserita'] },
    { word: 'Rocka', hints: ['Gitarra elektrikoak', 'Bateria gogorra', 'Errebeldia'] },
    { word: 'Jazza', hints: ['Inprobisazioa', 'New Orleans', 'Swinga'] },
    { word: 'Popa', hints: ['Arrakasta zerrendak', 'Errepika erraza', 'Komertziala'] },
    { word: 'Punka', hints: ['Azkar eta gordin', 'Errebeldia', 'Gitarra zaratatsuak'] },
    { word: 'Reggaea', hints: ['Jamaika', 'Rastak', 'Erritmo geldoa'] },
    { word: 'Bertsoa', hints: ['Inprobisatua', 'Doinua', 'Plazan'] },
    { word: 'Abesbatza', hints: ['Ahots taldea', 'Harmonia', 'Zuzendaria'] },
    { word: 'Orkestra', hints: ['Musikari asko', 'Sinfonikoa', 'Batuta'] },
    { word: 'Ken Zazpi', hints: ['Euskal rocka', 'Bizkaia', 'Bi ahots'] },
    { word: 'Berri Txarrak', hints: ['Lekunberri', 'Rock gogorra', 'Hiru kide'] },
    { word: 'Huntza', hints: ['Trikitixa', 'Talde gaztea', 'Pop alaia'] },
    { word: 'ETS', hints: ['Rock alaia', 'Festak', 'Jaialdiak'] },
    { word: 'Su Ta Gar', hints: ['Heavy euskalduna', 'Eibar', 'Metala'] },
    { word: 'Gatibu', hints: ['Gernika', 'Bizkaiera', 'Rocka'] },
    { word: 'Bulego', hints: ['Pop elektronikoa', 'Sintetizadoreak', 'Dantza'] },
    { word: 'Kortatu', hints: ['Punka', 'Irun', 'Ska'] },
    { word: 'Izaro', hints: ['Kantautorea', 'Ahots goxoa', 'Pianoa'] },
    { word: 'Esne Beltza', hints: ['Festa giroa', 'Mestizajea', 'Trikitixa'] },
    { word: 'Zea Mays', hints: ['Emakume abeslaria', 'Bilbo', 'Rock leuna'] },
  ],
  gl: [
    { word: 'Guitarra', hints: ['Seis cordas', 'Trastes', 'Rasgueo'] },
    { word: 'Piano', hints: ['Teclas', 'Branco e negro', 'De cola'] },
    { word: 'Violín', hints: ['Arco', 'Catro cordas', 'Queixeira'] },
    { word: 'Batería', hints: ['Ritmo', 'Baquetas', 'Pratos'] },
    { word: 'Frauta', hints: ['Vento', 'Furados', 'Soprar'] },
    { word: 'Trompeta', hints: ['Metal', 'Pistóns', 'Fanfarria'] },
    { word: 'Saxofón', hints: ['Jazz', 'Latón curvo', 'Cana'] },
    { word: 'Gaita', hints: ['Fol', 'Galega', 'Soprete'] },
    { word: 'Pandeireta', hints: ['Percusión tradicional', 'Sonaxas', 'Cantareiras'] },
    { word: 'Zanfona', hints: ['Manivela', 'Roda', 'Medieval'] },
    { word: 'Clarinete', hints: ['Lingüeta', 'Vento madeira', 'Tubo negro'] },
    { word: 'Violonchelo', hints: ['Corda grave', 'Arco', 'Sentado'] },
    { word: 'Arpa', hints: ['Cordas pulsadas', 'Marco alto', 'Anxelical'] },
    { word: 'Rock', hints: ['Guitarras eléctricas', 'Batería forte', 'Rebeldía'] },
    { word: 'Jazz', hints: ['Improvisación', 'Nova Orleans', 'Swing'] },
    { word: 'Pop', hints: ['Listas de éxitos', 'Retrouso pegañento', 'Comercial'] },
    { word: 'Punk', hints: ['Rápido e cru', 'Rebeldía', 'Guitarras ruidosas'] },
    { word: 'Reggae', hints: ['Xamaica', 'Bob Marley', 'Ritmo lento'] },
    { word: 'Muiñeira', hints: ['Baile galego', 'Compás ternario', 'Gaita'] },
    { word: 'Coro', hints: ['Voces xuntas', 'Harmonía', 'Director'] },
    { word: 'Orquestra', hints: ['Moitos músicos', 'Sinfónica', 'Batuta'] },
    { word: 'Luar na Lubre', hints: ['Folk galego', 'Celta', 'A Coruña'] },
    { word: 'Carlos Núñez', hints: ['Gaiteiro', 'Vigo', 'Virtuoso'] },
    { word: 'Taylor Swift', hints: ['Estadounidense', 'Pop country', 'Xira mundial'] },
    { word: 'Cristina Pato', hints: ['Gaita virtuosa', 'Ourense', 'Fusión'] },
    { word: 'Ed Sheeran', hints: ['Británico', 'Pelo roxo', 'Cantautor'] },
    { word: 'Billie Eilish', hints: ['Voz suave', 'Pelo tinguido', 'Moi nova'] },
    { word: 'Siniestro Total', hints: ['Vigo punk', 'Humor', 'Anos 80'] },
    { word: 'Tanxugueiras', hints: ['Tres pandeireteiras', 'Benidorm Fest', 'Folk moderno'] },
    { word: 'Aitana', hints: ['Operación Triunfo', 'Pop xuvenil', 'Barcelona'] },
    { word: 'Lola Índigo', hints: ['Bailarina', 'Pop urbano', 'Coreografías'] },
  ],
  va: [
    { word: 'Guitarra', hints: ['Sis cordes', 'Trasts', 'Rasgueig'] },
    { word: 'Piano', hints: ['Tecles', 'Blanc i negre', 'De cua'] },
    { word: 'Violí', hints: ['Arquet', 'Quatre cordes', 'Sota la barbeta'] },
    { word: 'Bateria', hints: ['Ritme', 'Baquetes', 'Plats'] },
    { word: 'Flauta', hints: ['Vent', 'Travessera', 'Forats'] },
    { word: 'Trompeta', hints: ['Metall', 'Pistons', 'Banda'] },
    { word: 'Saxofon', hints: ['Jazz', 'Llautó corbat', 'Canya'] },
    { word: 'Dolçaina', hints: ['Festa valenciana', 'Tabal', 'Vent tradicional'] },
    { word: 'Tabal', hints: ['Acompanya la dolçaina', 'Percussió', 'Festa de carrer'] },
    { word: 'Clarinet', hints: ['Canya', 'Vent de fusta', 'Tub negre'] },
    { word: 'Violoncel', hints: ['Corda greu', 'Arquet', 'Assegut'] },
    { word: 'Contrabaix', hints: ['Greus', 'Quatre cordes', 'Dempeus'] },
    { word: 'Arpa', hints: ['Cordes polsades', 'Marc alt', 'Angelical'] },
    { word: 'Rock', hints: ['Guitarres elèctriques', 'Bateria forta', 'Rebel·lia'] },
    { word: 'Jazz', hints: ['Improvisació', 'Nova Orleans', 'Swing'] },
    { word: 'Pop', hints: ['Llistes d’èxits', 'Tornada enganxosa', 'Comercial'] },
    { word: 'Reggae', hints: ['Jamaica', 'Bob Marley', 'Ritme lent'] },
    { word: 'Bachata', hints: ['Ball llatí', 'Carib', 'Parella'] },
    { word: 'Pasdoble', hints: ['Banda i bous', 'Festa de poble', 'Marxa'] },
    { word: 'Coral', hints: ['Veus juntes', 'Harmonia', 'Director'] },
    { word: 'Orquestra', hints: ['Molts músics', 'Simfònica', 'Batuta'] },
    { word: 'Obrint Pas', hints: ['Ska valencià', 'Dolçaina i guitarres', 'València'] },
    { word: 'La Gossa Sorda', hints: ['Pego', 'Mestissatge', 'Marina Alta'] },
    { word: 'Aspencat', hints: ['Mestissatge valencià', 'Festiu', 'Reivindicatiu'] },
    { word: 'Zoo', hints: ['Gandia', 'Rap mestís', 'Electrònica'] },
    { word: 'Rosalía', hints: ['Cantant catalana', 'Flamenc modern', 'Ungles llargues'] },
    {
      word: 'Taylor Swift',
      hints: ['Cantant americana', 'Gires multitudinàries', 'Country i pop'],
    },
    { word: 'Auxili', hints: ['Reggae', 'Ontinyent', 'Mestissatge'] },
    { word: 'Ed Sheeran', hints: ['Cantant anglés', 'Pèl-roig', 'Guitarra acústica'] },
    { word: 'La Fúmiga', hints: ['Festa', 'Mestissatge festiu', 'Vents'] },
    { word: 'Smoking Souls', hints: ['Rock valencià', 'Guitarres potents', 'Festivals'] },
  ],
}
