import type { WordEntry } from '../../domain/content/types'
import type { LocaleCode } from '../../domain/game/types'

export const music: Partial<Record<LocaleCode, WordEntry[]>> = {
  ca: [
    { word: 'Guitarra', hint: 'Sis cordes' },
    { word: 'Piano', hint: 'Tecles' },
    { word: 'Violí', hint: 'Arquet' },
    { word: 'Bateria', hint: 'Ritme' },
    { word: 'Flauta', hint: 'Vent' },
    { word: 'Trompeta', hint: 'Metall' },
    { word: 'Saxofon', hint: 'Jazz' },
    { word: 'Acordió', hint: 'Manxa' },
    { word: 'Clarinet', hint: 'Canya' },
    { word: 'Contrabaix', hint: 'Greus' },
    { word: 'Tenora', hint: 'Cobla' },
    { word: 'Rock', hint: 'Guitarres elèctriques' },
    { word: 'Jazz', hint: 'Improvisació' },
    { word: 'Pop', hint: 'Llistes d’èxits' },
    { word: 'Flamenc', hint: 'Andalusia' },
    { word: 'Reggae', hint: 'Jamaica' },
    { word: 'Salsa', hint: 'Ball llatí' },
    { word: 'Tango', hint: 'Argentina' },
    { word: 'Òpera', hint: 'Veu lírica' },
    { word: 'Rumba catalana', hint: 'Peret' },
    { word: 'Sardana', hint: 'Dansa en rotllana' },
    { word: 'Cor', hint: 'Veus juntes' },
    { word: 'Orquestra', hint: 'Molts músics' },
    { word: 'Manel', hint: 'Pop català' },
    { word: 'Txarango', hint: 'Festa mestissa' },
    { word: 'Els Pets', hint: 'Constantí' },
    { word: 'Sopa de Cabra', hint: 'Rock gironí' },
    { word: 'Antònia Font', hint: 'Mallorca' },
    { word: 'Oques Grasses', hint: 'Vic' },
    { word: 'Blaumut', hint: 'Indie català' },
    { word: 'Doctor Prats', hint: 'Mestissatge festiu' },
  ],
  en: [
    { word: 'Guitar', hint: 'Six strings' },
    { word: 'Piano', hint: 'Keys' },
    { word: 'Violin', hint: 'Bow' },
    { word: 'Drums', hint: 'Rhythm' },
    { word: 'Flute', hint: 'Woodwind' },
    { word: 'Trumpet', hint: 'Brass' },
    { word: 'Saxophone', hint: 'Jazz horn' },
    { word: 'Cello', hint: 'Low strings' },
    { word: 'Clarinet', hint: 'Single reed' },
    { word: 'Harp', hint: 'Plucked strings' },
    { word: 'Trombone', hint: 'Slide' },
    { word: 'Rock', hint: 'Electric guitars' },
    { word: 'Jazz', hint: 'Improvisation' },
    { word: 'Pop', hint: 'Charts' },
    { word: 'Blues', hint: 'Mississippi' },
    { word: 'Reggae', hint: 'Jamaica' },
    { word: 'Country', hint: 'Nashville' },
    { word: 'Techno', hint: 'Electronic beats' },
    { word: 'Opera', hint: 'Lyric voice' },
    { word: 'Hip hop', hint: 'Rap' },
    { word: 'Choir', hint: 'Group of voices' },
    { word: 'Orchestra', hint: 'Many players' },
    { word: 'The Beatles', hint: 'Liverpool four' },
    { word: 'Queen', hint: 'Freddie Mercury' },
    { word: 'Bob Dylan', hint: 'Folk legend' },
    { word: 'David Bowie', hint: 'Ziggy Stardust' },
    { word: 'Pink Floyd', hint: 'The Wall' },
    { word: 'Michael Jackson', hint: 'King of pop' },
    { word: 'Beyoncé', hint: 'Former Destiny’s Child' },
    { word: 'Radiohead', hint: 'Oxford band' },
    { word: 'Amy Winehouse', hint: 'Soul singer' },
  ],
  es: [
    { word: 'Guitarra', hint: 'Seis cuerdas' },
    { word: 'Piano', hint: 'Teclas' },
    { word: 'Violín', hint: 'Arco' },
    { word: 'Batería', hint: 'Ritmo' },
    { word: 'Flauta', hint: 'Viento' },
    { word: 'Trompeta', hint: 'Metal' },
    { word: 'Saxofón', hint: 'Jazz' },
    { word: 'Acordeón', hint: 'Fuelle' },
    { word: 'Clarinete', hint: 'Lengüeta' },
    { word: 'Violonchelo', hint: 'Cuerda grave' },
    { word: 'Arpa', hint: 'Cuerdas pulsadas' },
    { word: 'Rock', hint: 'Guitarras eléctricas' },
    { word: 'Jazz', hint: 'Improvisación' },
    { word: 'Pop', hint: 'Listas de éxitos' },
    { word: 'Flamenco', hint: 'Andalucía' },
    { word: 'Reguetón', hint: 'Perreo' },
    { word: 'Salsa', hint: 'Baile latino' },
    { word: 'Bolero', hint: 'Romántico' },
    { word: 'Copla', hint: 'Canción española' },
    { word: 'Tango', hint: 'Argentina' },
    { word: 'Coro', hint: 'Voces juntas' },
    { word: 'Orquesta', hint: 'Muchos músicos' },
    { word: 'Rosalía', hint: 'Flamenco pop' },
    { word: 'Joaquín Sabina', hint: 'Cantautor' },
    { word: 'Paco de Lucía', hint: 'Guitarra flamenca' },
    { word: 'Camarón', hint: 'Cante jondo' },
    { word: 'Mecano', hint: 'Pop ochentero' },
    { word: 'Estopa', hint: 'Hermanos rumberos' },
    { word: 'Alejandro Sanz', hint: 'Baladas' },
    { word: 'Bad Bunny', hint: 'Trap latino' },
    { word: 'C. Tangana', hint: 'El Madrileño' },
  ],
  eu: [
    { word: 'Gitarra', hint: 'Sei sokak' },
    { word: 'Pianoa', hint: 'Teklak' },
    { word: 'Biolina', hint: 'Arkua' },
    { word: 'Bateria', hint: 'Erritmoa' },
    { word: 'Txirula', hint: 'Haizea' },
    { word: 'Tronpeta', hint: 'Metala' },
    { word: 'Saxofoia', hint: 'Jazza' },
    { word: 'Trikitixa', hint: 'Eskusoinua' },
    { word: 'Alboka', hint: 'Adarra' },
    { word: 'Txalaparta', hint: 'Bi makil' },
    { word: 'Klarinetea', hint: 'Mihia' },
    { word: 'Biolontxeloa', hint: 'Soka larria' },
    { word: 'Rocka', hint: 'Gitarra elektrikoak' },
    { word: 'Jazza', hint: 'Inprobisazioa' },
    { word: 'Popa', hint: 'Arrakasta zerrendak' },
    { word: 'Punka', hint: 'Azkar eta gordin' },
    { word: 'Reggaea', hint: 'Jamaika' },
    { word: 'Bertsoa', hint: 'Inprobisatua' },
    { word: 'Abesbatza', hint: 'Ahots taldea' },
    { word: 'Orkestra', hint: 'Musikari asko' },
    { word: 'Ken Zazpi', hint: 'Euskal rocka' },
    { word: 'Berri Txarrak', hint: 'Lekunberri' },
    { word: 'Mikel Laboa', hint: 'Txoria txori' },
    { word: 'Benito Lertxundi', hint: 'Kantautorea' },
    { word: 'Su Ta Gar', hint: 'Heavy euskalduna' },
    { word: 'Gatibu', hint: 'Gernika' },
    { word: 'Itoiz', hint: 'Lasa anaiak' },
    { word: 'Kortatu', hint: 'Negu Gorriak aurretik' },
    { word: 'Oskorri', hint: 'Folk taldea' },
    { word: 'Esne Beltza', hint: 'Festa giroa' },
    { word: 'Zea Mays', hint: 'Aiora Renteria' },
  ],
  gl: [
    { word: 'Guitarra', hint: 'Seis cordas' },
    { word: 'Piano', hint: 'Teclas' },
    { word: 'Violín', hint: 'Arco' },
    { word: 'Batería', hint: 'Ritmo' },
    { word: 'Frauta', hint: 'Vento' },
    { word: 'Trompeta', hint: 'Metal' },
    { word: 'Saxofón', hint: 'Jazz' },
    { word: 'Gaita', hint: 'Fol' },
    { word: 'Pandeireta', hint: 'Percusión tradicional' },
    { word: 'Zanfona', hint: 'Manivela' },
    { word: 'Clarinete', hint: 'Lingüeta' },
    { word: 'Violonchelo', hint: 'Corda grave' },
    { word: 'Arpa', hint: 'Cordas pulsadas' },
    { word: 'Rock', hint: 'Guitarras eléctricas' },
    { word: 'Jazz', hint: 'Improvisación' },
    { word: 'Pop', hint: 'Listas de éxitos' },
    { word: 'Punk', hint: 'Rápido e cru' },
    { word: 'Reggae', hint: 'Xamaica' },
    { word: 'Muiñeira', hint: 'Baile galego' },
    { word: 'Coro', hint: 'Voces xuntas' },
    { word: 'Orquestra', hint: 'Moitos músicos' },
    { word: 'Luar na Lubre', hint: 'Folk galego' },
    { word: 'Carlos Núñez', hint: 'Gaiteiro' },
    { word: 'Milladoiro', hint: 'Música celta' },
    { word: 'Cristina Pato', hint: 'Gaita virtuosa' },
    { word: 'Mercedes Peón', hint: 'Tradición experimental' },
    { word: 'Susana Seivane', hint: 'Familia gaiteira' },
    { word: 'Siniestro Total', hint: 'Vigo punk' },
    { word: 'Tanxugueiras', hint: 'Tres pandereteiras' },
    { word: 'Berrogüetto', hint: 'Folk de fusión' },
    { word: 'Sés', hint: 'Cantautora coruñesa' },
  ],
  va: [
    { word: 'Guitarra', hint: 'Sis cordes' },
    { word: 'Piano', hint: 'Tecles' },
    { word: 'Violí', hint: 'Arquet' },
    { word: 'Bateria', hint: 'Ritme' },
    { word: 'Flauta', hint: 'Vent' },
    { word: 'Trompeta', hint: 'Metall' },
    { word: 'Saxofon', hint: 'Jazz' },
    { word: 'Dolçaina', hint: 'Festa valenciana' },
    { word: 'Tabal', hint: 'Acompanya la dolçaina' },
    { word: 'Clarinet', hint: 'Canya' },
    { word: 'Violoncel', hint: 'Corda greu' },
    { word: 'Contrabaix', hint: 'Greus' },
    { word: 'Arpa', hint: 'Cordes polsades' },
    { word: 'Rock', hint: 'Guitarres elèctriques' },
    { word: 'Jazz', hint: 'Improvisació' },
    { word: 'Pop', hint: 'Llistes d’èxits' },
    { word: 'Reggae', hint: 'Jamaica' },
    { word: 'Salsa', hint: 'Ball llatí' },
    { word: 'Pasdoble', hint: 'Banda i bous' },
    { word: 'Cor', hint: 'Veus juntes' },
    { word: 'Orquestra', hint: 'Molts músics' },
    { word: 'Obrint Pas', hint: 'Ska valencià' },
    { word: 'La Gossa Sorda', hint: 'Pego' },
    { word: 'Aspencat', hint: 'Mestissatge valencià' },
    { word: 'Zoo', hint: 'Panxampla' },
    { word: 'Feliu Ventura', hint: 'Cantautor' },
    { word: 'El Diluvi', hint: 'Folk reivindicatiu' },
    { word: 'Auxili', hint: 'Rap valencià' },
    { word: 'Pep Gimeno Botifarra', hint: 'Cant d’estil' },
    { word: 'Senyor Mostaza', hint: 'Reggae i ska' },
    { word: 'Tardor', hint: 'Indie valencià' },
  ],
}
