import type { WordEntry } from '../../domain/content/types'
import type { LocaleCode } from '../../domain/game/types'

export const music: Partial<Record<LocaleCode, WordEntry[]>> = {
  ca: [
    { word: 'Guitarra', hints: ['Sis cordes', 'Rasgueig', 'Trastos'] },
    { word: 'Piano', hints: ['Tecles', 'Blanc i negre', 'Cua'] },
    { word: 'Violí', hints: ['Arquet', 'Quatre cordes', 'Barbada'] },
    { word: 'Bateria', hints: ['Ritme', 'Baquetes', 'Plats'] },
    { word: 'Flauta', hints: ['Vent', 'Travessera', 'Forats'] },
    { word: 'Trompeta', hints: ['Metall', 'Pistons', 'Sordina'] },
    { word: 'Saxofon', hints: ['Jazz', 'Llautó corbat', 'Canya'] },
    { word: 'Acordió', hints: ['Manxa', 'Botons', 'Aire'] },
    { word: 'Clarinet', hints: ['Canya', 'Vent fusta', 'Negre'] },
    { word: 'Contrabaix', hints: ['Greus', 'Quatre cordes', 'Dempeus'] },
    { word: 'Tenora', hints: ['Cobla', 'Doble canya', 'Sardanes'] },
    { word: 'Rock', hints: ['Guitarres elèctriques', 'Bateria forta', 'Rebel·lia'] },
    { word: 'Jazz', hints: ['Improvisació', 'Nova Orleans', 'Swing'] },
    { word: 'Pop', hints: ['Llistes d’èxits', 'Comercial', 'Tornada enganxosa'] },
    { word: 'Flamenc', hints: ['Andalusia', 'Taconeig', 'Cante jondo'] },
    { word: 'Reggae', hints: ['Jamaica', 'Bob Marley', 'Ritme lent'] },
    { word: 'Salsa', hints: ['Ball llatí', 'Carib', 'Percussió'] },
    { word: 'Tango', hints: ['Argentina', 'Bandoneó', 'Parella'] },
    { word: 'Òpera', hints: ['Veu lírica', 'Escenari', 'Ària'] },
    { word: 'Rumba catalana', hints: ['Peret', 'Ventilador', 'Gràcia'] },
    { word: 'Sardana', hints: ['Dansa en rotllana', 'Cobla', 'Mans agafades'] },
    { word: 'Cor', hints: ['Veus juntes', 'Cantar en grup', 'Director'] },
    { word: 'Orquestra', hints: ['Molts músics', 'Simfònica', 'Batuta'] },
    { word: 'Manel', hints: ['Pop català', 'Barcelona', 'Indie'] },
    { word: 'Txarango', hints: ['Festa mestissa', 'Directes massius', 'Catalunya'] },
    { word: 'Els Pets', hints: ['Constantí', 'Rock català', 'Lluís Gavaldà'] },
    { word: 'Sopa de Cabra', hints: ['Rock gironí', 'Girona', 'Anys 90'] },
    { word: 'Antònia Font', hints: ['Mallorca', 'Pop oníric', 'Illes'] },
    { word: 'Oques Grasses', hints: ['Vic', 'Festes majors', 'Pop festiu'] },
    { word: 'Blaumut', hints: ['Indie català', 'Pop delicat', 'El turista'] },
    { word: 'Doctor Prats', hints: ['Mestissatge festiu', 'Terrassa', 'Vents'] },
  ],
  en: [
    { word: 'Guitar', hints: ['Six strings', 'Frets', 'Strumming'] },
    { word: 'Piano', hints: ['Keys', 'Black and white', 'Grand'] },
    { word: 'Violin', hints: ['Bow', 'Four strings', 'Chin rest'] },
    { word: 'Drums', hints: ['Rhythm', 'Sticks', 'Cymbals'] },
    { word: 'Flute', hints: ['Woodwind', 'Silver', 'Holes'] },
    { word: 'Trumpet', hints: ['Brass', 'Valves', 'Fanfare'] },
    { word: 'Saxophone', hints: ['Jazz horn', 'Reed', 'Curved metal'] },
    { word: 'Cello', hints: ['Low strings', 'Bowed', 'Seated player'] },
    { word: 'Clarinet', hints: ['Single reed', 'Woodwind', 'Black tube'] },
    { word: 'Harp', hints: ['Plucked strings', 'Tall frame', 'Angelic'] },
    { word: 'Trombone', hints: ['Slide', 'Brass', 'Low pitch'] },
    { word: 'Rock', hints: ['Electric guitars', 'Loud drums', 'Rebellion'] },
    { word: 'Jazz', hints: ['Improvisation', 'New Orleans', 'Swing'] },
    { word: 'Pop', hints: ['Charts', 'Catchy chorus', 'Mainstream'] },
    { word: 'Blues', hints: ['Mississippi', 'Twelve bars', 'Sorrowful'] },
    { word: 'Reggae', hints: ['Jamaica', 'Bob Marley', 'Offbeat'] },
    { word: 'Country', hints: ['Nashville', 'Cowboy', 'Banjo'] },
    { word: 'Techno', hints: ['Electronic beats', 'Synthesizer', 'Nightclub'] },
    { word: 'Opera', hints: ['Lyric voice', 'Stage drama', 'Aria'] },
    { word: 'Hip hop', hints: ['Rap', 'Beats', 'Street culture'] },
    { word: 'Choir', hints: ['Group of voices', 'Harmony', 'Conductor'] },
    { word: 'Orchestra', hints: ['Many players', 'Symphony', 'Baton'] },
    { word: 'The Beatles', hints: ['Liverpool four', 'Abbey Road', 'Lennon McCartney'] },
    { word: 'Queen', hints: ['Freddie Mercury', 'Bohemian Rhapsody', 'Stadium rock'] },
    { word: 'Bob Dylan', hints: ['Folk legend', 'Harmonica', 'Nobel laureate'] },
    { word: 'David Bowie', hints: ['Ziggy Stardust', 'Chameleon', 'Heroes'] },
    { word: 'Pink Floyd', hints: ['The Wall', 'Dark Side', 'Progressive'] },
    { word: 'Michael Jackson', hints: ['King of pop', 'Moonwalk', 'Thriller'] },
    { word: 'Beyoncé', hints: ['Former Destiny’s Child', 'Single Ladies', 'Queen Bey'] },
    { word: 'Radiohead', hints: ['Oxford band', 'Creep', 'Thom Yorke'] },
    { word: 'Amy Winehouse', hints: ['Soul singer', 'Beehive hair', 'Rehab'] },
  ],
  es: [
    { word: 'Guitarra', hints: ['Seis cuerdas', 'Trastes', 'Rasgueo'] },
    { word: 'Piano', hints: ['Teclas', 'Blanco y negro', 'De cola'] },
    { word: 'Violín', hints: ['Arco', 'Cuatro cuerdas', 'Mentonera'] },
    { word: 'Batería', hints: ['Ritmo', 'Baquetas', 'Platillos'] },
    { word: 'Flauta', hints: ['Viento', 'Travesera', 'Agujeros'] },
    { word: 'Trompeta', hints: ['Metal', 'Pistones', 'Fanfarria'] },
    { word: 'Saxofón', hints: ['Jazz', 'Latón curvo', 'Caña'] },
    { word: 'Acordeón', hints: ['Fuelle', 'Botones', 'Aire'] },
    { word: 'Clarinete', hints: ['Lengüeta', 'Viento madera', 'Tubo negro'] },
    { word: 'Violonchelo', hints: ['Cuerda grave', 'Arco', 'Sentado'] },
    { word: 'Arpa', hints: ['Cuerdas pulsadas', 'Marco alto', 'Angelical'] },
    { word: 'Rock', hints: ['Guitarras eléctricas', 'Batería fuerte', 'Rebeldía'] },
    { word: 'Jazz', hints: ['Improvisación', 'Nueva Orleans', 'Swing'] },
    { word: 'Pop', hints: ['Listas de éxitos', 'Estribillo pegadizo', 'Comercial'] },
    { word: 'Flamenco', hints: ['Andalucía', 'Taconeo', 'Cante jondo'] },
    { word: 'Reguetón', hints: ['Perreo', 'Dembow', 'Puerto Rico'] },
    { word: 'Salsa', hints: ['Baile latino', 'Caribe', 'Percusión'] },
    { word: 'Bolero', hints: ['Romántico', 'Letras de amor', 'Lento'] },
    { word: 'Copla', hints: ['Canción española', 'Andalucía', 'Tradicional'] },
    { word: 'Tango', hints: ['Argentina', 'Bandoneón', 'Pareja'] },
    { word: 'Coro', hints: ['Voces juntas', 'Armonía', 'Director'] },
    { word: 'Orquesta', hints: ['Muchos músicos', 'Sinfónica', 'Batuta'] },
    { word: 'Rosalía', hints: ['Flamenco pop', 'Motomami', 'Catalana'] },
    { word: 'Joaquín Sabina', hints: ['Cantautor', 'Úbeda', 'Voz rota'] },
    { word: 'Paco de Lucía', hints: ['Guitarra flamenca', 'Algeciras', 'Virtuoso'] },
    { word: 'Camarón', hints: ['Cante jondo', 'La Isla', 'Leyenda gitana'] },
    { word: 'Mecano', hints: ['Pop ochentero', 'Hijo de la luna', 'Hermanos Cano'] },
    { word: 'Estopa', hints: ['Hermanos rumberos', 'Cornellà', 'Rumba rock'] },
    { word: 'Alejandro Sanz', hints: ['Baladas', 'Corazón partío', 'Madrileño'] },
    { word: 'Bad Bunny', hints: ['Trap latino', 'Puerto Rico', 'Conejo malo'] },
    { word: 'C. Tangana', hints: ['El Madrileño', 'Pucho', 'Tinta'] },
  ],
  eu: [
    { word: 'Gitarra', hints: ['Sei sokak', 'Trasteak', 'Akordeak'] },
    { word: 'Pianoa', hints: ['Teklak', 'Zuri-beltza', 'Buztanduna'] },
    { word: 'Biolina', hints: ['Arkua', 'Lau soka', 'Kokotsa'] },
    { word: 'Bateria', hints: ['Erritmoa', 'Makilak', 'Platerak'] },
    { word: 'Txirula', hints: ['Haizea', 'Zuloak', 'Esku bat'] },
    { word: 'Tronpeta', hints: ['Metala', 'Pistoiak', 'Haize tresna'] },
    { word: 'Saxofoia', hints: ['Jazza', 'Letoi okertua', 'Mihia'] },
    { word: 'Trikitixa', hints: ['Eskusoinua', 'Botoiak', 'Erromeria'] },
    { word: 'Alboka', hints: ['Adarra', 'Haize tresna', 'Tradizionala'] },
    { word: 'Txalaparta', hints: ['Bi makil', 'Egurra', 'Bikoteka'] },
    { word: 'Klarinetea', hints: ['Mihia', 'Haize egurra', 'Tutu beltza'] },
    { word: 'Biolontxeloa', hints: ['Soka larria', 'Arkua', 'Eserita'] },
    { word: 'Rocka', hints: ['Gitarra elektrikoak', 'Bateria gogorra', 'Errebeldia'] },
    { word: 'Jazza', hints: ['Inprobisazioa', 'New Orleans', 'Swinga'] },
    { word: 'Popa', hints: ['Arrakasta zerrendak', 'Errepika erraza', 'Komertziala'] },
    { word: 'Punka', hints: ['Azkar eta gordin', 'Errebeldia', 'Gitarra zaratatsuak'] },
    { word: 'Reggaea', hints: ['Jamaika', 'Bob Marley', 'Erritmo geldoa'] },
    { word: 'Bertsoa', hints: ['Inprobisatua', 'Doinua', 'Plazan'] },
    { word: 'Abesbatza', hints: ['Ahots taldea', 'Harmonia', 'Zuzendaria'] },
    { word: 'Orkestra', hints: ['Musikari asko', 'Sinfonikoa', 'Batuta'] },
    { word: 'Ken Zazpi', hints: ['Euskal rocka', 'Berriz', 'Jon Mikel Saez'] },
    { word: 'Berri Txarrak', hints: ['Lekunberri', 'Gorka Urbizu', 'Hiru kide'] },
    { word: 'Mikel Laboa', hints: ['Txoria txori', 'Donostia', 'Lekeitio'] },
    { word: 'Benito Lertxundi', hints: ['Kantautorea', 'Orio', 'Folk zaharra'] },
    { word: 'Su Ta Gar', hints: ['Heavy euskalduna', 'Eibar', 'Metala'] },
    { word: 'Gatibu', hints: ['Gernika', 'Alex Sardui', 'Rocka'] },
    { word: 'Itoiz', hints: ['Lasa anaiak', 'Lekeitio', 'Pop poetikoa'] },
    { word: 'Kortatu', hints: ['Negu Gorriak aurretik', 'Irun', 'Ska'] },
    { word: 'Oskorri', hints: ['Folk taldea', 'Bilbo', 'Tradizioa'] },
    { word: 'Esne Beltza', hints: ['Festa giroa', 'Mestizajea', 'Nafarroa'] },
    { word: 'Zea Mays', hints: ['Aiora Renteria', 'Bilbo', 'Rock leuna'] },
  ],
  gl: [
    { word: 'Guitarra', hints: ['Seis cordas', 'Trastes', 'Rasgueo'] },
    { word: 'Piano', hints: ['Teclas', 'Branco e negro', 'De cola'] },
    { word: 'Violín', hints: ['Arco', 'Catro cordas', 'Queixeira'] },
    { word: 'Batería', hints: ['Ritmo', 'Baquetas', 'Pratos'] },
    { word: 'Frauta', hints: ['Vento', 'Furados', 'Soprar'] },
    { word: 'Trompeta', hints: ['Metal', 'Pistóns', 'Fanfarria'] },
    { word: 'Saxofón', hints: ['Jazz', 'Latón curvo', 'Cana'] },
    { word: 'Gaita', hints: ['Fol', 'Galega', 'Soprete'] },
    { word: 'Pandeireta', hints: ['Percusión tradicional', 'Sonaxas', 'Cantareiras'] },
    { word: 'Zanfona', hints: ['Manivela', 'Roda', 'Medieval'] },
    { word: 'Clarinete', hints: ['Lingüeta', 'Vento madeira', 'Tubo negro'] },
    { word: 'Violonchelo', hints: ['Corda grave', 'Arco', 'Sentado'] },
    { word: 'Arpa', hints: ['Cordas pulsadas', 'Marco alto', 'Anxelical'] },
    { word: 'Rock', hints: ['Guitarras eléctricas', 'Batería forte', 'Rebeldía'] },
    { word: 'Jazz', hints: ['Improvisación', 'Nova Orleans', 'Swing'] },
    { word: 'Pop', hints: ['Listas de éxitos', 'Retrouso pegañento', 'Comercial'] },
    { word: 'Punk', hints: ['Rápido e cru', 'Rebeldía', 'Guitarras ruidosas'] },
    { word: 'Reggae', hints: ['Xamaica', 'Bob Marley', 'Ritmo lento'] },
    { word: 'Muiñeira', hints: ['Baile galego', 'Compás ternario', 'Gaita'] },
    { word: 'Coro', hints: ['Voces xuntas', 'Harmonía', 'Director'] },
    { word: 'Orquestra', hints: ['Moitos músicos', 'Sinfónica', 'Batuta'] },
    { word: 'Luar na Lubre', hints: ['Folk galego', 'Celta', 'A Coruña'] },
    { word: 'Carlos Núñez', hints: ['Gaiteiro', 'Vigo', 'Virtuoso'] },
    { word: 'Milladoiro', hints: ['Música celta', 'Folk veterano', 'Santiago'] },
    { word: 'Cristina Pato', hints: ['Gaita virtuosa', 'Ourense', 'Fusión'] },
    { word: 'Mercedes Peón', hints: ['Tradición experimental', 'Voz potente', 'Coruñesa'] },
    { word: 'Susana Seivane', hints: ['Familia gaiteira', 'Cambados', 'Tradición'] },
    { word: 'Siniestro Total', hints: ['Vigo punk', 'Humor', 'Anos 80'] },
    { word: 'Tanxugueiras', hints: ['Tres pandereteiras', 'Terra', 'Benidorm Fest'] },
    { word: 'Berrogüetto', hints: ['Folk de fusión', 'Instrumental', 'Tradición renovada'] },
    { word: 'Sés', hints: ['Cantautora coruñesa', 'Voz crúa', 'Compromiso social'] },
  ],
  va: [
    { word: 'Guitarra', hints: ['Sis cordes', 'Trastos', 'Rasgueig'] },
    { word: 'Piano', hints: ['Tecles', 'Blanc i negre', 'De cua'] },
    { word: 'Violí', hints: ['Arquet', 'Quatre cordes', 'Barbada'] },
    { word: 'Bateria', hints: ['Ritme', 'Baquetes', 'Plats'] },
    { word: 'Flauta', hints: ['Vent', 'Travessera', 'Forats'] },
    { word: 'Trompeta', hints: ['Metall', 'Pistons', 'Banda'] },
    { word: 'Saxofon', hints: ['Jazz', 'Llautó corbat', 'Canya'] },
    { word: 'Dolçaina', hints: ['Festa valenciana', 'Tabal', 'Vent tradicional'] },
    { word: 'Tabal', hints: ['Acompanya la dolçaina', 'Percussió', 'Festa de carrer'] },
    { word: 'Clarinet', hints: ['Canya', 'Vent fusta', 'Tub negre'] },
    { word: 'Violoncel', hints: ['Corda greu', 'Arquet', 'Assegut'] },
    { word: 'Contrabaix', hints: ['Greus', 'Quatre cordes', 'Dempeus'] },
    { word: 'Arpa', hints: ['Cordes polsades', 'Marc alt', 'Angelical'] },
    { word: 'Rock', hints: ['Guitarres elèctriques', 'Bateria forta', 'Rebel·lia'] },
    { word: 'Jazz', hints: ['Improvisació', 'Nova Orleans', 'Swing'] },
    { word: 'Pop', hints: ['Llistes d’èxits', 'Tornada enganxosa', 'Comercial'] },
    { word: 'Reggae', hints: ['Jamaica', 'Bob Marley', 'Ritme lent'] },
    { word: 'Salsa', hints: ['Ball llatí', 'Carib', 'Percussió'] },
    { word: 'Pasdoble', hints: ['Banda i bous', 'Festa de poble', 'Marxa'] },
    { word: 'Cor', hints: ['Veus juntes', 'Harmonia', 'Director'] },
    { word: 'Orquestra', hints: ['Molts músics', 'Simfònica', 'Batuta'] },
    { word: 'Obrint Pas', hints: ['Ska valencià', 'Dolçaina i guitarres', 'València'] },
    { word: 'La Gossa Sorda', hints: ['Pego', 'Mestissatge', 'Marina Alta'] },
    { word: 'Aspencat', hints: ['Mestissatge valencià', 'Festiu', 'Reivindicatiu'] },
    { word: 'Zoo', hints: ['Panxampla', 'Gandia', 'Rap mestís'] },
    { word: 'Feliu Ventura', hints: ['Cantautor', 'Xàtiva', 'Cançó d’autor'] },
    { word: 'El Diluvi', hints: ['Folk reivindicatiu', 'L’Alcúdia', 'Arrels'] },
    { word: 'Auxili', hints: ['Rap valencià', 'Hip hop', 'Reivindicació'] },
    { word: 'Pep Gimeno Botifarra', hints: ['Cant d’estil', 'Tradicional', 'Xàtiva'] },
    { word: 'Senyor Mostaza', hints: ['Reggae i ska', 'Festiu', 'Vents'] },
    { word: 'Tardor', hints: ['Indie valencià', 'Pop melancòlic', 'Guitarres'] },
  ],
}
