import type { WordEntry } from '../../domain/content/types'
import type { LocaleCode } from '../../domain/game/types'

export const nature: Partial<Record<LocaleCode, WordEntry[]>> = {
  ca: [
    { word: 'Riu', hints: ['Aigua', 'Corrent', 'Cabal'] },
    { word: 'Muntanya', hints: ['Altura', 'Cim', 'Pendent'] },
    { word: 'Volcà', hints: ['Lava', 'Erupció', 'Cràter'] },
    { word: 'Llamp', hints: ['Tempesta', 'Elèctric', 'Cel'] },
    { word: 'Arc de Sant Martí', hints: ['Colors', 'Pluja', 'Cel'] },
    { word: 'Bosc', hints: ['Arbres', 'Verd', 'Fulles'] },
    { word: 'Desert', hints: ['Sorra seca', 'Calor', 'Àrid'] },
    { word: 'Cascada', hints: ['Salt', 'Aigua', 'Riu'] },
    { word: 'Estrella', hints: ['Nit', 'Brillant', 'Cel'] },
    { word: 'Boira', hints: ['Poca visibilitat', 'Grisa', 'Humitat'] },
    { word: 'Mar', hints: ['Salat', 'Onades', 'Blau'] },
    { word: 'Núvol', hints: ['Cel', 'Blanc', 'Pluja'] },
    { word: 'Neu', hints: ['Fred blanc', 'Hivern', 'Flocs'] },
    { word: 'Glacera', hints: ['Gel enorme', 'Fred', 'Muntanya'] },
    { word: 'Illa', hints: ['Envoltada', 'Mar', 'Terra'] },
    { word: 'Llac', hints: ['Aigua quieta', 'Dolç', 'Profund'] },
    { word: 'Cova', hints: ['Subterrani', 'Fosca', 'Roca'] },
    { word: 'Roca', hints: ['Dura', 'Pedra', 'Mineral'] },
    { word: 'Vent', hints: ['Aire mòbil', 'Brisa', 'Fort'] },
    { word: 'Pluja', hints: ['Gotes', 'Mullat', 'Núvol'] },
    { word: 'Sol', hints: ['Llum diürna', 'Calor', 'Groc'] },
    { word: 'Lluna', hints: ['Satèl·lit', 'Nit', 'Plena'] },
    { word: 'Cometa', hints: ['Cua brillant', 'Espai', 'Gel'] },
    { word: 'Tornado', hints: ['Remolí', 'Vent', 'Destrucció'] },
    { word: 'Terratrèmol', hints: ['Tremolor', 'Sòl', 'Sisme'] },
    { word: 'Selva', hints: ['Tròpic humit', 'Densa', 'Animals'] },
    { word: 'Praderia', hints: ['Herba plana', 'Verda', 'Camp'] },
    { word: 'Penya-segat', hints: ['Vora abrupta', 'Altura', 'Mar'] },
    { word: 'Flor', hints: ['Pètals', 'Perfum', 'Color'] },
    { word: 'Tempesta', hints: ['Trons', 'Pluja', 'Vent'] },
  ],
  en: [
    { word: 'River', hints: ['Water', 'Flowing', 'Current'] },
    { word: 'Mountain', hints: ['Height', 'Peak', 'Climb'] },
    { word: 'Volcano', hints: ['Lava', 'Eruption', 'Crater'] },
    { word: 'Lightning', hints: ['Storm', 'Electric', 'Flash'] },
    { word: 'Rainbow', hints: ['Colors', 'Arc', 'Sky'] },
    { word: 'Forest', hints: ['Trees', 'Green', 'Leaves'] },
    { word: 'Desert', hints: ['Dry sand', 'Hot', 'Arid'] },
    { word: 'Waterfall', hints: ['Drop', 'River', 'Cascade'] },
    { word: 'Star', hints: ['Night sky', 'Bright', 'Twinkle'] },
    { word: 'Fog', hints: ['Low visibility', 'Grey', 'Mist'] },
    { word: 'Sea', hints: ['Salty', 'Waves', 'Blue'] },
    { word: 'Cloud', hints: ['Sky', 'White', 'Rain'] },
    { word: 'Snow', hints: ['White cold', 'Winter', 'Flakes'] },
    { word: 'Glacier', hints: ['Huge ice', 'Cold', 'Mountain'] },
    { word: 'Island', hints: ['Surrounded', 'Sea', 'Shore'] },
    { word: 'Lake', hints: ['Still water', 'Fresh', 'Deep'] },
    { word: 'Cave', hints: ['Underground', 'Dark', 'Rock'] },
    { word: 'Rock', hints: ['Hard', 'Stone', 'Mineral'] },
    { word: 'Wind', hints: ['Moving air', 'Breeze', 'Gust'] },
    { word: 'Rain', hints: ['Drops', 'Wet', 'Cloud'] },
    { word: 'Sun', hints: ['Daylight', 'Heat', 'Yellow'] },
    { word: 'Moon', hints: ['Satellite', 'Night', 'Full'] },
    { word: 'Comet', hints: ['Bright tail', 'Space', 'Ice'] },
    { word: 'Tornado', hints: ['Whirl', 'Wind', 'Funnel'] },
    { word: 'Earthquake', hints: ['Shaking', 'Ground', 'Seismic'] },
    { word: 'Jungle', hints: ['Humid tropic', 'Dense', 'Animals'] },
    { word: 'Meadow', hints: ['Flat grass', 'Green', 'Field'] },
    { word: 'Cliff', hints: ['Steep edge', 'Height', 'Sea'] },
    { word: 'Flower', hints: ['Petals', 'Scent', 'Color'] },
    { word: 'Storm', hints: ['Thunder', 'Rain', 'Wind'] },
  ],
  es: [
    { word: 'Río', hints: ['Agua', 'Corriente', 'Caudal'] },
    { word: 'Montaña', hints: ['Altura', 'Cima', 'Pendiente'] },
    { word: 'Volcán', hints: ['Lava', 'Erupción', 'Cráter'] },
    { word: 'Relámpago', hints: ['Tormenta', 'Eléctrico', 'Destello'] },
    { word: 'Arcoíris', hints: ['Colores', 'Lluvia', 'Cielo'] },
    { word: 'Bosque', hints: ['Árboles', 'Verde', 'Hojas'] },
    { word: 'Desierto', hints: ['Arena seca', 'Calor', 'Árido'] },
    { word: 'Cascada', hints: ['Salto', 'Agua', 'Río'] },
    { word: 'Estrella', hints: ['Cielo nocturno', 'Brillante', 'Punta'] },
    { word: 'Niebla', hints: ['Poca visibilidad', 'Gris', 'Humedad'] },
    { word: 'Mar', hints: ['Salado', 'Olas', 'Azul'] },
    { word: 'Nube', hints: ['Cielo', 'Blanca', 'Lluvia'] },
    { word: 'Nieve', hints: ['Frío blanco', 'Invierno', 'Copos'] },
    { word: 'Glaciar', hints: ['Hielo enorme', 'Frío', 'Montaña'] },
    { word: 'Isla', hints: ['Rodeada', 'Mar', 'Tierra'] },
    { word: 'Lago', hints: ['Agua quieta', 'Dulce', 'Profundo'] },
    { word: 'Cueva', hints: ['Subterráneo', 'Oscura', 'Roca'] },
    { word: 'Roca', hints: ['Dura', 'Piedra', 'Mineral'] },
    { word: 'Viento', hints: ['Aire en movimiento', 'Brisa', 'Ráfaga'] },
    { word: 'Lluvia', hints: ['Gotas', 'Mojado', 'Nube'] },
    { word: 'Sol', hints: ['Luz del día', 'Calor', 'Amarillo'] },
    { word: 'Luna', hints: ['Satélite', 'Noche', 'Llena'] },
    { word: 'Cometa', hints: ['Cola brillante', 'Espacio', 'Hielo'] },
    { word: 'Tornado', hints: ['Remolino', 'Viento', 'Embudo'] },
    { word: 'Terremoto', hints: ['Temblor', 'Suelo', 'Sismo'] },
    { word: 'Selva', hints: ['Trópico húmedo', 'Densa', 'Animales'] },
    { word: 'Pradera', hints: ['Hierba llana', 'Verde', 'Campo'] },
    { word: 'Acantilado', hints: ['Borde abrupto', 'Altura', 'Mar'] },
    { word: 'Flor', hints: ['Pétalos', 'Aroma', 'Color'] },
    { word: 'Tormenta', hints: ['Truenos', 'Lluvia', 'Viento'] },
  ],
  eu: [
    { word: 'Ibaia', hints: ['Ura', 'Korrontea', 'Emaria'] },
    { word: 'Mendia', hints: ['Altuera', 'Gailurra', 'Aldapa'] },
    { word: 'Sumendia', hints: ['Laba', 'Erupzioa', 'Kraterra'] },
    { word: 'Tximista', hints: ['Ekaitza', 'Elektrikoa', 'Distira'] },
    { word: 'Ostadarra', hints: ['Koloreak', 'Euria', 'Zerua'] },
    { word: 'Basoa', hints: ['Zuhaitzak', 'Berdea', 'Hostoak'] },
    { word: 'Basamortua', hints: ['Harea lehorra', 'Beroa', 'Idorra'] },
    { word: 'Ur-jauzia', hints: ['Erorketa', 'Ibaia', 'Salto'] },
    { word: 'Izarra', hints: ['Gaueko zerua', 'Distiratsua', 'Argia'] },
    { word: 'Lainoa', hints: ['Ikuspen txikia', 'Grisa', 'Hezetasuna'] },
    { word: 'Itsasoa', hints: ['Gazia', 'Olatuak', 'Urdina'] },
    { word: 'Hodeia', hints: ['Zerua', 'Zuria', 'Euria'] },
    { word: 'Elurra', hints: ['Hotz zuria', 'Negua', 'Malutak'] },
    { word: 'Glaziarra', hints: ['Izotz handia', 'Hotza', 'Mendia'] },
    { word: 'Uhartea', hints: ['Inguratua', 'Itsasoa', 'Lurra'] },
    { word: 'Aintzira', hints: ['Ur geldia', 'Geza', 'Sakona'] },
    { word: 'Haitzuloa', hints: ['Lurpean', 'Iluna', 'Harria'] },
    { word: 'Harkaitza', hints: ['Gogorra', 'Harria', 'Minerala'] },
    { word: 'Haizea', hints: ['Aire mugikorra', 'Brisa', 'Indartsua'] },
    { word: 'Euria', hints: ['Tantak', 'Bustia', 'Hodeia'] },
    { word: 'Eguzkia', hints: ['Eguneko argia', 'Beroa', 'Horia'] },
    { word: 'Ilargia', hints: ['Satelitea', 'Gaua', 'Betea'] },
    { word: 'Kometa', hints: ['Isats distiratsua', 'Espazioa', 'Izotza'] },
    { word: 'Tornadoa', hints: ['Zurrunbiloa', 'Haizea', 'Inbutua'] },
    { word: 'Lurrikara', hints: ['Dardara', 'Lurra', 'Sismoa'] },
    { word: 'Oihana', hints: ['Tropiko hezea', 'Trinkoa', 'Animaliak'] },
    { word: 'Larrea', hints: ['Belar laua', 'Berdea', 'Zelaia'] },
    { word: 'Itsaslabarra', hints: ['Ertz malkartsua', 'Altuera', 'Kosta'] },
    { word: 'Lorea', hints: ['Petaloak', 'Usaina', 'Margoa'] },
    { word: 'Ekaitza', hints: ['Trumoiak', 'Euria', 'Haizea'] },
  ],
  gl: [
    { word: 'Río', hints: ['Auga', 'Corrente', 'Caudal'] },
    { word: 'Montaña', hints: ['Altura', 'Cima', 'Pendente'] },
    { word: 'Volcán', hints: ['Lava', 'Erupción', 'Cráter'] },
    { word: 'Lóstrego', hints: ['Tormenta', 'Eléctrico', 'Resplandor'] },
    { word: 'Arco da vella', hints: ['Cores', 'Choiva', 'Ceo'] },
    { word: 'Bosque', hints: ['Árbores', 'Verde', 'Follas'] },
    { word: 'Deserto', hints: ['Area seca', 'Calor', 'Árido'] },
    { word: 'Fervenza', hints: ['Salto', 'Auga', 'Río'] },
    { word: 'Estrela', hints: ['Ceo nocturno', 'Brillante', 'Luz'] },
    { word: 'Néboa', hints: ['Pouca visibilidade', 'Gris', 'Humidade'] },
    { word: 'Mar', hints: ['Salgado', 'Ondas', 'Azul'] },
    { word: 'Nube', hints: ['Ceo', 'Branca', 'Choiva'] },
    { word: 'Neve', hints: ['Frío branco', 'Inverno', 'Folerpas'] },
    { word: 'Glaciar', hints: ['Xeo enorme', 'Frío', 'Montaña'] },
    { word: 'Illa', hints: ['Rodeada', 'Mar', 'Terra'] },
    { word: 'Lago', hints: ['Auga quieta', 'Doce', 'Profundo'] },
    { word: 'Cova', hints: ['Subterráneo', 'Escura', 'Rocha'] },
    { word: 'Rocha', hints: ['Dura', 'Pedra', 'Mineral'] },
    { word: 'Vento', hints: ['Aire en movemento', 'Brisa', 'Refacho'] },
    { word: 'Choiva', hints: ['Pingas', 'Mollado', 'Nube'] },
    { word: 'Sol', hints: ['Luz do día', 'Calor', 'Amarelo'] },
    { word: 'Lúa', hints: ['Satélite', 'Noite', 'Chea'] },
    { word: 'Cometa', hints: ['Cola brillante', 'Espazo', 'Xeo'] },
    { word: 'Tornado', hints: ['Remuíño', 'Vento', 'Funil'] },
    { word: 'Terremoto', hints: ['Tremor', 'Chan', 'Sismo'] },
    { word: 'Selva', hints: ['Trópico húmido', 'Densa', 'Animais'] },
    { word: 'Pradería', hints: ['Herba chá', 'Verde', 'Campo'] },
    { word: 'Cantil', hints: ['Bordo abrupto', 'Altura', 'Mar'] },
    { word: 'Flor', hints: ['Pétalos', 'Aroma', 'Cor'] },
    { word: 'Tormenta', hints: ['Tronos', 'Choiva', 'Vento'] },
  ],
  va: [
    { word: 'Riu', hints: ['Aigua', 'Corrent', 'Cabal'] },
    { word: 'Muntanya', hints: ['Altura', 'Cim', 'Pendent'] },
    { word: 'Volcà', hints: ['Lava', 'Erupció', 'Cràter'] },
    { word: 'Llamp', hints: ['Tempestat', 'Elèctric', 'Cel'] },
    { word: 'Arc de Sant Martí', hints: ['Colors', 'Pluja', 'Cel'] },
    { word: 'Bosc', hints: ['Arbres', 'Verd', 'Fulles'] },
    { word: 'Desert', hints: ['Arena seca', 'Calor', 'Àrid'] },
    { word: 'Cascada', hints: ['Bot', 'Aigua', 'Riu'] },
    { word: 'Estrela', hints: ['Nit', 'Brillant', 'Cel'] },
    { word: 'Boira', hints: ['Poca visibilitat', 'Grisa', 'Humitat'] },
    { word: 'Mar', hints: ['Salat', 'Onades', 'Blau'] },
    { word: 'Núvol', hints: ['Cel', 'Blanc', 'Pluja'] },
    { word: 'Neu', hints: ['Fred blanc', 'Hivern', 'Flocs'] },
    { word: 'Glacera', hints: ['Gel enorme', 'Fred', 'Muntanya'] },
    { word: 'Illa', hints: ['Envoltada', 'Mar', 'Terra'] },
    { word: 'Llac', hints: ['Aigua quieta', 'Dolç', 'Profund'] },
    { word: 'Cova', hints: ['Subterrani', 'Fosca', 'Roca'] },
    { word: 'Roca', hints: ['Dura', 'Pedra', 'Mineral'] },
    { word: 'Vent', hints: ['Aire en moviment', 'Brisa', 'Fort'] },
    { word: 'Pluja', hints: ['Gotes', 'Mullat', 'Núvol'] },
    { word: 'Sol', hints: ['Llum del dia', 'Calor', 'Groc'] },
    { word: 'Lluna', hints: ['Satèl·lit', 'Nit', 'Plena'] },
    { word: 'Cometa', hints: ['Cua brillant', 'Espai', 'Gel'] },
    { word: 'Tornado', hints: ['Remolí', 'Vent', 'Destrucció'] },
    { word: 'Terratrémol', hints: ['Tremolor', 'Sòl', 'Sisme'] },
    { word: 'Selva', hints: ['Tròpic humit', 'Densa', 'Animals'] },
    { word: 'Praderia', hints: ['Herba plana', 'Verda', 'Camp'] },
    { word: 'Penya-segat', hints: ['Vora abrupta', 'Altura', 'Mar'] },
    { word: 'Flor', hints: ['Pètals', 'Perfum', 'Color'] },
    { word: 'Tempestat', hints: ['Trons', 'Pluja', 'Vent'] },
  ],
}
