import type { WordEntry } from '../../domain/content/types'
import type { LocaleCode } from '../../domain/game/types'

export const nature: Partial<Record<LocaleCode, WordEntry[]>> = {
  ca: [
    { word: 'Riu', hint: 'Aigua' },
    { word: 'Muntanya', hint: 'Altura' },
    { word: 'Volcà', hint: 'Lava' },
    { word: 'Llamp', hint: 'Tempesta' },
    { word: 'Arc de Sant Martí', hint: 'Colors' },
    { word: 'Bosc', hint: 'Arbres' },
    { word: 'Desert', hint: 'Sorra seca' },
    { word: 'Cascada', hint: 'Salt' },
    { word: 'Estrella', hint: 'Nit' },
    { word: 'Boira', hint: 'Poca visibilitat' },
    { word: 'Mar', hint: 'Salat' },
    { word: 'Núvol', hint: 'Cel' },
    { word: 'Neu', hint: 'Fred blanc' },
    { word: 'Glacera', hint: 'Gel enorme' },
    { word: 'Illa', hint: 'Envoltada' },
    { word: 'Llac', hint: 'Aigua quieta' },
    { word: 'Cova', hint: 'Subterrani' },
    { word: 'Roca', hint: 'Dura' },
    { word: 'Vent', hint: 'Aire mòbil' },
    { word: 'Pluja', hint: 'Gotes' },
    { word: 'Sol', hint: 'Llum diürna' },
    { word: 'Lluna', hint: 'Satèl·lit' },
    { word: 'Cometa', hint: 'Cua brillant' },
    { word: 'Tornado', hint: 'Remolí' },
    { word: 'Terratrèmol', hint: 'Tremolor' },
    { word: 'Selva', hint: 'Tròpic humit' },
    { word: 'Praderia', hint: 'Herba plana' },
    { word: 'Penya-segat', hint: 'Vora abrupta' },
    { word: 'Flor', hint: 'Pètals' },
    { word: 'Tempesta', hint: 'Trons' },
  ],
  en: [
    { word: 'River', hint: 'Water' },
    { word: 'Mountain', hint: 'Height' },
    { word: 'Volcano', hint: 'Lava' },
    { word: 'Lightning', hint: 'Storm' },
    { word: 'Rainbow', hint: 'Colors' },
    { word: 'Forest', hint: 'Trees' },
    { word: 'Desert', hint: 'Dry sand' },
    { word: 'Waterfall', hint: 'Drop' },
    { word: 'Star', hint: 'Night sky' },
    { word: 'Fog', hint: 'Low visibility' },
    { word: 'Sea', hint: 'Salty' },
    { word: 'Cloud', hint: 'Sky' },
    { word: 'Snow', hint: 'White cold' },
    { word: 'Glacier', hint: 'Huge ice' },
    { word: 'Island', hint: 'Surrounded' },
    { word: 'Lake', hint: 'Still water' },
    { word: 'Cave', hint: 'Underground' },
    { word: 'Rock', hint: 'Hard' },
    { word: 'Wind', hint: 'Moving air' },
    { word: 'Rain', hint: 'Drops' },
    { word: 'Sun', hint: 'Daylight' },
    { word: 'Moon', hint: 'Satellite' },
    { word: 'Comet', hint: 'Bright tail' },
    { word: 'Tornado', hint: 'Whirl' },
    { word: 'Earthquake', hint: 'Shaking' },
    { word: 'Jungle', hint: 'Humid tropic' },
    { word: 'Meadow', hint: 'Flat grass' },
    { word: 'Cliff', hint: 'Steep edge' },
    { word: 'Flower', hint: 'Petals' },
    { word: 'Storm', hint: 'Thunder' },
  ],
  es: [
    { word: 'Río', hint: 'Agua' },
    { word: 'Montaña', hint: 'Altura' },
    { word: 'Volcán', hint: 'Lava' },
    { word: 'Relámpago', hint: 'Tormenta' },
    { word: 'Arcoíris', hint: 'Colores' },
    { word: 'Bosque', hint: 'Árboles' },
    { word: 'Desierto', hint: 'Arena seca' },
    { word: 'Cascada', hint: 'Salto' },
    { word: 'Estrella', hint: 'Cielo nocturno' },
    { word: 'Niebla', hint: 'Poca visibilidad' },
    { word: 'Mar', hint: 'Salado' },
    { word: 'Nube', hint: 'Cielo' },
    { word: 'Nieve', hint: 'Frío blanco' },
    { word: 'Glaciar', hint: 'Hielo enorme' },
    { word: 'Isla', hint: 'Rodeada' },
    { word: 'Lago', hint: 'Agua quieta' },
    { word: 'Cueva', hint: 'Subterráneo' },
    { word: 'Roca', hint: 'Dura' },
    { word: 'Viento', hint: 'Aire en movimiento' },
    { word: 'Lluvia', hint: 'Gotas' },
    { word: 'Sol', hint: 'Luz del día' },
    { word: 'Luna', hint: 'Satélite' },
    { word: 'Cometa', hint: 'Cola brillante' },
    { word: 'Tornado', hint: 'Remolino' },
    { word: 'Terremoto', hint: 'Temblor' },
    { word: 'Selva', hint: 'Trópico húmedo' },
    { word: 'Pradera', hint: 'Hierba llana' },
    { word: 'Acantilado', hint: 'Borde abrupto' },
    { word: 'Flor', hint: 'Pétalos' },
    { word: 'Tormenta', hint: 'Truenos' },
  ],
  eu: [
    { word: 'Ibaia', hint: 'Ura' },
    { word: 'Mendia', hint: 'Altuera' },
    { word: 'Sumendia', hint: 'Laba' },
    { word: 'Tximista', hint: 'Ekaitza' },
    { word: 'Ostadarra', hint: 'Koloreak' },
    { word: 'Basoa', hint: 'Zuhaitzak' },
    { word: 'Basamortua', hint: 'Harea lehorra' },
    { word: 'Ur-jauzia', hint: 'Erorketa' },
    { word: 'Izarra', hint: 'Gaueko zerua' },
    { word: 'Lainoa', hint: 'Ikuspen txikia' },
    { word: 'Itsasoa', hint: 'Gazia' },
    { word: 'Hodeia', hint: 'Zerua' },
    { word: 'Elurra', hint: 'Hotz zuria' },
    { word: 'Glaziarra', hint: 'Izotz handia' },
    { word: 'Uhartea', hint: 'Inguratua' },
    { word: 'Aintzira', hint: 'Ur geldia' },
    { word: 'Haitzuloa', hint: 'Lurpean' },
    { word: 'Harkaitza', hint: 'Gogorra' },
    { word: 'Haizea', hint: 'Aire mugikorra' },
    { word: 'Euria', hint: 'Tantak' },
    { word: 'Eguzkia', hint: 'Eguneko argia' },
    { word: 'Ilargia', hint: 'Satelitea' },
    { word: 'Kometa', hint: 'Isats distiratsua' },
    { word: 'Tornadoa', hint: 'Zurrunbiloa' },
    { word: 'Lurrikara', hint: 'Dardara' },
    { word: 'Oihana', hint: 'Tropiko hezea' },
    { word: 'Larrea', hint: 'Belar laua' },
    { word: 'Itsaslabarra', hint: 'Ertz malkartsua' },
    { word: 'Lorea', hint: 'Petaloak' },
    { word: 'Ekaitza', hint: 'Trumoiak' },
  ],
  gl: [
    { word: 'Río', hint: 'Auga' },
    { word: 'Montaña', hint: 'Altura' },
    { word: 'Volcán', hint: 'Lava' },
    { word: 'Lóstrego', hint: 'Tormenta' },
    { word: 'Arco da vella', hint: 'Cores' },
    { word: 'Bosque', hint: 'Árbores' },
    { word: 'Deserto', hint: 'Area seca' },
    { word: 'Fervenza', hint: 'Salto' },
    { word: 'Estrela', hint: 'Ceo nocturno' },
    { word: 'Néboa', hint: 'Pouca visibilidade' },
    { word: 'Mar', hint: 'Salgado' },
    { word: 'Nube', hint: 'Ceo' },
    { word: 'Neve', hint: 'Frío branco' },
    { word: 'Glaciar', hint: 'Xeo enorme' },
    { word: 'Illa', hint: 'Rodeada' },
    { word: 'Lago', hint: 'Auga quieta' },
    { word: 'Cova', hint: 'Subterráneo' },
    { word: 'Rocha', hint: 'Dura' },
    { word: 'Vento', hint: 'Aire en movemento' },
    { word: 'Choiva', hint: 'Pingas' },
    { word: 'Sol', hint: 'Luz do día' },
    { word: 'Lúa', hint: 'Satélite' },
    { word: 'Cometa', hint: 'Cola brillante' },
    { word: 'Tornado', hint: 'Remuíño' },
    { word: 'Terremoto', hint: 'Tremor' },
    { word: 'Selva', hint: 'Trópico húmido' },
    { word: 'Pradería', hint: 'Herba chá' },
    { word: 'Cantil', hint: 'Bordo abrupto' },
    { word: 'Flor', hint: 'Pétalos' },
    { word: 'Tormenta', hint: 'Tronos' },
  ],
  va: [
    { word: 'Riu', hint: 'Aigua' },
    { word: 'Muntanya', hint: 'Altura' },
    { word: 'Volcà', hint: 'Lava' },
    { word: 'Llamp', hint: 'Tempestat' },
    { word: 'Arc de Sant Martí', hint: 'Colors' },
    { word: 'Bosc', hint: 'Arbres' },
    { word: 'Desert', hint: 'Arena seca' },
    { word: 'Cascada', hint: 'Bot' },
    { word: 'Estrela', hint: 'Nit' },
    { word: 'Boira', hint: 'Poca visibilitat' },
    { word: 'Mar', hint: 'Salat' },
    { word: 'Núvol', hint: 'Cel' },
    { word: 'Neu', hint: 'Fred blanc' },
    { word: 'Glacera', hint: 'Gel enorme' },
    { word: 'Illa', hint: 'Envoltada' },
    { word: 'Llac', hint: 'Aigua quieta' },
    { word: 'Cova', hint: 'Subterrani' },
    { word: 'Roca', hint: 'Dura' },
    { word: 'Vent', hint: 'Aire en moviment' },
    { word: 'Pluja', hint: 'Gotes' },
    { word: 'Sol', hint: 'Llum del dia' },
    { word: 'Lluna', hint: 'Satèl·lit' },
    { word: 'Cometa', hint: 'Cua brillant' },
    { word: 'Tornado', hint: 'Remolí' },
    { word: 'Terratrémol', hint: 'Tremolor' },
    { word: 'Selva', hint: 'Tròpic humit' },
    { word: 'Praderia', hint: 'Herba plana' },
    { word: 'Penya-segat', hint: 'Vora abrupta' },
    { word: 'Flor', hint: 'Pètals' },
    { word: 'Tempestat', hint: 'Trons' },
  ],
}
