import type { WordEntry } from '../../domain/content/types'
import type { LocaleCode } from '../../domain/game/types'

export const places: Partial<Record<LocaleCode, WordEntry[]>> = {
  ca: [
    { word: 'Platja', hint: 'Estiu' },
    { word: 'Hospital', hint: 'Salut' },
    { word: 'Aeroport', hint: 'Viatges' },
    { word: 'Biblioteca', hint: 'Llibres' },
    { word: 'Mercat', hint: 'Compres' },
    { word: 'Estadi', hint: 'Esport' },
    { word: 'Museu', hint: 'Art' },
    { word: 'Presó', hint: 'Reclusos' },
    { word: 'Far', hint: 'Costa' },
    { word: 'Castell', hint: 'Edat mitjana' },
    { word: 'Escola', hint: 'Alumnes' },
    { word: 'Restaurant', hint: 'Menjar' },
    { word: 'Cinema', hint: 'Pel·lícules' },
    { word: 'Església', hint: 'Pregària' },
    { word: 'Parc', hint: 'Natura urbana' },
    { word: 'Estació', hint: 'Trens' },
    { word: 'Banc', hint: 'Diners' },
    { word: 'Hotel', hint: 'Allotjament' },
    { word: 'Zoo', hint: 'Animals' },
    { word: 'Teatre', hint: 'Escenari' },
    { word: 'Gimnàs', hint: 'Exercici' },
    { word: 'Granja', hint: 'Bestiar' },
    { word: 'Muntanya', hint: 'Alçada' },
    { word: 'Riu', hint: 'Aigua corrent' },
    { word: 'Bosc', hint: 'Arbres' },
    { word: 'Desert', hint: 'Sorra seca' },
    { word: 'Volcà', hint: 'Lava' },
    { word: 'Cova', hint: 'Subterrani' },
    { word: 'Everest', hint: 'Cim més alt' },
    { word: 'Sàhara', hint: 'Desert africà' },
  ],
  en: [
    { word: 'Beach', hint: 'Summer' },
    { word: 'Hospital', hint: 'Health' },
    { word: 'Airport', hint: 'Travel' },
    { word: 'Library', hint: 'Books' },
    { word: 'Market', hint: 'Shopping' },
    { word: 'Stadium', hint: 'Sport' },
    { word: 'Museum', hint: 'Art' },
    { word: 'Prison', hint: 'Inmates' },
    { word: 'Lighthouse', hint: 'Coast' },
    { word: 'Castle', hint: 'Middle ages' },
    { word: 'School', hint: 'Students' },
    { word: 'Restaurant', hint: 'Food' },
    { word: 'Cinema', hint: 'Movies' },
    { word: 'Church', hint: 'Prayer' },
    { word: 'Park', hint: 'Urban nature' },
    { word: 'Station', hint: 'Trains' },
    { word: 'Bank', hint: 'Money' },
    { word: 'Hotel', hint: 'Lodging' },
    { word: 'Zoo', hint: 'Animals' },
    { word: 'Theater', hint: 'Stage' },
    { word: 'Gym', hint: 'Exercise' },
    { word: 'Farm', hint: 'Livestock' },
    { word: 'Mountain', hint: 'Height' },
    { word: 'River', hint: 'Flowing water' },
    { word: 'Forest', hint: 'Trees' },
    { word: 'Desert', hint: 'Dry sand' },
    { word: 'Volcano', hint: 'Lava' },
    { word: 'Cave', hint: 'Underground' },
    { word: 'Everest', hint: 'Highest peak' },
    { word: 'Sahara', hint: 'African desert' },
  ],
  es: [
    { word: 'Playa', hint: 'Verano' },
    { word: 'Hospital', hint: 'Salud' },
    { word: 'Aeropuerto', hint: 'Viajes' },
    { word: 'Biblioteca', hint: 'Libros' },
    { word: 'Mercado', hint: 'Compras' },
    { word: 'Estadio', hint: 'Deporte' },
    { word: 'Museo', hint: 'Arte' },
    { word: 'Cárcel', hint: 'Reclusos' },
    { word: 'Faro', hint: 'Costa' },
    { word: 'Castillo', hint: 'Edad media' },
    { word: 'Escuela', hint: 'Alumnos' },
    { word: 'Restaurante', hint: 'Comida' },
    { word: 'Cine', hint: 'Películas' },
    { word: 'Iglesia', hint: 'Rezos' },
    { word: 'Parque', hint: 'Naturaleza urbana' },
    { word: 'Estación', hint: 'Trenes' },
    { word: 'Banco', hint: 'Dinero' },
    { word: 'Hotel', hint: 'Alojamiento' },
    { word: 'Zoológico', hint: 'Animales' },
    { word: 'Teatro', hint: 'Escenario' },
    { word: 'Gimnasio', hint: 'Ejercicio' },
    { word: 'Granja', hint: 'Ganado' },
    { word: 'Montaña', hint: 'Altura' },
    { word: 'Río', hint: 'Agua corriente' },
    { word: 'Bosque', hint: 'Árboles' },
    { word: 'Desierto', hint: 'Arena seca' },
    { word: 'Volcán', hint: 'Lava' },
    { word: 'Cueva', hint: 'Subterráneo' },
    { word: 'Everest', hint: 'Cima más alta' },
    { word: 'Sáhara', hint: 'Desierto africano' },
  ],
  eu: [
    { word: 'Hondartza', hint: 'Uda' },
    { word: 'Ospitalea', hint: 'Osasuna' },
    { word: 'Aireportua', hint: 'Bidaiak' },
    { word: 'Liburutegia', hint: 'Liburuak' },
    { word: 'Merkatua', hint: 'Erosketak' },
    { word: 'Estadioa', hint: 'Kirola' },
    { word: 'Museoa', hint: 'Artea' },
    { word: 'Kartzela', hint: 'Presoak' },
    { word: 'Itsasargia', hint: 'Kostaldea' },
    { word: 'Gaztelua', hint: 'Erdi aroa' },
    { word: 'Eskola', hint: 'Ikasleak' },
    { word: 'Jatetxea', hint: 'Janaria' },
    { word: 'Zinema', hint: 'Filmak' },
    { word: 'Eliza', hint: 'Otoitza' },
    { word: 'Parkea', hint: 'Hiri natura' },
    { word: 'Geltokia', hint: 'Trenak' },
    { word: 'Bankua', hint: 'Dirua' },
    { word: 'Hotela', hint: 'Ostatua' },
    { word: 'Zooa', hint: 'Animaliak' },
    { word: 'Antzokia', hint: 'Eszenatokia' },
    { word: 'Gimnasioa', hint: 'Ariketa' },
    { word: 'Baserria', hint: 'Abereak' },
    { word: 'Mendia', hint: 'Altuera' },
    { word: 'Ibaia', hint: 'Ur korrontea' },
    { word: 'Basoa', hint: 'Zuhaitzak' },
    { word: 'Basamortua', hint: 'Harea lehorra' },
    { word: 'Sumendia', hint: 'Laba' },
    { word: 'Kobazuloa', hint: 'Lurpekoa' },
    { word: 'Everest', hint: 'Gailur altuena' },
    { word: 'Sahara', hint: 'Afrikako basamortua' },
  ],
  gl: [
    { word: 'Praia', hint: 'Verán' },
    { word: 'Hospital', hint: 'Saúde' },
    { word: 'Aeroporto', hint: 'Viaxes' },
    { word: 'Biblioteca', hint: 'Libros' },
    { word: 'Mercado', hint: 'Compras' },
    { word: 'Estadio', hint: 'Deporte' },
    { word: 'Museo', hint: 'Arte' },
    { word: 'Cárcere', hint: 'Reclusos' },
    { word: 'Faro', hint: 'Costa' },
    { word: 'Castelo', hint: 'Idade media' },
    { word: 'Escola', hint: 'Alumnos' },
    { word: 'Restaurante', hint: 'Comida' },
    { word: 'Cine', hint: 'Películas' },
    { word: 'Igrexa', hint: 'Rezos' },
    { word: 'Parque', hint: 'Natureza urbana' },
    { word: 'Estación', hint: 'Trens' },
    { word: 'Banco', hint: 'Diñeiro' },
    { word: 'Hotel', hint: 'Aloxamento' },
    { word: 'Zoolóxico', hint: 'Animais' },
    { word: 'Teatro', hint: 'Escenario' },
    { word: 'Ximnasio', hint: 'Exercicio' },
    { word: 'Granxa', hint: 'Gando' },
    { word: 'Montaña', hint: 'Altura' },
    { word: 'Río', hint: 'Auga corrente' },
    { word: 'Bosque', hint: 'Árbores' },
    { word: 'Deserto', hint: 'Area seca' },
    { word: 'Volcán', hint: 'Lava' },
    { word: 'Cova', hint: 'Subterráneo' },
    { word: 'Everest', hint: 'Cima máis alta' },
    { word: 'Sáhara', hint: 'Deserto africano' },
  ],
  va: [
    { word: 'Platja', hint: 'Estiu' },
    { word: 'Hospital', hint: 'Salut' },
    { word: 'Aeroport', hint: 'Viatges' },
    { word: 'Biblioteca', hint: 'Llibres' },
    { word: 'Mercat', hint: 'Compres' },
    { word: 'Estadi', hint: 'Esport' },
    { word: 'Museu', hint: 'Art' },
    { word: 'Presó', hint: 'Reclusos' },
    { word: 'Far', hint: 'Costa' },
    { word: 'Castell', hint: 'Edat mitjana' },
    { word: 'Escola', hint: 'Alumnes' },
    { word: 'Restaurant', hint: 'Menjar' },
    { word: 'Cine', hint: 'Pel·lícules' },
    { word: 'Església', hint: 'Pregària' },
    { word: 'Parc', hint: 'Natura urbana' },
    { word: 'Estació', hint: 'Trens' },
    { word: 'Banc', hint: 'Diners' },
    { word: 'Hotel', hint: 'Allotjament' },
    { word: 'Zoo', hint: 'Animals' },
    { word: 'Teatre', hint: 'Escenari' },
    { word: 'Gimnàs', hint: 'Exercici' },
    { word: 'Granja', hint: 'Bestiar' },
    { word: 'Muntanya', hint: 'Altura' },
    { word: 'Riu', hint: 'Aigua corrent' },
    { word: 'Bosc', hint: 'Arbres' },
    { word: 'Desert', hint: 'Arena seca' },
    { word: 'Volcà', hint: 'Lava' },
    { word: 'Cova', hint: 'Subterrani' },
    { word: 'Everest', hint: 'Cim més alt' },
    { word: 'Sàhara', hint: 'Desert africà' },
  ],
}
