import type { WordEntry } from '../../domain/content/types'
import type { LocaleCode } from '../../domain/game/types'

export const places: Partial<Record<LocaleCode, WordEntry[]>> = {
  ca: [
    { word: 'Platja', hints: ['Estiu', 'Sorra', 'Onades'] },
    { word: 'Hospital', hints: ['Salut', 'Metges', 'Urgències'] },
    { word: 'Aeroport', hints: ['Viatges', 'Avions', 'Maletes'] },
    { word: 'Biblioteca', hints: ['Llibres', 'Silenci', 'Lectura'] },
    { word: 'Mercat', hints: ['Compres', 'Parades', 'Verdures'] },
    { word: 'Estadi', hints: ['Esport', 'Grades', 'Públic'] },
    { word: 'Museu', hints: ['Art', 'Quadres', 'Història'] },
    { word: 'Presó', hints: ['Reclusos', 'Reixes', 'Càstig'] },
    { word: 'Far', hints: ['Costa', 'Llum', 'Mariners'] },
    { word: 'Castell', hints: ['Edat mitjana', 'Muralla', 'Rei'] },
    { word: 'Escola', hints: ['Alumnes', 'Pissarra', 'Mestres'] },
    { word: 'Restaurant', hints: ['Menjar', 'Cambrer', 'Taules'] },
    { word: 'Cinema', hints: ['Pel·lícules', 'Pantalla', 'Crispetes'] },
    { word: 'Església', hints: ['Pregària', 'Campanar', 'Religió'] },
    { word: 'Parc', hints: ['Natura urbana', 'Bancs', 'Gronxadors'] },
    { word: 'Estació', hints: ['Trens', 'Andana', 'Bitllets'] },
    { word: 'Banc', hints: ['Diners', 'Caixer', 'Estalvis'] },
    { word: 'Hotel', hints: ['Allotjament', 'Recepció', 'Habitacions'] },
    { word: 'Zoo', hints: ['Animals', 'Gàbies', 'Lleons'] },
    { word: 'Teatre', hints: ['Escenari', 'Actors', 'Teló'] },
    { word: 'Gimnàs', hints: ['Exercici', 'Peses', 'Músculs'] },
    { word: 'Granja', hints: ['Bestiar', 'Tractor', 'Camp'] },
    { word: 'Muntanya', hints: ['Alçada', 'Cim', 'Excursió'] },
    { word: 'Riu', hints: ['Aigua corrent', 'Pont', 'Peixos'] },
    { word: 'Bosc', hints: ['Arbres', 'Verd', 'Bolets'] },
    { word: 'Desert', hints: ['Sorra seca', 'Calor', 'Dunes'] },
    { word: 'Volcà', hints: ['Lava', 'Erupció', 'Cràter'] },
    { word: 'Cova', hints: ['Subterrani', 'Foscor', 'Estalactites'] },
    { word: 'Everest', hints: ['Cim més alt', 'Nepal', 'Neu'] },
    { word: 'Sàhara', hints: ['Desert africà', 'Dunes', 'Camells'] },
  ],
  en: [
    { word: 'Beach', hints: ['Summer', 'Sand', 'Waves'] },
    { word: 'Hospital', hints: ['Health', 'Doctors', 'Emergency'] },
    { word: 'Airport', hints: ['Travel', 'Planes', 'Luggage'] },
    { word: 'Library', hints: ['Books', 'Silence', 'Reading'] },
    { word: 'Market', hints: ['Shopping', 'Stalls', 'Vegetables'] },
    { word: 'Stadium', hints: ['Sport', 'Stands', 'Crowd'] },
    { word: 'Museum', hints: ['Art', 'Paintings', 'History'] },
    { word: 'Prison', hints: ['Inmates', 'Bars', 'Punishment'] },
    { word: 'Lighthouse', hints: ['Coast', 'Beam', 'Sailors'] },
    { word: 'Castle', hints: ['Middle ages', 'Walls', 'King'] },
    { word: 'School', hints: ['Students', 'Blackboard', 'Teachers'] },
    { word: 'Restaurant', hints: ['Food', 'Waiter', 'Tables'] },
    { word: 'Cinema', hints: ['Movies', 'Screen', 'Popcorn'] },
    { word: 'Church', hints: ['Prayer', 'Bells', 'Religion'] },
    { word: 'Park', hints: ['Urban nature', 'Benches', 'Swings'] },
    { word: 'Station', hints: ['Trains', 'Platform', 'Tickets'] },
    { word: 'Bank', hints: ['Money', 'ATM', 'Savings'] },
    { word: 'Hotel', hints: ['Lodging', 'Reception', 'Rooms'] },
    { word: 'Zoo', hints: ['Animals', 'Cages', 'Lions'] },
    { word: 'Theater', hints: ['Stage', 'Actors', 'Curtain'] },
    { word: 'Gym', hints: ['Exercise', 'Weights', 'Muscles'] },
    { word: 'Farm', hints: ['Livestock', 'Tractor', 'Fields'] },
    { word: 'Mountain', hints: ['Height', 'Summit', 'Hiking'] },
    { word: 'River', hints: ['Flowing water', 'Bridge', 'Fish'] },
    { word: 'Forest', hints: ['Trees', 'Green', 'Wildlife'] },
    { word: 'Desert', hints: ['Dry sand', 'Heat', 'Dunes'] },
    { word: 'Volcano', hints: ['Lava', 'Eruption', 'Crater'] },
    { word: 'Cave', hints: ['Underground', 'Darkness', 'Stalactites'] },
    { word: 'Everest', hints: ['Highest peak', 'Nepal', 'Snow'] },
    { word: 'Sahara', hints: ['African desert', 'Dunes', 'Camels'] },
  ],
  es: [
    { word: 'Playa', hints: ['Verano', 'Arena', 'Olas'] },
    { word: 'Hospital', hints: ['Salud', 'Médicos', 'Urgencias'] },
    { word: 'Aeropuerto', hints: ['Viajes', 'Aviones', 'Maletas'] },
    { word: 'Biblioteca', hints: ['Libros', 'Silencio', 'Lectura'] },
    { word: 'Mercado', hints: ['Compras', 'Puestos', 'Verduras'] },
    { word: 'Estadio', hints: ['Deporte', 'Gradas', 'Público'] },
    { word: 'Museo', hints: ['Arte', 'Cuadros', 'Historia'] },
    { word: 'Cárcel', hints: ['Reclusos', 'Rejas', 'Castigo'] },
    { word: 'Faro', hints: ['Costa', 'Luz', 'Marineros'] },
    { word: 'Castillo', hints: ['Edad media', 'Muralla', 'Rey'] },
    { word: 'Escuela', hints: ['Alumnos', 'Pizarra', 'Maestros'] },
    { word: 'Restaurante', hints: ['Comida', 'Camarero', 'Mesas'] },
    { word: 'Cine', hints: ['Películas', 'Pantalla', 'Palomitas'] },
    { word: 'Iglesia', hints: ['Rezos', 'Campanas', 'Religión'] },
    { word: 'Parque', hints: ['Naturaleza urbana', 'Bancos', 'Columpios'] },
    { word: 'Estación', hints: ['Trenes', 'Andén', 'Billetes'] },
    { word: 'Banco', hints: ['Dinero', 'Cajero', 'Ahorros'] },
    { word: 'Hotel', hints: ['Alojamiento', 'Recepción', 'Habitaciones'] },
    { word: 'Zoológico', hints: ['Animales', 'Jaulas', 'Leones'] },
    { word: 'Teatro', hints: ['Escenario', 'Actores', 'Telón'] },
    { word: 'Gimnasio', hints: ['Ejercicio', 'Pesas', 'Músculos'] },
    { word: 'Granja', hints: ['Ganado', 'Tractor', 'Campo'] },
    { word: 'Montaña', hints: ['Altura', 'Cima', 'Excursión'] },
    { word: 'Río', hints: ['Agua corriente', 'Puente', 'Peces'] },
    { word: 'Bosque', hints: ['Árboles', 'Verde', 'Setas'] },
    { word: 'Desierto', hints: ['Arena seca', 'Calor', 'Dunas'] },
    { word: 'Volcán', hints: ['Lava', 'Erupción', 'Cráter'] },
    { word: 'Cueva', hints: ['Subterráneo', 'Oscuridad', 'Estalactitas'] },
    { word: 'Everest', hints: ['Cima más alta', 'Nepal', 'Nieve'] },
    { word: 'Sáhara', hints: ['Desierto africano', 'Dunas', 'Camellos'] },
  ],
  eu: [
    { word: 'Hondartza', hints: ['Uda', 'Harea', 'Olatuak'] },
    { word: 'Ospitalea', hints: ['Osasuna', 'Medikuak', 'Larrialdiak'] },
    { word: 'Aireportua', hints: ['Bidaiak', 'Hegazkinak', 'Maletak'] },
    { word: 'Liburutegia', hints: ['Liburuak', 'Isiltasuna', 'Irakurketa'] },
    { word: 'Merkatua', hints: ['Erosketak', 'Postuak', 'Barazkiak'] },
    { word: 'Estadioa', hints: ['Kirola', 'Harmailak', 'Jendea'] },
    { word: 'Museoa', hints: ['Artea', 'Koadroak', 'Historia'] },
    { word: 'Kartzela', hints: ['Presoak', 'Burdinak', 'Zigorra'] },
    { word: 'Itsasargia', hints: ['Kostaldea', 'Distira', 'Marinelak'] },
    { word: 'Gaztelua', hints: ['Erdi aroa', 'Harresia', 'Erregea'] },
    { word: 'Eskola', hints: ['Ikasleak', 'Arbela', 'Irakasleak'] },
    { word: 'Jatetxea', hints: ['Janaria', 'Zerbitzaria', 'Mahaiak'] },
    { word: 'Zinema', hints: ['Filmak', 'Pantaila', 'Krispetak'] },
    { word: 'Eliza', hints: ['Otoitza', 'Kanpaiak', 'Erlijioa'] },
    { word: 'Parkea', hints: ['Hiri natura', 'Eserlekuak', 'Zabuak'] },
    { word: 'Geltokia', hints: ['Trenak', 'Nasa', 'Txartelak'] },
    { word: 'Bankua', hints: ['Dirua', 'Kutxazaina', 'Aurrezkiak'] },
    { word: 'Hotela', hints: ['Ostatua', 'Harrera', 'Gelak'] },
    { word: 'Zooa', hints: ['Animaliak', 'Kaiolak', 'Lehoiak'] },
    { word: 'Antzokia', hints: ['Eszenatokia', 'Aktoreak', 'Oihala'] },
    { word: 'Gimnasioa', hints: ['Ariketa', 'Pisuak', 'Giharrak'] },
    { word: 'Baserria', hints: ['Abereak', 'Traktorea', 'Soroa'] },
    { word: 'Mendia', hints: ['Altuera', 'Gailurra', 'Txangoa'] },
    { word: 'Ibaia', hints: ['Ur korrontea', 'Zubia', 'Arrainak'] },
    { word: 'Basoa', hints: ['Zuhaitzak', 'Berdea', 'Onddoak'] },
    { word: 'Basamortua', hints: ['Harea lehorra', 'Beroa', 'Dunak'] },
    { word: 'Sumendia', hints: ['Laba', 'Erupzioa', 'Kraterra'] },
    { word: 'Kobazuloa', hints: ['Lurpekoa', 'Iluntasuna', 'Estalaktitak'] },
    { word: 'Everest', hints: ['Gailur altuena', 'Nepal', 'Elurra'] },
    { word: 'Sahara', hints: ['Afrikako basamortua', 'Dunak', 'Gameluak'] },
  ],
  gl: [
    { word: 'Praia', hints: ['Verán', 'Area', 'Ondas'] },
    { word: 'Hospital', hints: ['Saúde', 'Médicos', 'Urxencias'] },
    { word: 'Aeroporto', hints: ['Viaxes', 'Avións', 'Maletas'] },
    { word: 'Biblioteca', hints: ['Libros', 'Silencio', 'Lectura'] },
    { word: 'Mercado', hints: ['Compras', 'Postos', 'Verduras'] },
    { word: 'Estadio', hints: ['Deporte', 'Bancadas', 'Público'] },
    { word: 'Museo', hints: ['Arte', 'Cadros', 'Historia'] },
    { word: 'Cárcere', hints: ['Reclusos', 'Reixas', 'Castigo'] },
    { word: 'Faro', hints: ['Costa', 'Luz', 'Mariñeiros'] },
    { word: 'Castelo', hints: ['Idade media', 'Muralla', 'Rei'] },
    { word: 'Escola', hints: ['Alumnos', 'Encerado', 'Mestres'] },
    { word: 'Restaurante', hints: ['Comida', 'Camareiro', 'Mesas'] },
    { word: 'Cine', hints: ['Películas', 'Pantalla', 'Pipas'] },
    { word: 'Igrexa', hints: ['Rezos', 'Campás', 'Relixión'] },
    { word: 'Parque', hints: ['Natureza urbana', 'Bancos', 'Randeeiras'] },
    { word: 'Estación', hints: ['Trens', 'Andén', 'Billetes'] },
    { word: 'Banco', hints: ['Diñeiro', 'Caixeiro', 'Aforros'] },
    { word: 'Hotel', hints: ['Aloxamento', 'Recepción', 'Cuartos'] },
    { word: 'Zoolóxico', hints: ['Animais', 'Gaiolas', 'Leóns'] },
    { word: 'Teatro', hints: ['Escenario', 'Actores', 'Pano'] },
    { word: 'Ximnasio', hints: ['Exercicio', 'Pesas', 'Músculos'] },
    { word: 'Granxa', hints: ['Gando', 'Tractor', 'Campo'] },
    { word: 'Montaña', hints: ['Altura', 'Cima', 'Excursión'] },
    { word: 'Río', hints: ['Auga corrente', 'Ponte', 'Peixes'] },
    { word: 'Bosque', hints: ['Árbores', 'Verde', 'Cogomelos'] },
    { word: 'Deserto', hints: ['Area seca', 'Calor', 'Dunas'] },
    { word: 'Volcán', hints: ['Lava', 'Erupción', 'Cráter'] },
    { word: 'Cova', hints: ['Subterráneo', 'Escuridade', 'Estalactitas'] },
    { word: 'Everest', hints: ['Cima máis alta', 'Nepal', 'Neve'] },
    { word: 'Sáhara', hints: ['Deserto africano', 'Dunas', 'Camelos'] },
  ],
  va: [
    { word: 'Platja', hints: ['Estiu', 'Arena', 'Onades'] },
    { word: 'Hospital', hints: ['Salut', 'Metges', 'Urgències'] },
    { word: 'Aeroport', hints: ['Viatges', 'Avions', 'Maletes'] },
    { word: 'Biblioteca', hints: ['Llibres', 'Silenci', 'Lectura'] },
    { word: 'Mercat', hints: ['Compres', 'Parades', 'Verdures'] },
    { word: 'Estadi', hints: ['Esport', 'Grades', 'Públic'] },
    { word: 'Museu', hints: ['Art', 'Quadres', 'Història'] },
    { word: 'Presó', hints: ['Reclusos', 'Reixes', 'Càstig'] },
    { word: 'Far', hints: ['Costa', 'Llum', 'Mariners'] },
    { word: 'Castell', hints: ['Edat mitjana', 'Muralla', 'Rei'] },
    { word: 'Escola', hints: ['Alumnes', 'Pissarra', 'Mestres'] },
    { word: 'Restaurant', hints: ['Menjar', 'Cambrer', 'Taules'] },
    { word: 'Cine', hints: ['Pel·lícules', 'Pantalla', 'Crispetes'] },
    { word: 'Església', hints: ['Pregària', 'Campanar', 'Religió'] },
    { word: 'Parc', hints: ['Natura urbana', 'Bancs', 'Gronxadors'] },
    { word: 'Estació', hints: ['Trens', 'Andana', 'Bitllets'] },
    { word: 'Banc', hints: ['Diners', 'Caixer', 'Estalvis'] },
    { word: 'Hotel', hints: ['Allotjament', 'Recepció', 'Habitacions'] },
    { word: 'Zoo', hints: ['Animals', 'Gàbies', 'Lleons'] },
    { word: 'Teatre', hints: ['Escenari', 'Actors', 'Teló'] },
    { word: 'Gimnàs', hints: ['Exercici', 'Peses', 'Músculs'] },
    { word: 'Granja', hints: ['Bestiar', 'Tractor', 'Camp'] },
    { word: 'Muntanya', hints: ['Altura', 'Cim', 'Excursió'] },
    { word: 'Riu', hints: ['Aigua corrent', 'Pont', 'Peixos'] },
    { word: 'Bosc', hints: ['Arbres', 'Verd', 'Bolets'] },
    { word: 'Desert', hints: ['Arena seca', 'Calor', 'Dunes'] },
    { word: 'Volcà', hints: ['Lava', 'Erupció', 'Cràter'] },
    { word: 'Cova', hints: ['Subterrani', 'Foscor', 'Estalactites'] },
    { word: 'Everest', hints: ['Cim més alt', 'Nepal', 'Neu'] },
    { word: 'Sàhara', hints: ['Desert africà', 'Dunes', 'Camells'] },
  ],
}
