import type { WordEntry } from '../../domain/content/types'
import type { LocaleCode } from '../../domain/game/types'

export const places: Partial<Record<LocaleCode, WordEntry[]>> = {
  ca: [
    { word: 'Platja', hints: ['Estiu', 'Sorra', 'Onades'] },
    { word: 'Hospital', hints: ['Salut', 'Metges', 'Urgències'] },
    { word: 'Aeroport', hints: ['Viatges', 'Avions', 'Maletes'] },
    { word: 'Biblioteca', hints: ['Llibres', 'Silenci', 'Lectura'] },
    { word: 'Mercat', hints: ['Compres', 'Parades', 'Verdures'] },
    { word: 'Estadi', hints: ['Esport', 'Grades', 'Públic'] },
    { word: 'Museu', hints: ['Art', 'Quadres', 'Història'] },
    { word: 'Presó', hints: ['Reclusos', 'Reixes', 'Càstig'] },
    { word: 'Far', hints: ['Costa', 'Llum', 'Mariners'] },
    { word: 'Castell', hints: ['Edat mitjana', 'Muralla', 'Rei'] },
    { word: 'Escola', hints: ['Alumnes', 'Pissarra', 'Mestres'] },
    { word: 'Restaurant', hints: ['Menjar', 'Cambrer', 'Taules'] },
    { word: 'Cinema', hints: ['Pel·lícules', 'Pantalla', 'Crispetes'] },
    { word: 'Església', hints: ['Pregària', 'Campanar', 'Religió'] },
    { word: 'Parc', hints: ['Natura urbana', 'Bancs', 'Gronxadors'] },
    { word: 'Estació', hints: ['Trens', 'Andana', 'Bitllets'] },
    { word: 'Aquàrium', hints: ['Peixos', 'Vidre', 'Taurons'] },
    { word: 'Hotel', hints: ['Allotjament', 'Recepció', 'Habitacions'] },
    { word: 'Zoo', hints: ['Animals', 'Gàbies', 'Lleons'] },
    { word: 'Teatre', hints: ['Escenari', 'Actors', 'Teló'] },
    { word: 'Gimnàs', hints: ['Exercici', 'Peses', 'Músculs'] },
    { word: 'Granja', hints: ['Bestiar', 'Tractor', 'Camp'] },
    { word: 'Supermercat', hints: ['Carro', 'Prestatgeries', 'Compra setmanal'] },
    { word: 'Piscina', hints: ['Nedar', 'Banyador', 'Trampolí'] },
    { word: 'Farmàcia', hints: ['Medicaments', 'Creu verda', 'Recepta'] },
    { word: 'Port', hints: ['Vaixells', 'Moll', 'Amarrar'] },
    { word: 'Ajuntament', hints: ['Alcalde', 'Plaça major', 'Tràmits'] },
    { word: 'Càmping', hints: ['Tenda de campanya', 'Sac de dormir', 'Caravanes'] },
    { word: 'Everest', hints: ['Cim més alt', 'Nepal', 'Neu'] },
    { word: 'Sàhara', hints: ['Desert africà', 'Dunes', 'Camells'] },
  ],
  en: [
    { word: 'Beach', hints: ['Summer', 'Sand', 'Waves'] },
    { word: 'Hospital', hints: ['Health', 'Doctors', 'Emergency'] },
    { word: 'Airport', hints: ['Travel', 'Planes', 'Luggage'] },
    { word: 'Library', hints: ['Books', 'Silence', 'Reading'] },
    { word: 'Market', hints: ['Shopping', 'Stalls', 'Vegetables'] },
    { word: 'Stadium', hints: ['Sport', 'Stands', 'Crowd'] },
    { word: 'Museum', hints: ['Art', 'Paintings', 'History'] },
    { word: 'Prison', hints: ['Inmates', 'Bars', 'Punishment'] },
    { word: 'Lighthouse', hints: ['Coast', 'Beam', 'Sailors'] },
    { word: 'Castle', hints: ['Middle ages', 'Walls', 'King'] },
    { word: 'School', hints: ['Students', 'Blackboard', 'Teachers'] },
    { word: 'Restaurant', hints: ['Food', 'Waiter', 'Tables'] },
    { word: 'Cinema', hints: ['Movies', 'Screen', 'Popcorn'] },
    { word: 'Church', hints: ['Prayer', 'Bells', 'Religion'] },
    { word: 'Park', hints: ['Picnic', 'Benches', 'Swings'] },
    { word: 'Station', hints: ['Trains', 'Platform', 'Tickets'] },
    { word: 'Bank', hints: ['Money', 'ATM', 'Savings'] },
    { word: 'Hotel', hints: ['Lodging', 'Reception', 'Rooms'] },
    { word: 'Zoo', hints: ['Animals', 'Cages', 'Lions'] },
    { word: 'Theatre', hints: ['Stage', 'Actors', 'Curtain'] },
    { word: 'Gym', hints: ['Exercise', 'Weights', 'Muscles'] },
    { word: 'Farm', hints: ['Livestock', 'Tractor', 'Fields'] },
    { word: 'Swimming pool', hints: ['Lanes', 'Chlorine', 'Goggles'] },
    { word: 'Supermarket', hints: ['Trolley', 'Checkout', 'Aisles'] },
    { word: 'Pharmacy', hints: ['Medicine', 'Prescription', 'Green cross'] },
    { word: 'Harbour', hints: ['Boats', 'Docks', 'Fishermen'] },
    { word: 'Town hall', hints: ['Mayor', 'Council', 'Weddings'] },
    { word: 'Campsite', hints: ['Tents', 'Sleeping bags', 'Marshmallows'] },
    { word: 'Everest', hints: ['Climbers', 'Nepal', 'Snow'] },
    { word: 'Sahara', hints: ['Oasis', 'Dunes', 'Camels'] },
  ],
  es: [
    { word: 'Playa', hints: ['Verano', 'Arena', 'Olas'] },
    { word: 'Hospital', hints: ['Salud', 'Médicos', 'Urgencias'] },
    { word: 'Aeropuerto', hints: ['Viajes', 'Aviones', 'Maletas'] },
    { word: 'Biblioteca', hints: ['Libros', 'Silencio', 'Lectura'] },
    { word: 'Mercado', hints: ['Compras', 'Puestos', 'Verduras'] },
    { word: 'Estadio', hints: ['Deporte', 'Gradas', 'Público'] },
    { word: 'Museo', hints: ['Arte', 'Cuadros', 'Historia'] },
    { word: 'Cárcel', hints: ['Reclusos', 'Rejas', 'Castigo'] },
    { word: 'Faro', hints: ['Costa', 'Luz', 'Marineros'] },
    { word: 'Castillo', hints: ['Edad Media', 'Muralla', 'Rey'] },
    { word: 'Escuela', hints: ['Alumnos', 'Pizarra', 'Maestros'] },
    { word: 'Restaurante', hints: ['Comida', 'Camarero', 'Mesas'] },
    { word: 'Cine', hints: ['Películas', 'Pantalla', 'Palomitas'] },
    { word: 'Iglesia', hints: ['Rezos', 'Campanas', 'Religión'] },
    { word: 'Parque', hints: ['Naturaleza urbana', 'Bancos', 'Columpios'] },
    { word: 'Estación de tren', hints: ['Andén', 'Billetes', 'Vías'] },
    { word: 'Peluquería', hints: ['Corte de pelo', 'Secador', 'Espejo'] },
    { word: 'Hotel', hints: ['Alojamiento', 'Recepción', 'Habitaciones'] },
    { word: 'Zoológico', hints: ['Animales', 'Jaulas', 'Leones'] },
    { word: 'Teatro', hints: ['Escenario', 'Actores', 'Telón'] },
    { word: 'Gimnasio', hints: ['Ejercicio', 'Pesas', 'Músculos'] },
    { word: 'Granja', hints: ['Ganado', 'Tractor', 'Campo'] },
    { word: 'Piscina', hints: ['Bañador', 'Socorrista', 'Cloro'] },
    { word: 'Supermercado', hints: ['Carrito', 'Caja', 'Ofertas'] },
    { word: 'Farmacia', hints: ['Medicinas', 'Cruz verde', 'Receta'] },
    { word: 'Puerto', hints: ['Barcos', 'Muelle', 'Grúas'] },
    { word: 'Ayuntamiento', hints: ['Alcalde', 'Plaza', 'Bodas'] },
    { word: 'Camping', hints: ['Saco de dormir', 'Hoguera', 'Vacaciones'] },
    { word: 'Everest', hints: ['Cima más alta', 'Nepal', 'Nieve'] },
    { word: 'Sáhara', hints: ['Desierto africano', 'Dunas', 'Camellos'] },
  ],
  eu: [
    { word: 'Hondartza', hints: ['Uda', 'Harea', 'Olatuak'] },
    { word: 'Ospitalea', hints: ['Osasuna', 'Medikuak', 'Larrialdiak'] },
    { word: 'Aireportua', hints: ['Bidaiak', 'Hegazkinak', 'Maletak'] },
    { word: 'Liburutegia', hints: ['Mailegua', 'Isiltasuna', 'Irakurketa'] },
    { word: 'Merkatua', hints: ['Erosketak', 'Postuak', 'Barazkiak'] },
    { word: 'Estadioa', hints: ['Kirola', 'Harmailak', 'Jendea'] },
    { word: 'Museoa', hints: ['Artea', 'Koadroak', 'Historia'] },
    { word: 'Kartzela', hints: ['Presoak', 'Burdin-sareak', 'Zigorra'] },
    { word: 'Itsasargia', hints: ['Kostaldea', 'Distira', 'Marinelak'] },
    { word: 'Gaztelua', hints: ['Erdi Aroa', 'Harresia', 'Erregea'] },
    { word: 'Eskola', hints: ['Ikasleak', 'Arbela', 'Irakasleak'] },
    { word: 'Jatetxea', hints: ['Janaria', 'Zerbitzaria', 'Mahaiak'] },
    { word: 'Zinema', hints: ['Filmak', 'Pantaila', 'Krispetak'] },
    { word: 'Eliza', hints: ['Otoitza', 'Kanpaiak', 'Erlijioa'] },
    { word: 'Parkea', hints: ['Txirristak', 'Eserlekuak', 'Zabuak'] },
    { word: 'Geltokia', hints: ['Trenak', 'Nasa', 'Txartelak'] },
    { word: 'Bankua', hints: ['Dirua', 'Kutxazaina', 'Aurrezkiak'] },
    { word: 'Hotela', hints: ['Ostatua', 'Harrera', 'Gelak'] },
    { word: 'Zooa', hints: ['Animaliak', 'Kaiolak', 'Lehoiak'] },
    { word: 'Antzokia', hints: ['Eszenatokia', 'Aktoreak', 'Oihala'] },
    { word: 'Gimnasioa', hints: ['Ariketa', 'Pisuak', 'Giharrak'] },
    { word: 'Baserria', hints: ['Abereak', 'Traktorea', 'Soroa'] },
    { word: 'Igerilekua', hints: ['Kloroa', 'Betaurrekoak', 'Bainujantzia'] },
    { word: 'Supermerkatua', hints: ['Erosketa-orga', 'Apalak', 'Eskaintzak'] },
    { word: 'Farmazia', hints: ['Botikak', 'Errezeta', 'Gurutze berdea'] },
    { word: 'Portua', hints: ['Itsasontziak', 'Kaia', 'Arrantzaleak'] },
    { word: 'Udaletxea', hints: ['Alkatea', 'Balkoia', 'Ezkontzak'] },
    { word: 'Kanpina', hints: ['Lo-zakuak', 'Udako oporrak', 'Karabanak'] },
    { word: 'Everest', hints: ['Eskalatzaileak', 'Nepal', 'Elurra'] },
    { word: 'Sahara', hints: ['Oasia', 'Dunak', 'Gameluak'] },
  ],
  gl: [
    { word: 'Praia', hints: ['Verán', 'Area', 'Ondas'] },
    { word: 'Hospital', hints: ['Saúde', 'Médicos', 'Urxencias'] },
    { word: 'Aeroporto', hints: ['Viaxes', 'Avións', 'Maletas'] },
    { word: 'Biblioteca', hints: ['Libros', 'Silencio', 'Lectura'] },
    { word: 'Mercado', hints: ['Compras', 'Postos', 'Verduras'] },
    { word: 'Estadio', hints: ['Deporte', 'Bancadas', 'Público'] },
    { word: 'Museo', hints: ['Arte', 'Cadros', 'Historia'] },
    { word: 'Cárcere', hints: ['Reclusos', 'Reixas', 'Castigo'] },
    { word: 'Faro', hints: ['Costa', 'Luz', 'Mariñeiros'] },
    { word: 'Castelo', hints: ['Idade Media', 'Muralla', 'Rei'] },
    { word: 'Escola', hints: ['Alumnos', 'Encerado', 'Mestres'] },
    { word: 'Restaurante', hints: ['Comida', 'Camareiro', 'Mesas'] },
    { word: 'Cine', hints: ['Películas', 'Pantalla', 'Flocos de millo'] },
    { word: 'Igrexa', hints: ['Rezos', 'Campás', 'Relixión'] },
    { word: 'Parque', hints: ['Natureza urbana', 'Bancos', 'Randeeiras'] },
    { word: 'Estación de tren', hints: ['Andén', 'Billetes', 'Vías'] },
    { word: 'Perruquería', hints: ['Corte de pelo', 'Secador', 'Espello'] },
    { word: 'Hotel', hints: ['Aloxamento', 'Recepción', 'Cuartos'] },
    { word: 'Zoolóxico', hints: ['Animais', 'Gaiolas', 'Leóns'] },
    { word: 'Teatro', hints: ['Escenario', 'Actores', 'Pano'] },
    { word: 'Ximnasio', hints: ['Exercicio', 'Pesas', 'Músculos'] },
    { word: 'Granxa', hints: ['Gando', 'Tractor', 'Campo'] },
    { word: 'Piscina', hints: ['Bañador', 'Socorrista', 'Cloro'] },
    { word: 'Supermercado', hints: ['Carro', 'Caixa', 'Ofertas'] },
    { word: 'Farmacia', hints: ['Menciñas', 'Cruz verde', 'Receita'] },
    { word: 'Porto', hints: ['Barcos', 'Peirao', 'Guindastres'] },
    { word: 'Concello', hints: ['Alcalde', 'Praza', 'Vodas'] },
    { word: 'Cámping', hints: ['Saco de durmir', 'Fogueira', 'Vacacións'] },
    { word: 'Everest', hints: ['Cima máis alta', 'Nepal', 'Neve'] },
    { word: 'Sáhara', hints: ['Deserto africano', 'Dunas', 'Camelos'] },
  ],
  va: [
    { word: 'Platja', hints: ['Estiu', 'Arena', 'Onades'] },
    { word: 'Hospital', hints: ['Salut', 'Metges', 'Urgències'] },
    { word: 'Aeroport', hints: ['Viatges', 'Avions', 'Maletes'] },
    { word: 'Biblioteca', hints: ['Llibres', 'Silenci', 'Lectura'] },
    { word: 'Mercat', hints: ['Compres', 'Parades', 'Verdures'] },
    { word: 'Estadi', hints: ['Esport', 'Grades', 'Públic'] },
    { word: 'Museu', hints: ['Art', 'Quadres', 'Història'] },
    { word: 'Presó', hints: ['Reclusos', 'Reixes', 'Càstig'] },
    { word: 'Far', hints: ['Costa', 'Llum', 'Mariners'] },
    { word: 'Castell', hints: ['Edat mitjana', 'Muralla', 'Rei'] },
    { word: 'Escola', hints: ['Alumnes', 'Pissarra', 'Mestres'] },
    { word: 'Restaurant', hints: ['Menjar', 'Cambrer', 'Taules'] },
    { word: 'Cine', hints: ['Pel·lícules', 'Pantalla', 'Rosetes'] },
    { word: 'Església', hints: ['Pregària', 'Campanar', 'Religió'] },
    { word: 'Parc', hints: ['Natura urbana', 'Bancs', 'Gronxadors'] },
    { word: 'Estació', hints: ['Trens', 'Andana', 'Bitllets'] },
    { word: 'Aquàrium', hints: ['Peixos', 'Vidre', 'Taurons'] },
    { word: 'Hotel', hints: ['Allotjament', 'Recepció', 'Habitacions'] },
    { word: 'Zoològic', hints: ['Animals', 'Gàbies', 'Lleons'] },
    { word: 'Teatre', hints: ['Escenari', 'Actors', 'Teló'] },
    { word: 'Gimnàs', hints: ['Exercici', 'Peses', 'Músculs'] },
    { word: 'Granja', hints: ['Bestiar', 'Tractor', 'Camp'] },
    { word: 'Supermercat', hints: ['Carro', 'Prestatgeries', 'Compra setmanal'] },
    { word: 'Piscina', hints: ['Nadar', 'Banyador', 'Trampolí'] },
    { word: 'Farmàcia', hints: ['Medicaments', 'Creu verda', 'Recepta'] },
    { word: 'Port', hints: ['Vaixells', 'Moll', 'Amarrar'] },
    { word: 'Ajuntament', hints: ['Alcalde', 'Plaça major', 'Tràmits'] },
    { word: 'Càmping', hints: ['Tenda de campanya', 'Sac de dormir', 'Caravanes'] },
    { word: 'Everest', hints: ['Cim més alt', 'Nepal', 'Neu'] },
    { word: 'Sàhara', hints: ['Desert africà', 'Dunes', 'Camells'] },
  ],
}
