import type { WordEntry } from '../../domain/content/types'
import type { LocaleCode } from '../../domain/game/types'

export const transport: Partial<Record<LocaleCode, WordEntry[]>> = {
  ca: [
    { word: 'Cotxe', hints: ['Quatre rodes', 'Volant', 'Gasolina'] },
    { word: 'Avió', hints: ['Pel cel', 'Ales', 'Aeroport'] },
    { word: 'Bicicleta', hints: ['Pedals', 'Dues rodes', 'Cadena'] },
    { word: 'Metro', hints: ['Sota terra', 'Andana', 'Túnel'] },
    { word: 'Vaixell', hints: ['Pel mar', 'Coberta', 'Àncora'] },
    { word: 'Helicòpter', hints: ['Rotor', 'Aspes', 'Vol vertical'] },
    { word: 'Tramvia', hints: ['Vies urbanes', 'Elèctric', 'Catenària'] },
    { word: 'Patinet', hints: ['Sobre rodetes', 'Manillar', 'Dret a sobre'] },
    { word: 'Globus', hints: ['Aire calent', 'Cremador', 'Cistella'] },
    { word: 'Submarí', hints: ['Sota l’aigua', 'Periscopi', 'Profunditat'] },
    { word: 'Autobús', hints: ['Molts passatgers', 'Parada', 'Bitllet'] },
    { word: 'Tren', hints: ['Sobre rails', 'Vagons', 'Estació'] },
    { word: 'Moto', hints: ['Dues rodes', 'Casc', 'Manillar'] },
    { word: 'Camió', hints: ['Porta càrrega', 'Remolc', 'Mercaderies'] },
    { word: 'Taxi', hints: ['Groc i negre', 'Comptador del viatge', 'Llogar'] },
    { word: 'Furgoneta', hints: ['Repartiment', 'Caixa darrere', 'Paquets'] },
    { word: 'Tractor', hints: ['Al camp', 'Pagès', 'Llaurar'] },
    { word: 'Canoa', hints: ['Amb rem', 'Riu', 'Estreta'] },
    { word: 'Iot', hints: ['Luxe nàutic', 'Vela blanca', 'Ric'] },
    { word: 'Ferri', hints: ['Travessa l’estret', 'Cotxes a bord', 'Illa'] },
    { word: 'Trineu', hints: ['Sobre neu', 'Llisca', 'Gossos'] },
    { word: 'Monopatí', hints: ['Quatre rodetes', 'Salts', 'Taula'] },
    { word: 'Caravana', hints: ['Casa rodant', 'Acampada', 'Vacances'] },
    { word: 'Cohet', hints: ['A l’espai', 'Enlairament', 'Combustible'] },
    { word: 'Telefèric', hints: ['Penjat del cable', 'Muntanya', 'Cabina'] },
    { word: 'Carruatge', hints: ['Tirat per cavalls', 'Antic', 'Cotxer'] },
    { word: 'Quad', hints: ['Tot terreny', 'Aventura', 'Quatre rodes amples'] },
    { word: 'Ambulància', hints: ['Amb sirena', 'Emergència', 'Hospital'] },
    { word: 'Moto d’aigua', hints: ['Onades', 'Esquitxos', 'Ràpida'] },
    { word: 'Dirigible', hints: ['Globus allargat', 'Flota', 'Gas lleuger'] },
  ],
  en: [
    { word: 'Car', hints: ['Four wheels', 'Steering wheel', 'Petrol'] },
    { word: 'Plane', hints: ['Through the sky', 'Wings', 'Airport'] },
    { word: 'Bicycle', hints: ['Pedals', 'Two wheels', 'Chain'] },
    { word: 'Metro', hints: ['Rush hour', 'Platform', 'Tunnel'] },
    { word: 'Ship', hints: ['On the sea', 'Deck', 'Anchor'] },
    { word: 'Helicopter', hints: ['Spinning blades', 'Rotor', 'Vertical lift'] },
    { word: 'Tram', hints: ['City rails', 'Electric', 'Overhead wire'] },
    { word: 'Kick scooter', hints: ['Small wheels', 'Handlebar', 'Stand on it'] },
    { word: 'Hot-air balloon', hints: ['Flame', 'Burner', 'Basket'] },
    { word: 'Submarine', hints: ['Under water', 'Periscope', 'Deep dive'] },
    { word: 'Bus', hints: ['Many seats', 'Stop', 'Ticket'] },
    { word: 'Train', hints: ['On tracks', 'Carriages', 'Station'] },
    { word: 'Motorbike', hints: ['Two wheels', 'Helmet', 'Engine roar'] },
    { word: 'Lorry', hints: ['Carries cargo', 'Trailer', 'Goods'] },
    { word: 'Taxi', hints: ['Fare', 'Meter', 'For hire'] },
    { word: 'Van', hints: ['Deliveries', 'Boxy back', 'Parcels'] },
    { word: 'Tractor', hints: ['On the farm', 'Plough', 'Big wheels'] },
    { word: 'Canoe', hints: ['With a paddle', 'River', 'Narrow'] },
    { word: 'Yacht', hints: ['Luxury boat', 'White sail', 'Wealthy'] },
    { word: 'Ferry', hints: ['Crosses water', 'Cars aboard', 'Island'] },
    { word: 'Sledge', hints: ['On snow', 'Slides', 'Dogs pull it'] },
    { word: 'Skateboard', hints: ['Street tricks', 'Deck', 'Ollie'] },
    { word: 'Campervan', hints: ['Home on wheels', 'Road trip', 'Holiday'] },
    { word: 'Rocket', hints: ['Into space', 'Launch', 'Fuel'] },
    { word: 'Cable car', hints: ['Ski resort', 'Mountain', 'Cabin'] },
    { word: 'Stagecoach', hints: ['Horse drawn', 'Wild West', 'Old fashioned'] },
    { word: 'Quad bike', hints: ['Off road', 'Adventure', 'Four fat wheels'] },
    { word: 'Ambulance', hints: ['With siren', 'Emergency', 'Hospital'] },
    { word: 'Jet ski', hints: ['On the waves', 'Watersport', 'Fast spray'] },
    { word: 'Fire engine', hints: ['Ladder', 'Red', 'Hose'] },
  ],
  es: [
    { word: 'Coche', hints: ['Cuatro ruedas', 'Volante', 'Gasolina'] },
    { word: 'Avión', hints: ['Por el cielo', 'Alas', 'Aeropuerto'] },
    { word: 'Bicicleta', hints: ['Pedales', 'Dos ruedas', 'Cadena'] },
    { word: 'Metro', hints: ['Bajo la ciudad', 'Andén', 'Túnel'] },
    { word: 'Barco', hints: ['Por el mar', 'Cubierta', 'Ancla'] },
    { word: 'Helicóptero', hints: ['Rotor', 'Aspas', 'Vuelo vertical'] },
    { word: 'Tranvía', hints: ['Vías urbanas', 'Eléctrico', 'Catenaria'] },
    { word: 'Patinete', hints: ['Ruedas pequeñas', 'Manillar', 'De pie'] },
    { word: 'Globo aerostático', hints: ['Aire caliente', 'Quemador', 'Cesta'] },
    { word: 'Submarino', hints: ['Bajo el agua', 'Periscopio', 'Profundidad'] },
    { word: 'Autobús', hints: ['Muchos asientos', 'Parada', 'Billete'] },
    { word: 'Tren', hints: ['Sobre raíles', 'Vagones', 'Estación'] },
    { word: 'Moto', hints: ['Dos ruedas', 'Casco', 'Manillar'] },
    { word: 'Camión', hints: ['Lleva carga', 'Remolque', 'Mercancías'] },
    { word: 'Taxi', hints: ['Luz verde', 'Contador del viaje', 'Alquilar'] },
    { word: 'Furgoneta', hints: ['Reparto', 'Caja detrás', 'Paquetes'] },
    { word: 'Tractor', hints: ['En el campo', 'Arar', 'Agricultor'] },
    { word: 'Canoa', hints: ['Con remo', 'Río', 'Estrecha'] },
    { word: 'Yate', hints: ['Lujo náutico', 'Vela blanca', 'Rico'] },
    { word: 'Ferri', hints: ['Cruza el estrecho', 'Coches a bordo', 'Isla'] },
    { word: 'Trineo', hints: ['Sobre nieve', 'Resbala', 'Perros'] },
    { word: 'Monopatín', hints: ['Trucos urbanos', 'Tabla', 'Saltos'] },
    { word: 'Caravana', hints: ['Casa rodante', 'Acampada', 'Vacaciones'] },
    { word: 'Cohete', hints: ['Al espacio', 'Despegue', 'Combustible'] },
    { word: 'Teleférico', hints: ['Colgado del cable', 'Montaña', 'Cabina'] },
    { word: 'Carruaje', hints: ['Tirado por caballos', 'Antiguo', 'Cochero'] },
    { word: 'Quad', hints: ['Todoterreno', 'Aventura', 'Ruedas anchas'] },
    { word: 'Ambulancia', hints: ['Con sirena', 'Emergencia', 'Hospital'] },
    { word: 'Lancha', hints: ['Rápida en agua', 'Motor fueraborda', 'Estela'] },
    { word: 'Dirigible', hints: ['Globo alargado', 'Flota', 'Gas ligero'] },
  ],
  eu: [
    { word: 'Autoa', hints: ['Lau gurpil', 'Bolantea', 'Gasolina'] },
    { word: 'Hegazkina', hints: ['Zeruan zehar', 'Hegoak', 'Aireportua'] },
    { word: 'Bizikleta', hints: ['Pedalak', 'Bi gurpil', 'Katea'] },
    { word: 'Metroa', hints: ['Lurpean', 'Nasa', 'Tunela'] },
    { word: 'Itsasontzia', hints: ['Kapitaina', 'Bizkarra', 'Aingura'] },
    { word: 'Helikopteroa', hints: ['Helizea gora', 'Errotorea', 'Bertikalki igo'] },
    { word: 'Tranbia', hints: ['Hiri trenbidea', 'Elektrikoa', 'Goiko kablea'] },
    { word: 'Patinetea', hints: ['Gurpil txikiak', 'Eskulekua', 'Zutik'] },
    { word: 'Globoa', hints: ['Aire beroa', 'Erregailua', 'Saskia'] },
    { word: 'Urpekoa', hints: ['Torpedoa', 'Periskopioa', 'Sakonera'] },
    { word: 'Autobusa', hints: ['Bidaiari asko', 'Geltokia', 'Txartela'] },
    { word: 'Trena', hints: ['Errailen gainean', 'Bagoiak', 'Makinista'] },
    { word: 'Motoa', hints: ['Bi gurpil', 'Kaskoa', 'Eskulekua'] },
    { word: 'Kamioia', hints: ['Karga darama', 'Atoia', 'Salgaiak'] },
    { word: 'Taxia', hints: ['Argi berdea', 'Kontagailua', 'Alokatu'] },
    { word: 'Furgoneta', hints: ['Banaketa', 'Atzeko kutxa', 'Paketeak'] },
    { word: 'Traktorea', hints: ['Soroan', 'Goldatu', 'Nekazaria'] },
    { word: 'Kanoa', hints: ['Arraunarekin', 'Ibaia', 'Estua'] },
    { word: 'Yatea', hints: ['Luxuzko ontzia', 'Bela zuria', 'Aberatsa'] },
    { word: 'Ferrya', hints: ['Itsasoa zeharkatzen', 'Autoak barruan', 'Uhartea'] },
    { word: 'Lera', hints: ['Elurraren gainean', 'Irristatu', 'Txakurrak'] },
    { word: 'Skatea', hints: ['Kaleko trikimailuak', 'Oholtxoa', 'Jauziak'] },
    { word: 'Karabana', hints: ['Etxe ibiltaria', 'Kanpaketa', 'Oporrak'] },
    { word: 'Suziria', hints: ['Espaziora', 'Aireratzea', 'Erregaia'] },
    { word: 'Teleferikoa', hints: ['Kablean zintzilik', 'Mendia', 'Kabina'] },
    { word: 'Zalgurdia', hints: ['Zaldiek tiratua', 'Antzinakoa', 'Errauskine'] },
    { word: 'Quada', hints: ['Mendi ibilgailua', 'Abentura', 'Gurpil zabalak'] },
    { word: 'Anbulantzia', hints: ['Sirenarekin', 'Larrialdia', 'Ospitalea'] },
    { word: 'Txalupa', hints: ['Ur gaineko txikia', 'Kanpoko motorra', 'Arrantza'] },
    { word: 'Dirigiblea', hints: ['Globo luzanga', 'Flotatzen du', 'Gas arina'] },
  ],
  gl: [
    { word: 'Coche', hints: ['Catro rodas', 'Volante', 'Gasolina'] },
    { word: 'Avión', hints: ['Polo ceo', 'Ás', 'Aeroporto'] },
    { word: 'Bicicleta', hints: ['Pedais', 'Dúas rodas', 'Cadea'] },
    { word: 'Metro', hints: ['Baixo a cidade', 'Andén', 'Túnel'] },
    { word: 'Barco', hints: ['Polo mar', 'Cuberta', 'Áncora'] },
    { word: 'Helicóptero', hints: ['Rotor', 'Aspas', 'Voo vertical'] },
    { word: 'Tranvía', hints: ['Vías urbanas', 'Eléctrico', 'Catenaria'] },
    { word: 'Patinete', hints: ['Rodas pequenas', 'Guiador', 'De pé'] },
    { word: 'Globo aerostático', hints: ['Aire quente', 'Queimador', 'Cesta'] },
    { word: 'Submarino', hints: ['Baixo a auga', 'Periscopio', 'Profundidade'] },
    { word: 'Autobús', hints: ['Moitos asentos', 'Parada', 'Billete'] },
    { word: 'Tren', hints: ['Sobre raís', 'Vagóns', 'Estación'] },
    { word: 'Moto', hints: ['Dúas rodas', 'Casco', 'Guiador'] },
    { word: 'Camión', hints: ['Leva carga', 'Remolque', 'Mercadorías'] },
    { word: 'Taxi', hints: ['Luz verde', 'Contador da viaxe', 'Alugar'] },
    { word: 'Furgoneta', hints: ['Reparto', 'Caixa detrás', 'Paquetes'] },
    { word: 'Tractor', hints: ['No campo', 'Arar', 'Labrego'] },
    { word: 'Canoa', hints: ['Con remo', 'Río', 'Estreita'] },
    { word: 'Iate', hints: ['Luxo náutico', 'Vela branca', 'Rico'] },
    { word: 'Ferri', hints: ['Cruza a ría', 'Coches a bordo', 'Illa'] },
    { word: 'Trineo', hints: ['Sobre neve', 'Esvara', 'Cans'] },
    { word: 'Monopatín', hints: ['Trucos urbanos', 'Táboa', 'Saltos'] },
    { word: 'Caravana', hints: ['Casa rodante', 'Acampada', 'Vacacións'] },
    { word: 'Foguete', hints: ['Ao espazo', 'Despegue', 'Combustible'] },
    { word: 'Teleférico', hints: ['Colgado do cable', 'Montaña', 'Cabina'] },
    { word: 'Carruaxe', hints: ['Tirado por cabalos', 'Antigo', 'Cocheiro'] },
    { word: 'Quad', hints: ['Todoterreo', 'Aventura', 'Rodas anchas'] },
    { word: 'Ambulancia', hints: ['Con sirena', 'Emerxencia', 'Hospital'] },
    { word: 'Lancha', hints: ['Rápida na auga', 'Motor fóra borda', 'Pesca'] },
    { word: 'Dirixible', hints: ['Globo alongado', 'Flota', 'Gas lixeiro'] },
  ],
  va: [
    { word: 'Cotxe', hints: ['Quatre rodes', 'Volant', 'Gasolina'] },
    { word: 'Avió', hints: ['Pel cel', 'Ales', 'Aeroport'] },
    { word: 'Bicicleta', hints: ['Pedals', 'Dos rodes', 'Cadena'] },
    { word: 'Metro', hints: ['Davall la ciutat', 'Andana', 'Túnel'] },
    { word: 'Vaixell', hints: ['Per la mar', 'Coberta', 'Àncora'] },
    { word: 'Helicòpter', hints: ['Hèlix amunt', 'Aspes', 'Vol vertical'] },
    { word: 'Tramvia', hints: ['Vies urbanes', 'Elèctric', 'Catenària'] },
    { word: 'Patinet', hints: ['Rodes menudes', 'Manillar', 'Dret damunt'] },
    { word: 'Globus', hints: ['Aire calent', 'Cremador', 'Cistella'] },
    { word: 'Submarí', hints: ['Davall l’aigua', 'Periscopi', 'Profunditat'] },
    { word: 'Autobús', hints: ['Molts seients', 'Parada', 'Bitllet'] },
    { word: 'Tren', hints: ['Sobre rails', 'Vagons', 'Estació'] },
    { word: 'Moto', hints: ['Dos rodes', 'Casc', 'Manillar'] },
    { word: 'Camió', hints: ['Porta càrrega', 'Remolc', 'Mercaderies'] },
    { word: 'Taxi', hints: ['Llum verda', 'Comptador del viatge', 'Llogar'] },
    { word: 'Furgoneta', hints: ['Repartiment', 'Caixa darrere', 'Paquets'] },
    { word: 'Tractor', hints: ['Al camp', 'Llaurar', 'Llaurador'] },
    { word: 'Canoa', hints: ['Amb rem', 'Riu', 'Estreta'] },
    { word: 'Iot', hints: ['Luxe nàutic', 'Vela blanca', 'Ric'] },
    { word: 'Ferri', hints: ['Travessa la mar', 'Cotxes a bord', 'Illa'] },
    { word: 'Trineu', hints: ['Sobre neu', 'Llisca', 'Gossos'] },
    { word: 'Monopatí', hints: ['Trucs urbans', 'Taula', 'Salts'] },
    { word: 'Caravana', hints: ['Casa rodant', 'Acampada', 'Vacances'] },
    { word: 'Coet', hints: ['A l’espai', 'Enlairament', 'Combustible'] },
    { word: 'Telefèric', hints: ['Penjat del cable', 'Muntanya', 'Cabina'] },
    { word: 'Carruatge', hints: ['Tirat per cavalls', 'Antic', 'Cotxer'] },
    { word: 'Quad', hints: ['Tot terreny', 'Aventura', 'Rodes amples'] },
    { word: 'Ambulància', hints: ['Amb sirena', 'Emergència', 'Hospital'] },
    { word: 'Llanxa', hints: ['Ràpida en l’aigua', 'Motor fora borda', 'Pesca'] },
    { word: 'Dirigible', hints: ['Globus allargat', 'Flota', 'Gas lleuger'] },
  ],
}
