import type { WordEntry } from '../../domain/content/types'
import type { LocaleCode } from '../../domain/game/types'

export const transport: Partial<Record<LocaleCode, WordEntry[]>> = {
  ca: [
    { word: 'Cotxe', hint: 'Quatre rodes' },
    { word: 'Avió', hint: 'Pel cel' },
    { word: 'Bicicleta', hint: 'Pedals' },
    { word: 'Metro', hint: 'Sota terra' },
    { word: 'Vaixell', hint: 'Pel mar' },
    { word: 'Helicòpter', hint: 'Hèlix amunt' },
    { word: 'Tramvia', hint: 'Vies urbanes' },
    { word: 'Patinet', hint: 'Sobre rodetes' },
    { word: 'Globus', hint: 'Aire calent' },
    { word: 'Submarí', hint: 'Sota l aigua' },
    { word: 'Autobús', hint: 'Molts passatgers' },
    { word: 'Tren', hint: 'Sobre rails' },
    { word: 'Moto', hint: 'Dues rodes' },
    { word: 'Camió', hint: 'Porta càrrega' },
    { word: 'Taxi', hint: 'Groc i negre' },
    { word: 'Furgoneta', hint: 'Repartiment' },
    { word: 'Tractor', hint: 'Al camp' },
    { word: 'Canoa', hint: 'Amb rem' },
    { word: 'Iot', hint: 'Luxe nàutic' },
    { word: 'Ferri', hint: 'Travessa estret' },
    { word: 'Trineu', hint: 'Sobre neu' },
    { word: 'Monopatí', hint: 'Quatre rodetes' },
    { word: 'Caravana', hint: 'Casa rodant' },
    { word: 'Cohet', hint: 'A l espai' },
    { word: 'Telefèric', hint: 'Penjat del cable' },
    { word: 'Carruatge', hint: 'Tirat per cavalls' },
    { word: 'Quad', hint: 'Tot terreny' },
    { word: 'Ambulància', hint: 'Amb sirena' },
    { word: 'Velomar', hint: 'A la platja' },
    { word: 'Dirigible', hint: 'Globus allargat' },
  ],
  en: [
    { word: 'Car', hint: 'Four wheels' },
    { word: 'Plane', hint: 'Through the sky' },
    { word: 'Bicycle', hint: 'Pedals' },
    { word: 'Subway', hint: 'Underground' },
    { word: 'Ship', hint: 'On the sea' },
    { word: 'Helicopter', hint: 'Spinning blades' },
    { word: 'Tram', hint: 'City rails' },
    { word: 'Scooter', hint: 'Small wheels' },
    { word: 'Balloon', hint: 'Hot air' },
    { word: 'Submarine', hint: 'Under water' },
    { word: 'Bus', hint: 'Many seats' },
    { word: 'Train', hint: 'On tracks' },
    { word: 'Motorbike', hint: 'Two wheels' },
    { word: 'Truck', hint: 'Carries cargo' },
    { word: 'Taxi', hint: 'Yellow cab' },
    { word: 'Van', hint: 'Deliveries' },
    { word: 'Tractor', hint: 'On the farm' },
    { word: 'Canoe', hint: 'With a paddle' },
    { word: 'Yacht', hint: 'Luxury boat' },
    { word: 'Ferry', hint: 'Crosses water' },
    { word: 'Sled', hint: 'On snow' },
    { word: 'Skateboard', hint: 'Street tricks' },
    { word: 'Camper', hint: 'Home on wheels' },
    { word: 'Rocket', hint: 'Into space' },
    { word: 'Cable car', hint: 'Hung on cable' },
    { word: 'Carriage', hint: 'Horse drawn' },
    { word: 'Quad bike', hint: 'Off road' },
    { word: 'Ambulance', hint: 'With siren' },
    { word: 'Jet ski', hint: 'On the waves' },
    { word: 'Blimp', hint: 'Floating airship' },
  ],
  es: [
    { word: 'Coche', hint: 'Cuatro ruedas' },
    { word: 'Avión', hint: 'Por el cielo' },
    { word: 'Bicicleta', hint: 'Pedales' },
    { word: 'Metro', hint: 'Bajo la ciudad' },
    { word: 'Barco', hint: 'Por el mar' },
    { word: 'Helicóptero', hint: 'Hélice arriba' },
    { word: 'Tranvía', hint: 'Vías urbanas' },
    { word: 'Patinete', hint: 'Ruedas pequeñas' },
    { word: 'Globo', hint: 'Aire caliente' },
    { word: 'Submarino', hint: 'Bajo el agua' },
    { word: 'Autobús', hint: 'Muchos asientos' },
    { word: 'Tren', hint: 'Sobre raíles' },
    { word: 'Moto', hint: 'Dos ruedas' },
    { word: 'Camión', hint: 'Lleva carga' },
    { word: 'Taxi', hint: 'Amarillo urbano' },
    { word: 'Furgoneta', hint: 'Reparto' },
    { word: 'Tractor', hint: 'En el campo' },
    { word: 'Canoa', hint: 'Con remo' },
    { word: 'Yate', hint: 'Lujo náutico' },
    { word: 'Ferri', hint: 'Cruza el estrecho' },
    { word: 'Trineo', hint: 'Sobre nieve' },
    { word: 'Monopatín', hint: 'Trucos urbanos' },
    { word: 'Caravana', hint: 'Casa rodante' },
    { word: 'Cohete', hint: 'Al espacio' },
    { word: 'Teleférico', hint: 'Colgado del cable' },
    { word: 'Carruaje', hint: 'Tirado por caballos' },
    { word: 'Quad', hint: 'Todoterreno' },
    { word: 'Ambulancia', hint: 'Con sirena' },
    { word: 'Lancha', hint: 'Rápida en agua' },
    { word: 'Dirigible', hint: 'Globo alargado' },
  ],
  eu: [
    { word: 'Autoa', hint: 'Lau gurpil' },
    { word: 'Hegazkina', hint: 'Zeruan zehar' },
    { word: 'Bizikleta', hint: 'Pedalak' },
    { word: 'Metroa', hint: 'Lurpean' },
    { word: 'Itsasontzia', hint: 'Itsasoan' },
    { word: 'Helikopteroa', hint: 'Helizea gora' },
    { word: 'Tranbia', hint: 'Hiri trenbidea' },
    { word: 'Patinetea', hint: 'Gurpil txikiak' },
    { word: 'Globoa', hint: 'Aire beroa' },
    { word: 'Urpekoa', hint: 'Uraren azpian' },
    { word: 'Autobusa', hint: 'Bidaiari asko' },
    { word: 'Trena', hint: 'Errailen gainean' },
    { word: 'Motorra', hint: 'Bi gurpil' },
    { word: 'Kamioia', hint: 'Karga darama' },
    { word: 'Taxia', hint: 'Hiriko horia' },
    { word: 'Furgoneta', hint: 'Banaketa' },
    { word: 'Traktorea', hint: 'Soroan' },
    { word: 'Kanoa', hint: 'Arraunarekin' },
    { word: 'Yatea', hint: 'Luxuzko ontzia' },
    { word: 'Ferrya', hint: 'Itsasoa zeharkatzen' },
    { word: 'Lera', hint: 'Elurraren gainean' },
    { word: 'Skatea', hint: 'Kaleko trikimailuak' },
    { word: 'Karabana', hint: 'Etxe ibiltaria' },
    { word: 'Suziria', hint: 'Espaziora' },
    { word: 'Teleferikoa', hint: 'Kablean zintzilik' },
    { word: 'Gurdia', hint: 'Zaldiek tiratua' },
    { word: 'Quada', hint: 'Mendi ibilgailua' },
    { word: 'Anbulantzia', hint: 'Sirenarekin' },
    { word: 'Txalupa', hint: 'Ur gaineko txikia' },
    { word: 'Dirigiblea', hint: 'Globo luzanga' },
  ],
  gl: [
    { word: 'Coche', hint: 'Catro rodas' },
    { word: 'Avión', hint: 'Polo ceo' },
    { word: 'Bicicleta', hint: 'Pedais' },
    { word: 'Metro', hint: 'Baixo a cidade' },
    { word: 'Barco', hint: 'Polo mar' },
    { word: 'Helicóptero', hint: 'Hélice arriba' },
    { word: 'Tranvía', hint: 'Vías urbanas' },
    { word: 'Patinete', hint: 'Rodas pequenas' },
    { word: 'Globo', hint: 'Aire quente' },
    { word: 'Submarino', hint: 'Baixo a auga' },
    { word: 'Autobús', hint: 'Moitos asentos' },
    { word: 'Tren', hint: 'Sobre raís' },
    { word: 'Moto', hint: 'Dúas rodas' },
    { word: 'Camión', hint: 'Leva carga' },
    { word: 'Taxi', hint: 'Amarelo urbano' },
    { word: 'Furgoneta', hint: 'Reparto' },
    { word: 'Tractor', hint: 'No campo' },
    { word: 'Canoa', hint: 'Con remo' },
    { word: 'Iate', hint: 'Luxo náutico' },
    { word: 'Ferri', hint: 'Cruza a ría' },
    { word: 'Zorra', hint: 'Sobre neve' },
    { word: 'Monopatín', hint: 'Trucos urbanos' },
    { word: 'Caravana', hint: 'Casa rodante' },
    { word: 'Foguete', hint: 'Ao espazo' },
    { word: 'Teleférico', hint: 'Colgado do cable' },
    { word: 'Carruaxe', hint: 'Tirado por cabalos' },
    { word: 'Quad', hint: 'Todoterreo' },
    { word: 'Ambulancia', hint: 'Con sirena' },
    { word: 'Lancha', hint: 'Rápida na auga' },
    { word: 'Dirixible', hint: 'Globo alongado' },
  ],
  va: [
    { word: 'Cotxe', hint: 'Quatre rodes' },
    { word: 'Avió', hint: 'Pel cel' },
    { word: 'Bicicleta', hint: 'Pedals' },
    { word: 'Metro', hint: 'Davall la ciutat' },
    { word: 'Vaixell', hint: 'Per la mar' },
    { word: 'Helicòpter', hint: 'Hèlix amunt' },
    { word: 'Tramvia', hint: 'Vies urbanes' },
    { word: 'Patinet', hint: 'Rodes menudes' },
    { word: 'Globus', hint: 'Aire calent' },
    { word: 'Submarí', hint: 'Davall l aigua' },
    { word: 'Autobús', hint: 'Molts seients' },
    { word: 'Tren', hint: 'Sobre rails' },
    { word: 'Moto', hint: 'Dos rodes' },
    { word: 'Camió', hint: 'Porta càrrega' },
    { word: 'Taxi', hint: 'Groc urbà' },
    { word: 'Furgoneta', hint: 'Repartiment' },
    { word: 'Tractor', hint: 'Al camp' },
    { word: 'Canoa', hint: 'Amb rem' },
    { word: 'Iot', hint: 'Luxe nàutic' },
    { word: 'Ferri', hint: 'Travessa la mar' },
    { word: 'Trineu', hint: 'Sobre neu' },
    { word: 'Monopatí', hint: 'Trucs urbans' },
    { word: 'Caravana', hint: 'Casa rodant' },
    { word: 'Coet', hint: 'A l espai' },
    { word: 'Telefèric', hint: 'Penjat del cable' },
    { word: 'Carruatge', hint: 'Tirat per cavalls' },
    { word: 'Quad', hint: 'Tot terreny' },
    { word: 'Ambulància', hint: 'Amb sirena' },
    { word: 'Llanxa', hint: 'Ràpida en l aigua' },
    { word: 'Dirigible', hint: 'Globus allargat' },
  ],
}
